package wow_MythicKeystoneAffix

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMythicKeystoneAffixResponse is the unified BNet representation for MythicKeystoneAffix.
type BNetMythicKeystoneAffix struct{}

// MythicKeystoneAffixResponse represents the raw CN API response for MythicKeystoneAffix.
type CNMythicKeystoneAffix BNetMythicKeystoneAffix

// ToBNet converts the CN response to the unified BNetMythicKeystoneAffixResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneAffix) ToBNet() any {
	return r
}
