

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_MythicKeystoneAffix

type MythicKeystoneAffixesIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Affixes []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name *string `json:"name"`
	} `json:"affixes"`
}





// MythicKeystoneAffixesIndex represents the raw CN API response for MythicKeystoneAffixesIndex.
type CNMythicKeystoneAffixesIndexModel MythicKeystoneAffixesIndexModel

// ToBNet converts the CN  to the unified BNetMythicKeystoneAffixesIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneAffixesIndexModel) ToBNet() any {
	return r
}
