package wow_MythicKeystoneAffix

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMythicKeystoneAffixMediaResponse is the unified BNet representation for MythicKeystoneAffixMedia.
type BNetMythicKeystoneAffixMedia struct{}

// MythicKeystoneAffixMediaResponse represents the raw CN API response for MythicKeystoneAffixMedia.
type CNMythicKeystoneAffixMedia BNetMythicKeystoneAffixMedia

// ToBNet converts the CN response to the unified BNetMythicKeystoneAffixMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneAffixMedia) ToBNet() any {
	return r
}
