package wow_MythicKeystoneAffix

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMythicKeystoneAffixesIndexResponse is the unified BNet representation for MythicKeystoneAffixesIndex.
type BNetMythicKeystoneAffixesIndex struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Affixes []struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name *string `json:"name"`
		Id   int     `json:"id"`
	} `json:"affixes"`
}

// MythicKeystoneAffixesIndexResponse represents the raw CN API response for MythicKeystoneAffixesIndex.
type CNMythicKeystoneAffixesIndex BNetMythicKeystoneAffixesIndex

// ToBNet converts the CN response to the unified BNetMythicKeystoneAffixesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneAffixesIndex) ToBNet() any {
	return r
}
