package wow_TechTalent

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetTechTalentTreeResponse is the unified BNet representation for TechTalentTree.
type BNetTechTalentTree struct{}

// TechTalentTreeResponse represents the raw CN API response for TechTalentTree.
type CNTechTalentTree BNetTechTalentTree

// ToBNet converts the CN response to the unified BNetTechTalentTreeResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTechTalentTree) ToBNet() any {
	return r
}
