package wow_TechTalent

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetTechTalentIndexResponse is the unified BNet representation for TechTalentIndex.
type BNetTechTalentIndex struct{}

// TechTalentIndexResponse represents the raw CN API response for TechTalentIndex.
type CNTechTalentIndex BNetTechTalentIndex

// ToBNet converts the CN response to the unified BNetTechTalentIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTechTalentIndex) ToBNet() any {
	return r
}
