

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_TechTalent

type TechTalentMediaModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Assets []struct {
		FileDataID int    `json:"file_data_id,omitzero"`
		Key        string `json:"key,omitzero"`
		Value      string `json:"value,omitzero"`
	} `json:"assets"`
}





// TechTalentMedia represents the raw CN API response for TechTalentMedia.
type CNTechTalentMediaModel TechTalentMediaModel

// ToBNet converts the CN  to the unified BNetTechTalentMedia.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTechTalentMediaModel) ToBNet() any {
	return r
}
