package wow_TechTalent

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetTechTalentResponse is the unified BNet representation for TechTalent.
type BNetTechTalent struct{}

// TechTalentResponse represents the raw CN API response for TechTalent.
type CNTechTalent BNetTechTalent

// ToBNet converts the CN response to the unified BNetTechTalentResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTechTalent) ToBNet() any {
	return r
}
