

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_TechTalent

type TechTalentTreeModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ID       int `json:"id,omitzero"`
	MaxTiers int `json:"max_tiers,omitzero"`
	Talents  []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"talents"`
}





// TechTalentTree represents the raw CN API response for TechTalentTree.
type CNTechTalentTreeModel TechTalentTreeModel

// ToBNet converts the CN  to the unified BNetTechTalentTree.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTechTalentTreeModel) ToBNet() any {
	return r
}
