

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_TechTalent

type TechTalentTreeIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	TalentTrees []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitempty,omitzero"`
	} `json:"talent_trees"`
}





// TechTalentTreeIndex represents the raw CN API response for TechTalentTreeIndex.
type CNTechTalentTreeIndexModel TechTalentTreeIndexModel

// ToBNet converts the CN  to the unified BNetTechTalentTreeIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTechTalentTreeIndexModel) ToBNet() any {
	return r
}
