package wow_CharacterStatistics

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterStatisticsSummaryResponse is the unified BNet representation for CharacterStatisticsSummary.
type BNetCharacterStatisticsSummary struct{}

// CharacterStatisticsSummaryResponse represents the raw CN API response for CharacterStatisticsSummary.
type CNCharacterStatisticsSummary BNetCharacterStatisticsSummary

// ToBNet converts the CN response to the unified BNetCharacterStatisticsSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterStatisticsSummary) ToBNet() any {
	return r
}
