// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterStatistics

import "github.com/jinzhu/copier"

type CharacterStatisticsSummaryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Agility struct {
		Base      int `json:"base,omitzero"`
		Effective int `json:"effective,omitzero"`
	} `json:"agility"`
	Armor struct {
		Base      int `json:"base"`
		Effective int `json:"effective,omitzero"`
	} `json:"armor"`
	AttackPower int `json:"attack_power,omitzero"`
	Avoidance   struct {
		RatingBonus      float64 `json:"rating_bonus,omitzero"`
		RatingNormalized int     `json:"rating_normalized,omitzero"`
	} `json:"avoidance"`
	Block struct {
		RatingBonus      float64 `json:"rating_bonus"`
		RatingNormalized int     `json:"rating_normalized"`
		Value            float64 `json:"value,omitzero"`
	} `json:"block"`
	BonusArmor int `json:"bonus_armor"`
	Character  struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name  string `json:"name,omitzero"`
		Realm struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"realm"`
	} `json:"character"`
	Dodge struct {
		RatingBonus      float64 `json:"rating_bonus"`
		RatingNormalized int     `json:"rating_normalized"`
		Value            float64 `json:"value,omitzero"`
	} `json:"dodge"`
	Health    int `json:"health,omitzero"`
	Intellect struct {
		Base      int `json:"base,omitzero"`
		Effective int `json:"effective,omitzero"`
	} `json:"intellect"`
	Lifesteal struct {
		RatingBonus      float64 `json:"rating_bonus"`
		RatingNormalized int     `json:"rating_normalized"`
		Value            float64 `json:"value"`
	} `json:"lifesteal"`
	MainHandDamageMax float64 `json:"main_hand_damage_max,omitzero"`
	MainHandDamageMin float64 `json:"main_hand_damage_min,omitzero"`
	MainHandDps       float64 `json:"main_hand_dps,omitzero"`
	MainHandSpeed     float64 `json:"main_hand_speed,omitzero"`
	ManaRegen         float64 `json:"mana_regen,omitzero"`
	ManaRegenCombat   float64 `json:"mana_regen_combat,omitzero"`
	Mastery           struct {
		RatingBonus      float64 `json:"rating_bonus,omitzero"`
		RatingNormalized int     `json:"rating_normalized,omitzero"`
		Value            float64 `json:"value,omitzero"`
	} `json:"mastery"`
	MeleeCrit struct {
		RatingBonus      float64 `json:"rating_bonus,omitzero"`
		RatingNormalized int     `json:"rating_normalized,omitzero"`
		Value            float64 `json:"value,omitzero"`
	} `json:"melee_crit"`
	MeleeHaste struct {
		RatingBonus      float64 `json:"rating_bonus,omitzero"`
		RatingNormalized int     `json:"rating_normalized,omitzero"`
		Value            float64 `json:"value,omitzero"`
	} `json:"melee_haste"`
	OffHandDamageMax float64 `json:"off_hand_damage_max"`
	OffHandDamageMin float64 `json:"off_hand_damage_min"`
	OffHandDps       float64 `json:"off_hand_dps"`
	OffHandSpeed     float64 `json:"off_hand_speed,omitzero"`
	Parry            struct {
		RatingBonus      float64 `json:"rating_bonus"`
		RatingNormalized int     `json:"rating_normalized"`
		Value            float64 `json:"value"`
	} `json:"parry"`
	Power     int `json:"power,omitzero"`
	PowerType struct {
		ID  int `json:"id"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"power_type"`
	RangedCrit struct {
		RatingBonus      float64 `json:"rating_bonus,omitzero"`
		RatingNormalized int     `json:"rating_normalized,omitzero"`
		Value            float64 `json:"value,omitzero"`
	} `json:"ranged_crit"`
	RangedHaste struct {
		RatingBonus      float64 `json:"rating_bonus,omitzero"`
		RatingNormalized int     `json:"rating_normalized,omitzero"`
		Value            float64 `json:"value,omitzero"`
	} `json:"ranged_haste"`
	Speed struct {
		RatingBonus      float64 `json:"rating_bonus,omitzero"`
		RatingNormalized int     `json:"rating_normalized,omitzero"`
	} `json:"speed"`
	SpellCrit struct {
		RatingBonus      float64 `json:"rating_bonus,omitzero"`
		RatingNormalized int     `json:"rating_normalized,omitzero"`
		Value            float64 `json:"value,omitzero"`
	} `json:"spell_crit"`
	SpellHaste struct {
		RatingBonus      float64 `json:"rating_bonus,omitzero"`
		RatingNormalized int     `json:"rating_normalized,omitzero"`
		Value            float64 `json:"value,omitzero"`
	} `json:"spell_haste"`
	SpellPenetration int `json:"spell_penetration"`
	SpellPower       int `json:"spell_power,omitzero"`
	Stamina          struct {
		Base      int `json:"base,omitzero"`
		Effective int `json:"effective,omitzero"`
	} `json:"stamina"`
	Strength struct {
		Base      int `json:"base,omitzero"`
		Effective int `json:"effective,omitzero"`
	} `json:"strength"`
	Versatility                 float64 `json:"versatility,omitzero"`
	VersatilityDamageDoneBonus  float64 `json:"versatility_damage_done_bonus,omitzero"`
	VersatilityDamageTakenBonus float64 `json:"versatility_damage_taken_bonus,omitzero"`
	VersatilityHealingDoneBonus float64 `json:"versatility_healing_done_bonus,omitzero"`
}

// CharacterStatisticsSummary represents the raw CN API response for CharacterStatisticsSummary.
type CNCharacterStatisticsSummaryModel struct {
	Agility struct {
		Base      int `json:"base"`
		Effective int `json:"effective"`
	} `json:"agility"`
	Armor struct {
		Base      int `json:"base"`
		Effective int `json:"effective"`
	} `json:"armor"`
	AttackPower int `json:"attack_power"`
	Avoidance   struct {
		RatingBonus      float64 `json:"rating_bonus"`
		RatingNormalized int     `json:"rating_normalized"`
	} `json:"avoidance"`
	Block struct {
		RatingBonus      int `json:"rating_bonus"`
		RatingNormalized int `json:"rating_normalized"`
		Value            int `json:"value"`
	} `json:"block"`
	BonusArmor int `json:"bonus_armor"`
	Character  struct {
		Name  string `json:"name"`
		Realm struct {
			Name string `json:"name"`
			Slug string `json:"slug"`
		} `json:"realm"`
	} `json:"character"`
	Dodge struct {
		RatingBonus      int     `json:"rating_bonus"`
		RatingNormalized int     `json:"rating_normalized"`
		Value            float64 `json:"value"`
	} `json:"dodge"`
	Health    int `json:"health"`
	Intellect struct {
		Base      int `json:"base"`
		Effective int `json:"effective"`
	} `json:"intellect"`
	Lifesteal struct {
		RatingBonus      int `json:"rating_bonus"`
		RatingNormalized int `json:"rating_normalized"`
		Value            int `json:"value"`
	} `json:"lifesteal"`
	MainHandDamageMax float64 `json:"main_hand_damage_max"`
	MainHandDamageMin float64 `json:"main_hand_damage_min"`
	MainHandDps       float64 `json:"main_hand_dps"`
	MainHandSpeed     float64 `json:"main_hand_speed"`
	ManaRegen         int     `json:"mana_regen"`
	ManaRegenCombat   int     `json:"mana_regen_combat"`
	Mastery           struct {
		RatingBonus      float64 `json:"rating_bonus"`
		RatingNormalized int     `json:"rating_normalized"`
		Value            float64 `json:"value"`
	} `json:"mastery"`
	MeleeCrit struct {
		RatingBonus      float64 `json:"rating_bonus"`
		RatingNormalized int     `json:"rating_normalized"`
		Value            float64 `json:"value"`
	} `json:"melee_crit"`
	MeleeHaste struct {
		RatingBonus      float64 `json:"rating_bonus"`
		RatingNormalized int     `json:"rating_normalized"`
		Value            float64 `json:"value"`
	} `json:"melee_haste"`
	OffHandDamageMax float64 `json:"off_hand_damage_max"`
	OffHandDamageMin float64 `json:"off_hand_damage_min"`
	OffHandDps       float64 `json:"off_hand_dps"`
	OffHandSpeed     float64 `json:"off_hand_speed"`
	Parry            struct {
		RatingBonus      int `json:"rating_bonus"`
		RatingNormalized int `json:"rating_normalized"`
		Value            int `json:"value"`
	} `json:"parry"`
	Power     int `json:"power"`
	PowerType struct {
		Name string `json:"name"`
	} `json:"power_type"`
	RangedCrit struct {
		RatingBonus      float64 `json:"rating_bonus"`
		RatingNormalized int     `json:"rating_normalized"`
		Value            float64 `json:"value"`
	} `json:"ranged_crit"`
	RangedHaste struct {
		RatingBonus      float64 `json:"rating_bonus"`
		RatingNormalized int     `json:"rating_normalized"`
		Value            float64 `json:"value"`
	} `json:"ranged_haste"`
	Speed struct {
		RatingBonus      int `json:"rating_bonus"`
		RatingNormalized int `json:"rating_normalized"`
	} `json:"speed"`
	SpellCrit struct {
		RatingBonus      float64 `json:"rating_bonus"`
		RatingNormalized int     `json:"rating_normalized"`
		Value            float64 `json:"value"`
	} `json:"spell_crit"`
	SpellHaste struct {
		RatingBonus      float64 `json:"rating_bonus"`
		RatingNormalized int     `json:"rating_normalized"`
		Value            float64 `json:"value"`
	} `json:"spell_haste"`
	SpellPenetration int `json:"spell_penetration"`
	SpellPower       int `json:"spell_power"`
	Stamina          struct {
		Base      int `json:"base"`
		Effective int `json:"effective"`
	} `json:"stamina"`
	Strength struct {
		Base      int `json:"base"`
		Effective int `json:"effective"`
	} `json:"strength"`
	Versatility                 int     `json:"versatility"`
	VersatilityDamageDoneBonus  float64 `json:"versatility_damage_done_bonus"`
	VersatilityDamageTakenBonus float64 `json:"versatility_damage_taken_bonus"`
	VersatilityHealingDoneBonus float64 `json:"versatility_healing_done_bonus"`
}

// ToBNet converts the CN  to the unified BNetCharacterStatisticsSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterStatisticsSummaryModel) ToBNet() any {
	b := &CharacterStatisticsSummaryModel{}
	copier.Copy(b, r)
	return b
}
