

package wowClassic_Item

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// ItemSubclassModel is the unified BNet representation for ItemSubclass.
type ItemSubclassModel struct{}




// ItemSubclass represents the raw CN API response for ItemSubclass.
type CNItemSubclassModel ItemSubclassModel

// ToBNet converts the CN  to the unified BNetItemSubclass.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemSubclassModel) ToBNet() any {
	return r
}
