package wowClassic_Item

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetItemResponse is the unified BNet representation for Item.
type BNetItem struct{}

// ItemResponse represents the raw CN API response for Item.
type CNItem BNetItem

// ToBNet converts the CN response to the unified BNetItemResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItem) ToBNet() any {
	return r
}
