package wowClassic_Item

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetItemClassResponse is the unified BNet representation for ItemClass.
type BNetItemClass struct{}

// ItemClassResponse represents the raw CN API response for ItemClass.
type CNItemClass BNetItemClass

// ToBNet converts the CN response to the unified BNetItemClassResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemClass) ToBNet() any {
	return r
}
