

package wowClassic_Item

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// ItemModel is the unified BNet representation for Item.
type ItemModel struct{}




// Item represents the raw CN API response for Item.
type CNItemModel ItemModel

// ToBNet converts the CN  to the unified BNetItem.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemModel) ToBNet() any {
	return r
}
