

package wowClassic_Item

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// ItemMediaModel is the unified BNet representation for ItemMedia.
type ItemMediaModel struct{}




// ItemMedia represents the raw CN API response for ItemMedia.
type CNItemMediaModel ItemMediaModel

// ToBNet converts the CN  to the unified BNetItemMedia.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemMediaModel) ToBNet() any {
	return r
}
