

package wowClassic_Item

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// ItemClassModel is the unified BNet representation for ItemClass.
type ItemClassModel struct{}




// ItemClass represents the raw CN API response for ItemClass.
type CNItemClassModel ItemClassModel

// ToBNet converts the CN  to the unified BNetItemClass.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemClassModel) ToBNet() any {
	return r
}
