

package wowClassic_Item

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// ItemClassesIndexModel is the unified BNet representation for ItemClassesIndex.
type ItemClassesIndexModel struct{}




// ItemClassesIndex represents the raw CN API response for ItemClassesIndex.
type CNItemClassesIndexModel ItemClassesIndexModel

// ToBNet converts the CN  to the unified BNetItemClassesIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemClassesIndexModel) ToBNet() any {
	return r
}
