package wowClassic_Item

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetItemMediaResponse is the unified BNet representation for ItemMedia.
type BNetItemMedia struct{}

// ItemMediaResponse represents the raw CN API response for ItemMedia.
type CNItemMedia BNetItemMedia

// ToBNet converts the CN response to the unified BNetItemMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemMedia) ToBNet() any {
	return r
}
