package wowClassic_Item

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetItemSearchResponse is the unified BNet representation for ItemSearch.
type BNetItemSearch struct{}

// ItemSearchResponse represents the raw CN API response for ItemSearch.
type CNItemSearch BNetItemSearch

// ToBNet converts the CN response to the unified BNetItemSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemSearch) ToBNet() any {
	return r
}
