package wow_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPvPLeaderboardResponse is the unified BNet representation for PvPLeaderboard.
type BNetPvPLeaderboard struct{}

// PvPLeaderboardResponse represents the raw CN API response for PvPLeaderboard.
type CNPvPLeaderboard BNetPvPLeaderboard

// ToBNet converts the CN response to the unified BNetPvPLeaderboardResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPLeaderboard) ToBNet() any {
	return r
}
