

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_PvPSeason

type PvPLeaderboardModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Bracket struct {
		ID   int    `json:"id,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"bracket"`
	Entries []struct {
		Character struct {
			ID    int    `json:"id,omitzero"`
			Name  string `json:"name,omitzero"`
			Realm struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Slug string `json:"slug,omitzero"`
			} `json:"realm"`
		} `json:"character"`
		Faction struct {
			Type string `json:"type,omitzero"`
		} `json:"faction"`
		Rank                  int `json:"rank,omitzero"`
		Rating                int `json:"rating,omitzero"`
		SeasonMatchStatistics struct {
			Lost   int `json:"lost,omitzero"`
			Played int `json:"played,omitzero"`
			Won    int `json:"won,omitzero"`
		} `json:"season_match_statistics"`
		Tier struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
		} `json:"tier"`
	} `json:"entries"`
	Name   string `json:"name,omitzero"`
	Season struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"season"`
}





// PvPLeaderboard represents the raw CN API response for PvPLeaderboard.
type CNPvPLeaderboardModel PvPLeaderboardModel

// ToBNet converts the CN  to the unified BNetPvPLeaderboard.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPLeaderboardModel) ToBNet() any {
	return r
}
