

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_PvPSeason

type PvPRewardsIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Rewards []struct {
		Achievement struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"achievement"`
		Bracket struct {
			ID   int    `json:"id,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"bracket"`
		Faction struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"faction"`
		RatingCutoff int `json:"rating_cutoff,omitzero"`
	} `json:"rewards"`
	Season struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"season"`
}





// PvPRewardsIndex represents the raw CN API response for PvPRewardsIndex.
type CNPvPRewardsIndexModel PvPRewardsIndexModel

// ToBNet converts the CN  to the unified BNetPvPRewardsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPRewardsIndexModel) ToBNet() any {
	return r
}
