package wow_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPvPSeasonsIndexResponse is the unified BNet representation for PvPSeasonsIndex.
type BNetPvPSeasonsIndex struct{}

// PvPSeasonsIndexResponse represents the raw CN API response for PvPSeasonsIndex.
type CNPvPSeasonsIndex BNetPvPSeasonsIndex

// ToBNet converts the CN response to the unified BNetPvPSeasonsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPSeasonsIndex) ToBNet() any {
	return r
}
