package wow_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPvPSeasonResponse is the unified BNet representation for PvPSeason.
type BNetPvPSeason struct{}

// PvPSeasonResponse represents the raw CN API response for PvPSeason.
type CNPvPSeason BNetPvPSeason

// ToBNet converts the CN response to the unified BNetPvPSeasonResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPSeason) ToBNet() any {
	return r
}
