

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_PvPSeason

type PvPSeasonModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ID           int `json:"id,omitzero"`
	Leaderboards struct {
		Href string `json:"href,omitzero"`
	} `json:"leaderboards"`
	Rewards struct {
		Href string `json:"href,omitzero"`
	} `json:"rewards"`
	SeasonEndTimestamp   int `json:"season_end_timestamp,omitzero"`
	SeasonStartTimestamp int `json:"season_start_timestamp,omitzero"`
}





// PvPSeason represents the raw CN API response for PvPSeason.
type CNPvPSeasonModel PvPSeasonModel

// ToBNet converts the CN  to the unified BNetPvPSeason.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPSeasonModel) ToBNet() any {
	return r
}
