package wow_Realm

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetRealmResponse is the unified BNet representation for Realm.
type BNetRealm struct{}

// RealmResponse represents the raw CN API response for Realm.
type CNRealm BNetRealm

// ToBNet converts the CN response to the unified BNetRealmResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNRealm) ToBNet() any {
	return r
}
