package wow_CharacterProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterProfileStatusResponse is the unified BNet representation for CharacterProfileStatus.
type BNetCharacterProfileStatus struct{}

// CharacterProfileStatusResponse represents the raw CN API response for CharacterProfileStatus.
type CNCharacterProfileStatus BNetCharacterProfileStatus

// ToBNet converts the CN response to the unified BNetCharacterProfileStatusResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterProfileStatus) ToBNet() any {
	return r
}
