package wow_CharacterProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterProfileSummaryResponse is the unified BNet representation for CharacterProfileSummary.
type BNetCharacterProfileSummary struct{}

// CharacterProfileSummaryResponse represents the raw CN API response for CharacterProfileSummary.
type CNCharacterProfileSummary BNetCharacterProfileSummary

// ToBNet converts the CN response to the unified BNetCharacterProfileSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterProfileSummary) ToBNet() any {
	return r
}
