// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterProfile

import "github.com/jinzhu/copier"

type CharacterProfileSummaryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	AchievementPoints int `json:"achievement_points,omitzero"`
	Achievements      struct {
		Href string `json:"href,omitzero"`
	} `json:"achievements"`
	AchievementsStatistics struct {
		Href string `json:"href,omitzero"`
	} `json:"achievements_statistics"`
	ActiveSpec struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"active_spec"`
	Appearance struct {
		Href string `json:"href,omitzero"`
	} `json:"appearance"`
	AverageItemLevel int `json:"average_item_level,omitzero"`
	CharacterClass   struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"character_class"`
	Collections struct {
		Href string `json:"href,omitzero"`
	} `json:"collections"`
	CovenantProgress struct {
		ChosenCovenant struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"chosen_covenant"`
		RenownLevel int `json:"renown_level,omitzero"`
		Soulbinds   struct {
			Href string `json:"href,omitzero"`
		} `json:"soulbinds"`
	} `json:"covenant_progress"`
	Encounters struct {
		Href string `json:"href,omitzero"`
	} `json:"encounters"`
	Equipment struct {
		Href string `json:"href,omitzero"`
	} `json:"equipment"`
	EquippedItemLevel int `json:"equipped_item_level,omitzero"`
	Experience        int `json:"experience"`
	Faction           struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"faction"`
	Gender struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"gender"`
	Guild struct {
		Faction struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"faction"`
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name  string `json:"name,omitzero"`
		Realm struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"realm"`
	} `json:"guild"`
	Houses []struct {
		Href string `json:"href,omitzero"`
	} `json:"houses"`
	ID                 int  `json:"id,omitzero"`
	IsRemix            bool `json:"is_remix"`
	LastLoginTimestamp int  `json:"last_login_timestamp,omitzero"`
	Level              int  `json:"level,omitzero"`
	Media              struct {
		Href string `json:"href,omitzero"`
	} `json:"media"`
	MythicKeystoneProfile struct {
		Href string `json:"href,omitzero"`
	} `json:"mythic_keystone_profile"`
	Name        string `json:"name,omitzero"`
	NameSearch  string `json:"name_search,omitzero"`
	Professions struct {
		Href string `json:"href,omitzero"`
	} `json:"professions"`
	PvpSummary struct {
		Href string `json:"href,omitzero"`
	} `json:"pvp_summary"`
	Quests struct {
		Href string `json:"href,omitzero"`
	} `json:"quests"`
	Race struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"race"`
	Realm struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
		Slug string `json:"slug,omitzero"`
	} `json:"realm"`
	Reputations struct {
		Href string `json:"href,omitzero"`
	} `json:"reputations"`
	Specializations struct {
		Href string `json:"href,omitzero"`
	} `json:"specializations"`
	Statistics struct {
		Href string `json:"href,omitzero"`
	} `json:"statistics"`
	Titles struct {
		Href string `json:"href,omitzero"`
	} `json:"titles"`
}

// CharacterProfileSummary represents the raw CN API response for CharacterProfileSummary.
type CNCharacterProfileSummaryModel struct {
	CharacterSummary struct {
		Name   string `json:"name"`
		Gender struct {
			Type string `json:"type"`
			Name string `json:"name"`
		} `json:"gender"`
		Faction struct {
			Type string `json:"type"`
			Name string `json:"name"`
		} `json:"faction"`
		Race struct {
			Name string `json:"name"`
		} `json:"race"`
		CharacterClass struct {
			Id   int    `json:"id"`
			Name string `json:"name"`
		} `json:"character_class"`
		ActiveSpec struct {
			Name string `json:"name"`
		} `json:"active_spec"`
		Realm struct {
			Name string `json:"name"`
			Slug string `json:"slug"`
		} `json:"realm"`
		Guild struct {
			Name  string `json:"name"`
			Realm struct {
				Name string `json:"name"`
				Slug string `json:"slug"`
			} `json:"realm"`
			Faction struct {
				Type string `json:"type"`
				Name string `json:"name"`
			} `json:"faction"`
		} `json:"guild"`
		Level              int   `json:"level"`
		Experience         int   `json:"experience"`
		AchievementPoints  int   `json:"achievement_points"`
		LastLoginTimestamp int64 `json:"last_login_timestamp"`
		AverageItemLevel   int   `json:"average_item_level"`
		EquippedItemLevel  int   `json:"equipped_item_level"`
		ActiveTitle        struct {
			Name          string `json:"name"`
			DisplayString string `json:"display_string"`
		} `json:"active_title"`
		CovenantProgress struct {
			ChosenCovenant struct {
				Name string `json:"name"`
			} `json:"chosen_covenant"`
			RenownLevel int `json:"renown_level"`
			Soulbinds   struct {
			} `json:"soulbinds"`
		} `json:"covenant_progress"`
		NameSearch string `json:"name_search"`
	} `json:"character_summary"`
	List                    []string `json:"list"`
	Token                   string   `json:"token"`
	IsSelf                  bool     `json:"is_self"`
	Allow                   bool     `json:"allow"`
	EncountersJson          string   `json:"encounters_json"`
	AchievementCategoryJson string   `json:"achievement_category_json"`
	CharacterMedia          struct {
		Assets []struct {
			Key   string `json:"key"`
			Value string `json:"value"`
		} `json:"assets"`
	} `json:"character_media"`
}

// ToBNet converts the CN  to the unified BNetCharacterProfileSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterProfileSummaryModel) ToBNet() any {
	b := &CharacterProfileSummaryModel{}
	copier.Copy(b, r.CharacterSummary)
	return b
}
