

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterProfile

type CharacterProfileStatusModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ID      int  `json:"id,omitzero"`
	IsValid bool `json:"is_valid,omitzero"`
}





// CharacterProfileStatus represents the raw CN API response for CharacterProfileStatus.
type CNCharacterProfileStatusModel CharacterProfileStatusModel

// ToBNet converts the CN  to the unified BNetCharacterProfileStatus.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterProfileStatusModel) ToBNet() any {
	return r
}
