package wow_CharacterPvP

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterPvPSummaryResponse is the unified BNet representation for CharacterPvPSummary.
type BNetCharacterPvPSummary struct{}

// CharacterPvPSummaryResponse represents the raw CN API response for CharacterPvPSummary.
type CNCharacterPvPSummary BNetCharacterPvPSummary

// ToBNet converts the CN response to the unified BNetCharacterPvPSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterPvPSummary) ToBNet() any {
	return r
}
