// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterPvP

import "github.com/jinzhu/copier"

type CharacterPvPSummaryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Character struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name  string `json:"name,omitzero"`
		Realm struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"realm"`
	} `json:"character"`
	HonorLevel       int `json:"honor_level,omitzero"`
	HonorableKills   int `json:"honorable_kills,omitzero"`
	PvpMapStatistics []struct {
		MatchStatistics struct {
			Lost   int `json:"lost"`
			Played int `json:"played,omitzero"`
			Won    int `json:"won,omitzero"`
		} `json:"match_statistics"`
		WorldMap struct {
			ID   int    `json:"id,omitzero"`
			Name string `json:"name,omitzero"`
		} `json:"world_map"`
	} `json:"pvp_map_statistics"`
}

// CharacterPvPSummary represents the raw CN API response for CharacterPvPSummary.
type CNCharacterPvPSummaryModel struct {
	Links struct {
		Self struct {
		} `json:"self"`
	} `json:"_links"`
	Brackets  interface{} `json:"brackets"`
	Character struct {
		Id  int `json:"id"`
		Key struct {
		} `json:"key"`
		Name  string `json:"name"`
		Realm struct {
			Id  int `json:"id"`
			Key struct {
			} `json:"key"`
			Name string `json:"name"`
			Slug string `json:"slug"`
		} `json:"realm"`
	} `json:"character"`
	HonorLevel       int `json:"honor_level"`
	HonorableKills   int `json:"honorable_kills"`
	PvpMapStatistics []struct {
		MatchStatistics struct {
			Lost   int `json:"lost"`
			Played int `json:"played"`
			Won    int `json:"won"`
		} `json:"match_statistics"`
		WorldMap struct {
			Id   int    `json:"id"`
			Name string `json:"name"`
		} `json:"world_map"`
	} `json:"pvp_map_statistics"`
	Version string `json:"version"`
}

// ToBNet converts the CN  to the unified BNetCharacterPvPSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterPvPSummaryModel) ToBNet() any {
	b := &CharacterPvPSummaryModel{}
	copier.Copy(b, r)
	return b
}
