package D3_D3

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetEraResponse is the unified BNet representation for Era.
type BNetEra struct{}

// EraResponse represents the raw CN API response for Era.
type CNEra BNetEra

// ToBNet converts the CN response to the unified BNetEraResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNEra) ToBNet() any {
	return r
}
