

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package D3_D3

type EraIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	CurrentEra int `json:"current_era,omitzero"`
	Era        []struct {
		Href string `json:"href,omitzero"`
	} `json:"era"`
	GeneratedBy    string `json:"generated_by,omitzero"`
	LastUpdateTime string `json:"last_update_time,omitzero"`
}





// EraIndex represents the raw CN API response for EraIndex.
type CNEraIndexModel EraIndexModel

// ToBNet converts the CN  to the unified BNetEraIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNEraIndexModel) ToBNet() any {
	return r
}
