

package D3_D3

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// EraLeaderboardModel is the unified BNet representation for EraLeaderboard.
type EraLeaderboardModel struct{}




// EraLeaderboard represents the raw CN API response for EraLeaderboard.
type CNEraLeaderboardModel EraLeaderboardModel

// ToBNet converts the CN  to the unified BNetEraLeaderboard.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNEraLeaderboardModel) ToBNet() any {
	return r
}
