package D3_D3

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetSeasonResponse is the unified BNet representation for Season.
type BNetSeason struct{}

// SeasonResponse represents the raw CN API response for Season.
type CNSeason BNetSeason

// ToBNet converts the CN response to the unified BNetSeasonResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSeason) ToBNet() any {
	return r
}
