

package D3_D3

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// SeasonModel is the unified BNet representation for Season.
type SeasonModel struct{}




// Season represents the raw CN API response for Season.
type CNSeasonModel SeasonModel

// ToBNet converts the CN  to the unified BNetSeason.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSeasonModel) ToBNet() any {
	return r
}
