package D3_D3

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetSeasonIndexResponse is the unified BNet representation for SeasonIndex.
type BNetSeasonIndex struct{}

// SeasonIndexResponse represents the raw CN API response for SeasonIndex.
type CNSeasonIndex BNetSeasonIndex

// ToBNet converts the CN response to the unified BNetSeasonIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSeasonIndex) ToBNet() any {
	return r
}
