package D3_D3

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetSeasonLeaderboardResponse is the unified BNet representation for SeasonLeaderboard.
type BNetSeasonLeaderboard struct{}

// SeasonLeaderboardResponse represents the raw CN API response for SeasonLeaderboard.
type CNSeasonLeaderboard BNetSeasonLeaderboard

// ToBNet converts the CN response to the unified BNetSeasonLeaderboardResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSeasonLeaderboard) ToBNet() any {
	return r
}
