

package D3_D3

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// SeasonLeaderboardModel is the unified BNet representation for SeasonLeaderboard.
type SeasonLeaderboardModel struct{}




// SeasonLeaderboard represents the raw CN API response for SeasonLeaderboard.
type CNSeasonLeaderboardModel SeasonLeaderboardModel

// ToBNet converts the CN  to the unified BNetSeasonLeaderboard.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSeasonLeaderboardModel) ToBNet() any {
	return r
}
