package wow_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCreatureDisplayMediaResponse is the unified BNet representation for CreatureDisplayMedia.
type BNetCreatureDisplayMedia struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Assets []struct {
		Key   string `json:"key"`
		Value string `json:"value"`
	} `json:"assets"`
	Id int `json:"id"`
}

// CreatureDisplayMediaResponse represents the raw CN API response for CreatureDisplayMedia.
type CNCreatureDisplayMedia BNetCreatureDisplayMedia

// ToBNet converts the CN response to the unified BNetCreatureDisplayMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureDisplayMedia) ToBNet() any {
	return r
}
