package wow_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCreatureFamilyMediaResponse is the unified BNet representation for CreatureFamilyMedia.
type BNetCreatureFamilyMedia struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Assets []struct {
		Key        string `json:"key"`
		Value      string `json:"value"`
		FileDataId int    `json:"file_data_id"`
	} `json:"assets"`
	Id int `json:"id"`
}

// CreatureFamilyMediaResponse represents the raw CN API response for CreatureFamilyMedia.
type CNCreatureFamilyMedia BNetCreatureFamilyMedia

// ToBNet converts the CN response to the unified BNetCreatureFamilyMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureFamilyMedia) ToBNet() any {
	return r
}
