package wow_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCreatureSearchResponse is the unified BNet representation for CreatureSearch.
type BNetCreatureSearch struct{}

// CreatureSearchResponse represents the raw CN API response for CreatureSearch.
type CNCreatureSearch BNetCreatureSearch

// ToBNet converts the CN response to the unified BNetCreatureSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureSearch) ToBNet() any {
	return r
}
