

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Creature

type CreatureTypeModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ID   int    `json:"id,omitzero"`
	Name string `json:"name,omitzero"`
}





// CreatureType represents the raw CN API response for CreatureType.
type CNCreatureTypeModel CreatureTypeModel

// ToBNet converts the CN  to the unified BNetCreatureType.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureTypeModel) ToBNet() any {
	return r
}
