

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Creature

type CreatureFamilyModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ID    int `json:"id,omitzero"`
	Media struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	Name           string `json:"name,omitzero"`
	Specialization struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"specialization"`
}





// CreatureFamily represents the raw CN API response for CreatureFamily.
type CNCreatureFamilyModel CreatureFamilyModel

// ToBNet converts the CN  to the unified BNetCreatureFamily.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureFamilyModel) ToBNet() any {
	return r
}
