package wow_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCreatureFamiliesIndexResponse is the unified BNet representation for CreatureFamiliesIndex.
type BNetCreatureFamiliesIndex struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	CreatureFamilies []struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"creature_families"`
}

// CreatureFamiliesIndexResponse represents the raw CN API response for CreatureFamiliesIndex.
type CNCreatureFamiliesIndex BNetCreatureFamiliesIndex

// ToBNet converts the CN response to the unified BNetCreatureFamiliesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureFamiliesIndex) ToBNet() any {
	return r
}
