package wow_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCreatureTypeResponse is the unified BNet representation for CreatureType.
type BNetCreatureType struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// CreatureTypeResponse represents the raw CN API response for CreatureType.
type CNCreatureType BNetCreatureType

// ToBNet converts the CN response to the unified BNetCreatureTypeResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureType) ToBNet() any {
	return r
}
