package wow_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCreatureResponse is the unified BNet representation for Creature.
type BNetCreature struct{}

// CreatureResponse represents the raw CN API response for Creature.
type CNCreature BNetCreature

// ToBNet converts the CN response to the unified BNetCreatureResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreature) ToBNet() any {
	return r
}
