package wow_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCreatureFamilyResponse is the unified BNet representation for CreatureFamily.
type BNetCreatureFamily struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Id             int    `json:"id"`
	Name           string `json:"name"`
	Specialization struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"specialization"`
	Media struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Id int `json:"id"`
	} `json:"media"`
}

// CreatureFamilyResponse represents the raw CN API response for CreatureFamily.
type CNCreatureFamily BNetCreatureFamily

// ToBNet converts the CN response to the unified BNetCreatureFamilyResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureFamily) ToBNet() any {
	return r
}
