package wow_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCreatureFamilyResponse is the unified BNet representation for CreatureFamily.
type BNetCreatureFamily struct{}

// CreatureFamilyResponse represents the raw CN API response for CreatureFamily.
type CNCreatureFamily BNetCreatureFamily

// ToBNet converts the CN response to the unified BNetCreatureFamilyResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureFamily) ToBNet() any {
	return r
}
