

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:31:45+08:00
package wow_Creature

type CreatureModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	CreatureDisplays []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"creature_displays"`
	Family struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"family"`
	ID         int    `json:"id,omitzero"`
	IsTameable bool   `json:"is_tameable,omitzero"`
	Name       string `json:"name,omitzero"`
	Type       struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"type"`
}





// Creature represents the raw CN API response for Creature.
type CNCreatureModel CreatureModel

// ToBNet converts the CN  to the unified BNetCreature.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureModel) ToBNet() any {
	return r
}
