package wow_Achievement

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAchievementCategoryResponse is the unified BNet representation for AchievementCategory.
type BNetAchievementCategory struct{}

// AchievementCategoryResponse represents the raw CN API response for AchievementCategory.
type CNAchievementCategory BNetAchievementCategory

// ToBNet converts the CN response to the unified BNetAchievementCategoryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAchievementCategory) ToBNet() any {
	return r
}
