

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:31:45+08:00
package wow_Achievement

type AchievementModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Category struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"category"`
	Criteria struct {
		Amount      int    `json:"amount"`
		Description string `json:"description,omitzero"`
		ID          int    `json:"id,omitzero"`
	} `json:"criteria"`
	Description   string `json:"description,omitzero"`
	DisplayOrder  int    `json:"display_order,omitzero"`
	ID            int    `json:"id,omitzero"`
	IsAccountWide bool   `json:"is_account_wide"`
	Media         struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	Name            string `json:"name,omitzero"`
	NextAchievement struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"next_achievement"`
	Points int `json:"points,omitzero"`
}





// Achievement represents the raw CN API response for Achievement.
type CNAchievementModel AchievementModel

// ToBNet converts the CN  to the unified BNetAchievement.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAchievementModel) ToBNet() any {
	return r
}
