package wow_Achievement

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAchievementCategoriesIndexResponse is the unified BNet representation for AchievementCategoriesIndex.
type BNetAchievementCategoriesIndex struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Categories []struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"categories"`
	RootCategories []struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"root_categories"`
	GuildCategories []struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"guild_categories"`
}

// AchievementCategoriesIndexResponse represents the raw CN API response for AchievementCategoriesIndex.
type CNAchievementCategoriesIndex BNetAchievementCategoriesIndex

// ToBNet converts the CN response to the unified BNetAchievementCategoriesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAchievementCategoriesIndex) ToBNet() any {
	return r
}
