package wow_Achievement

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAchievementCategoriesIndexResponse is the unified BNet representation for AchievementCategoriesIndex.
type BNetAchievementCategoriesIndex struct{}

// AchievementCategoriesIndexResponse represents the raw CN API response for AchievementCategoriesIndex.
type CNAchievementCategoriesIndex BNetAchievementCategoriesIndex

// ToBNet converts the CN response to the unified BNetAchievementCategoriesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAchievementCategoriesIndex) ToBNet() any {
	return r
}
