package wow_Achievement

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAchievementMediaResponse is the unified BNet representation for AchievementMedia.
type BNetAchievementMedia struct{}

// AchievementMediaResponse represents the raw CN API response for AchievementMedia.
type CNAchievementMedia BNetAchievementMedia

// ToBNet converts the CN response to the unified BNetAchievementMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAchievementMedia) ToBNet() any {
	return r
}
