

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:31:45+08:00
package wow_Achievement

type AchievementCategoriesIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Categories []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"categories"`
	GuildCategories []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"guild_categories"`
	RootCategories []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"root_categories"`
}





// AchievementCategoriesIndex represents the raw CN API response for AchievementCategoriesIndex.
type CNAchievementCategoriesIndexModel AchievementCategoriesIndexModel

// ToBNet converts the CN  to the unified BNetAchievementCategoriesIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAchievementCategoriesIndexModel) ToBNet() any {
	return r
}
