

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:31:45+08:00
package wow_Achievement

type AchievementCategoryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Achievements []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"achievements"`
	AggregatesByFaction struct {
		Alliance struct {
			Points   int `json:"points"`
			Quantity int `json:"quantity,omitzero"`
		} `json:"alliance"`
		Horde struct {
			Points   int `json:"points"`
			Quantity int `json:"quantity,omitzero"`
		} `json:"horde"`
	} `json:"aggregates_by_faction"`
	DisplayOrder    int    `json:"display_order,omitzero"`
	ID              int    `json:"id,omitzero"`
	IsGuildCategory bool   `json:"is_guild_category"`
	Name            string `json:"name,omitzero"`
	Subcategories   []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"subcategories"`
}





// AchievementCategory represents the raw CN API response for AchievementCategory.
type CNAchievementCategoryModel AchievementCategoryModel

// ToBNet converts the CN  to the unified BNetAchievementCategory.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAchievementCategoryModel) ToBNet() any {
	return r
}
