package wow_Achievement

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAchievementsIndexResponse is the unified BNet representation for AchievementsIndex.
type BNetAchievementsIndex struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Achievements []struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"achievements"`
}

// AchievementsIndexResponse represents the raw CN API response for AchievementsIndex.
type CNAchievementsIndex BNetAchievementsIndex

// ToBNet converts the CN response to the unified BNetAchievementsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAchievementsIndex) ToBNet() any {
	return r
}
