package wow_ItemAppearance

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetItemAppearanceResponse is the unified BNet representation for ItemAppearance.
type BNetItemAppearance struct{}

// ItemAppearanceResponse represents the raw CN API response for ItemAppearance.
type CNItemAppearance BNetItemAppearance

// ToBNet converts the CN response to the unified BNetItemAppearanceResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemAppearance) ToBNet() any {
	return r
}
