

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_ItemAppearance

type ItemAppearanceSearchModel struct {
	MaxPageSize int   `json:"maxPageSize,omitzero"`
	Page        int   `json:"page,omitzero"`
	PageCount   int   `json:"pageCount"`
	PageSize    int   `json:"pageSize"`
	Results     []any `json:"results"`
}





// ItemAppearanceSearch represents the raw CN API response for ItemAppearanceSearch.
type CNItemAppearanceSearchModel ItemAppearanceSearchModel

// ToBNet converts the CN  to the unified BNetItemAppearanceSearch.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemAppearanceSearchModel) ToBNet() any {
	return r
}
