

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_ItemAppearance

type ItemAppearanceSetModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Appearances []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"appearances"`
	ID      int    `json:"id,omitzero"`
	SetName string `json:"set_name,omitzero"`
}





// ItemAppearanceSet represents the raw CN API response for ItemAppearanceSet.
type CNItemAppearanceSetModel ItemAppearanceSetModel

// ToBNet converts the CN  to the unified BNetItemAppearanceSet.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemAppearanceSetModel) ToBNet() any {
	return r
}
