package wow_ItemAppearance

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetItemAppearanceSetResponse is the unified BNet representation for ItemAppearanceSet.
type BNetItemAppearanceSet struct{}

// ItemAppearanceSetResponse represents the raw CN API response for ItemAppearanceSet.
type CNItemAppearanceSet BNetItemAppearanceSet

// ToBNet converts the CN response to the unified BNetItemAppearanceSetResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemAppearanceSet) ToBNet() any {
	return r
}
