package wow_ItemAppearance

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetItemAppearanceSlotIndexResponse is the unified BNet representation for ItemAppearanceSlotIndex.
type BNetItemAppearanceSlotIndex struct{}

// ItemAppearanceSlotIndexResponse represents the raw CN API response for ItemAppearanceSlotIndex.
type CNItemAppearanceSlotIndex BNetItemAppearanceSlotIndex

// ToBNet converts the CN response to the unified BNetItemAppearanceSlotIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemAppearanceSlotIndex) ToBNet() any {
	return r
}
