

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_ItemAppearance

type ItemAppearanceSlotIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Slots []struct {
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"slots"`
}





// ItemAppearanceSlotIndex represents the raw CN API response for ItemAppearanceSlotIndex.
type CNItemAppearanceSlotIndexModel ItemAppearanceSlotIndexModel

// ToBNet converts the CN  to the unified BNetItemAppearanceSlotIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemAppearanceSlotIndexModel) ToBNet() any {
	return r
}
