package wow_ItemAppearance

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetItemAppearanceSetsIndexResponse is the unified BNet representation for ItemAppearanceSetsIndex.
type BNetItemAppearanceSetsIndex struct{}

// ItemAppearanceSetsIndexResponse represents the raw CN API response for ItemAppearanceSetsIndex.
type CNItemAppearanceSetsIndex BNetItemAppearanceSetsIndex

// ToBNet converts the CN response to the unified BNetItemAppearanceSetsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemAppearanceSetsIndex) ToBNet() any {
	return r
}
