package wow_ModifiedCrafting

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetModifiedCraftingReagentSlotTypeIndexResponse is the unified BNet representation for ModifiedCraftingReagentSlotTypeIndex.
type BNetModifiedCraftingReagentSlotTypeIndex struct{}

// ModifiedCraftingReagentSlotTypeIndexResponse represents the raw CN API response for ModifiedCraftingReagentSlotTypeIndex.
type CNModifiedCraftingReagentSlotTypeIndex BNetModifiedCraftingReagentSlotTypeIndex

// ToBNet converts the CN response to the unified BNetModifiedCraftingReagentSlotTypeIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNModifiedCraftingReagentSlotTypeIndex) ToBNet() any {
	return r
}
