package wow_ModifiedCrafting

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetModifiedCraftingCategoryIndexResponse is the unified BNet representation for ModifiedCraftingCategoryIndex.
type BNetModifiedCraftingCategoryIndex struct{}

// ModifiedCraftingCategoryIndexResponse represents the raw CN API response for ModifiedCraftingCategoryIndex.
type CNModifiedCraftingCategoryIndex BNetModifiedCraftingCategoryIndex

// ToBNet converts the CN response to the unified BNetModifiedCraftingCategoryIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNModifiedCraftingCategoryIndex) ToBNet() any {
	return r
}
