

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_ModifiedCrafting

type ModifiedCraftingIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Categories struct {
		Href string `json:"href,omitzero"`
	} `json:"categories"`
	SlotTypes struct {
		Href string `json:"href,omitzero"`
	} `json:"slot_types"`
}





// ModifiedCraftingIndex represents the raw CN API response for ModifiedCraftingIndex.
type CNModifiedCraftingIndexModel ModifiedCraftingIndexModel

// ToBNet converts the CN  to the unified BNetModifiedCraftingIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNModifiedCraftingIndexModel) ToBNet() any {
	return r
}
