

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_ModifiedCrafting

type ModifiedCraftingCategoryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ID   int    `json:"id,omitzero"`
	Name string `json:"name,omitzero"`
}





// ModifiedCraftingCategory represents the raw CN API response for ModifiedCraftingCategory.
type CNModifiedCraftingCategoryModel ModifiedCraftingCategoryModel

// ToBNet converts the CN  to the unified BNetModifiedCraftingCategory.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNModifiedCraftingCategoryModel) ToBNet() any {
	return r
}
