

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_ModifiedCrafting

type ModifiedCraftingReagentSlotTypeModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	CompatibleCategories []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"compatible_categories"`
	Description string `json:"description,omitzero"`
	ID          int    `json:"id,omitzero"`
}





// ModifiedCraftingReagentSlotType represents the raw CN API response for ModifiedCraftingReagentSlotType.
type CNModifiedCraftingReagentSlotTypeModel ModifiedCraftingReagentSlotTypeModel

// ToBNet converts the CN  to the unified BNetModifiedCraftingReagentSlotType.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNModifiedCraftingReagentSlotTypeModel) ToBNet() any {
	return r
}
