package wow_ModifiedCrafting

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetModifiedCraftingIndexResponse is the unified BNet representation for ModifiedCraftingIndex.
type BNetModifiedCraftingIndex struct{}

// ModifiedCraftingIndexResponse represents the raw CN API response for ModifiedCraftingIndex.
type CNModifiedCraftingIndex BNetModifiedCraftingIndex

// ToBNet converts the CN response to the unified BNetModifiedCraftingIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNModifiedCraftingIndex) ToBNet() any {
	return r
}
