package wow_ModifiedCrafting

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetModifiedCraftingReagentSlotTypeResponse is the unified BNet representation for ModifiedCraftingReagentSlotType.
type BNetModifiedCraftingReagentSlotType struct{}

// ModifiedCraftingReagentSlotTypeResponse represents the raw CN API response for ModifiedCraftingReagentSlotType.
type CNModifiedCraftingReagentSlotType BNetModifiedCraftingReagentSlotType

// ToBNet converts the CN response to the unified BNetModifiedCraftingReagentSlotTypeResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNModifiedCraftingReagentSlotType) ToBNet() any {
	return r
}
