

package wowClassic_CharacterStatistics

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CharacterStatisticsSummaryModel is the unified BNet representation for CharacterStatisticsSummary.
type CharacterStatisticsSummaryModel struct{}




// CharacterStatisticsSummary represents the raw CN API response for CharacterStatisticsSummary.
type CNCharacterStatisticsSummaryModel CharacterStatisticsSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterStatisticsSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterStatisticsSummaryModel) ToBNet() any {
	return r
}
