package wow_Mount

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMountResponse is the unified BNet representation for Mount.
type BNetMount struct{}

// MountResponse represents the raw CN API response for Mount.
type CNMount BNetMount

// ToBNet converts the CN response to the unified BNetMountResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMount) ToBNet() any {
	return r
}
