package wow_Mount

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMountSearchResponse is the unified BNet representation for MountSearch.
type BNetMountSearch struct{}

// MountSearchResponse represents the raw CN API response for MountSearch.
type CNMountSearch BNetMountSearch

// ToBNet converts the CN response to the unified BNetMountSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMountSearch) ToBNet() any {
	return r
}
