

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Mount

type MountModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	CreatureDisplays []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"creature_displays"`
	Description string `json:"description,omitzero"`
	Faction     struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"faction"`
	ID           int    `json:"id,omitzero"`
	Name         string `json:"name,omitzero"`
	Requirements struct {
		Faction struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"faction"`
	} `json:"requirements"`
	Source struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"source"`
}





// Mount represents the raw CN API response for Mount.
type CNMountModel MountModel

// ToBNet converts the CN  to the unified BNetMount.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMountModel) ToBNet() any {
	return r
}
