

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Mount

type MountsIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Mounts []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"mounts"`
}





// MountsIndex represents the raw CN API response for MountsIndex.
type CNMountsIndexModel MountsIndexModel

// ToBNet converts the CN  to the unified BNetMountsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMountsIndexModel) ToBNet() any {
	return r
}
