package wow_Mount

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMountsIndexResponse is the unified BNet representation for MountsIndex.
type BNetMountsIndex struct{}

// MountsIndexResponse represents the raw CN API response for MountsIndex.
type CNMountsIndex BNetMountsIndex

// ToBNet converts the CN response to the unified BNetMountsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMountsIndex) ToBNet() any {
	return r
}
