

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterAppearance

type CharacterAppearanceSummaryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ActiveSpec struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"active_spec"`
	Character struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name  string `json:"name,omitzero"`
		Realm struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"realm"`
	} `json:"character"`
	Customizations []struct {
		Choice struct {
			DisplayOrder int    `json:"display_order"`
			ID           int    `json:"id,omitzero"`
			Name         string `json:"name,omitempty,omitzero"`
		} `json:"choice"`
		Option struct {
			ID   int    `json:"id,omitzero"`
			Name string `json:"name,omitzero"`
		} `json:"option"`
	} `json:"customizations"`
	Faction struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"faction"`
	Gender struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"gender"`
	Items []struct {
		Enchant                  int `json:"enchant"`
		ID                       int `json:"id,omitzero"`
		InternalSlotID           int `json:"internal_slot_id"`
		ItemAppearanceModifierID int `json:"item_appearance_modifier_id"`
		Slot                     struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"slot"`
		Subclass int `json:"subclass,omitzero"`
	} `json:"items"`
	PlayableClass struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"playable_class"`
	PlayableRace struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"playable_race"`
}





// CharacterAppearanceSummary represents the raw CN API response for CharacterAppearanceSummary.
type CNCharacterAppearanceSummaryModel CharacterAppearanceSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterAppearanceSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterAppearanceSummaryModel) ToBNet() any {
	return r
}
