package wow_AzeriteEssence

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAzeriteEssenceSearchResponse is the unified BNet representation for AzeriteEssenceSearch.
type BNetAzeriteEssenceSearch struct{}

// AzeriteEssenceSearchResponse represents the raw CN API response for AzeriteEssenceSearch.
type CNAzeriteEssenceSearch BNetAzeriteEssenceSearch

// ToBNet converts the CN response to the unified BNetAzeriteEssenceSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAzeriteEssenceSearch) ToBNet() any {
	return r
}
