

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:31:45+08:00
package wow_AzeriteEssence

type AzeriteEssenceSearchModel struct {
	MaxPageSize int   `json:"maxPageSize,omitzero"`
	Page        int   `json:"page,omitzero"`
	PageCount   int   `json:"pageCount"`
	PageSize    int   `json:"pageSize"`
	Results     []any `json:"results"`
}





// AzeriteEssenceSearch represents the raw CN API response for AzeriteEssenceSearch.
type CNAzeriteEssenceSearchModel AzeriteEssenceSearchModel

// ToBNet converts the CN  to the unified BNetAzeriteEssenceSearch.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAzeriteEssenceSearchModel) ToBNet() any {
	return r
}
