package wow_AzeriteEssence

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAzeriteEssenceResponse is the unified BNet representation for AzeriteEssence.
type BNetAzeriteEssence struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Id                     int    `json:"id"`
	Name                   string `json:"name"`
	AllowedSpecializations []struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"allowed_specializations"`
	Powers []struct {
		Id             int `json:"id"`
		Rank           int `json:"rank"`
		MainPowerSpell struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Id   int    `json:"id"`
		} `json:"main_power_spell"`
		PassivePowerSpell struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Id   int    `json:"id"`
		} `json:"passive_power_spell"`
	} `json:"powers"`
	Media struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Id int `json:"id"`
	} `json:"media"`
}

// AzeriteEssenceResponse represents the raw CN API response for AzeriteEssence.
type CNAzeriteEssence BNetAzeriteEssence

// ToBNet converts the CN response to the unified BNetAzeriteEssenceResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAzeriteEssence) ToBNet() any {
	return r
}
