package wow_AzeriteEssence

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAzeriteEssencesIndexResponse is the unified BNet representation for AzeriteEssencesIndex.
type BNetAzeriteEssencesIndex struct{}

// AzeriteEssencesIndexResponse represents the raw CN API response for AzeriteEssencesIndex.
type CNAzeriteEssencesIndex BNetAzeriteEssencesIndex

// ToBNet converts the CN response to the unified BNetAzeriteEssencesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAzeriteEssencesIndex) ToBNet() any {
	return r
}
