package wow_AzeriteEssence

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAzeriteEssenceResponse is the unified BNet representation for AzeriteEssence.
type BNetAzeriteEssence struct{}

// AzeriteEssenceResponse represents the raw CN API response for AzeriteEssence.
type CNAzeriteEssence BNetAzeriteEssence

// ToBNet converts the CN response to the unified BNetAzeriteEssenceResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAzeriteEssence) ToBNet() any {
	return r
}
