

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:31:45+08:00
package wow_AzeriteEssence

type AzeriteEssenceMediaModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Assets []struct {
		FileDataID int    `json:"file_data_id,omitzero"`
		Key        string `json:"key,omitzero"`
		Value      string `json:"value,omitzero"`
	} `json:"assets"`
	ID int `json:"id,omitzero"`
}





// AzeriteEssenceMedia represents the raw CN API response for AzeriteEssenceMedia.
type CNAzeriteEssenceMediaModel AzeriteEssenceMediaModel

// ToBNet converts the CN  to the unified BNetAzeriteEssenceMedia.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAzeriteEssenceMediaModel) ToBNet() any {
	return r
}
