package wow_AzeriteEssence

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAzeriteEssenceMediaResponse is the unified BNet representation for AzeriteEssenceMedia.
type BNetAzeriteEssenceMedia struct{}

// AzeriteEssenceMediaResponse represents the raw CN API response for AzeriteEssenceMedia.
type CNAzeriteEssenceMedia BNetAzeriteEssenceMedia

// ToBNet converts the CN response to the unified BNetAzeriteEssenceMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAzeriteEssenceMedia) ToBNet() any {
	return r
}
