

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:31:45+08:00
package wow_AzeriteEssence

type AzeriteEssencesIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	AzeriteEssences []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"azerite_essences"`
}





// AzeriteEssencesIndex represents the raw CN API response for AzeriteEssencesIndex.
type CNAzeriteEssencesIndexModel AzeriteEssencesIndexModel

// ToBNet converts the CN  to the unified BNetAzeriteEssencesIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAzeriteEssencesIndexModel) ToBNet() any {
	return r
}
