

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterQuests

type CharacterCompletedQuestsModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Character struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name  string `json:"name,omitzero"`
		Realm struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"realm"`
	} `json:"character"`
	Quests []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"quests"`
}





// CharacterCompletedQuests represents the raw CN API response for CharacterCompletedQuests.
type CNCharacterCompletedQuestsModel CharacterCompletedQuestsModel

// ToBNet converts the CN  to the unified BNetCharacterCompletedQuests.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterCompletedQuestsModel) ToBNet() any {
	return r
}
