package wow_CharacterQuests

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterCompletedQuestsResponse is the unified BNet representation for CharacterCompletedQuests.
type BNetCharacterCompletedQuests struct{}

// CharacterCompletedQuestsResponse represents the raw CN API response for CharacterCompletedQuests.
type CNCharacterCompletedQuests BNetCharacterCompletedQuests

// ToBNet converts the CN response to the unified BNetCharacterCompletedQuestsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterCompletedQuests) ToBNet() any {
	return r
}
