package wow_AuctionHouse

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAuctionsResponse is the unified BNet representation for Auctions.
type BNetAuctions struct{}

// AuctionsResponse represents the raw CN API response for Auctions.
type CNAuctions BNetAuctions

// ToBNet converts the CN response to the unified BNetAuctionsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAuctions) ToBNet() any {
	return r
}
