package wow_AuctionHouse

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAuctionsResponse is the unified BNet representation for Auctions.
type Auction struct {
	Id   int `json:"id"`
	Item struct {
		Id         int   `json:"id"`
		Context    int   `json:"context"`
		BonusLists []int `json:"bonus_lists"`
		Modifiers  []struct {
			Type  int `json:"type"`
			Value int `json:"value"`
		} `json:"modifiers"`
	} `json:"item"`
	Buyout   int    `json:"buyout"`
	Quantity int    `json:"quantity"`
	TimeLeft string `json:"time_left"`
}
type BNetAuctions struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	ConnectedRealm struct {
		Href string `json:"href"`
	} `json:"connected_realm"`
	Auctions    []Auction `json:"auctions"`
	Commodities struct {
		Href string `json:"href"`
	} `json:"commodities"`
}

// AuctionsResponse represents the raw CN API response for Auctions.
type CNAuctions BNetAuctions

// ToBNet converts the CN response to the unified BNetAuctionsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAuctions) ToBNet() any {
	return r
}
