package wowClassic_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPvPLeaderboardsIndexResponse is the unified BNet representation for PvPLeaderboardsIndex.
type BNetPvPLeaderboardsIndex struct{}

// PvPLeaderboardsIndexResponse represents the raw CN API response for PvPLeaderboardsIndex.
type CNPvPLeaderboardsIndex BNetPvPLeaderboardsIndex

// ToBNet converts the CN response to the unified BNetPvPLeaderboardsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPLeaderboardsIndex) ToBNet() any {
	return r
}
