

package wowClassic_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PvPLeaderboardsIndexModel is the unified BNet representation for PvPLeaderboardsIndex.
type PvPLeaderboardsIndexModel struct{}




// PvPLeaderboardsIndex represents the raw CN API response for PvPLeaderboardsIndex.
type CNPvPLeaderboardsIndexModel PvPLeaderboardsIndexModel

// ToBNet converts the CN  to the unified BNetPvPLeaderboardsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPLeaderboardsIndexModel) ToBNet() any {
	return r
}
