

package wowClassic_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PvPLeaderboardModel is the unified BNet representation for PvPLeaderboard.
type PvPLeaderboardModel struct{}




// PvPLeaderboard represents the raw CN API response for PvPLeaderboard.
type CNPvPLeaderboardModel PvPLeaderboardModel

// ToBNet converts the CN  to the unified BNetPvPLeaderboard.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPLeaderboardModel) ToBNet() any {
	return r
}
