package wowClassic_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPvPRegionIndexResponse is the unified BNet representation for PvPRegionIndex.
type BNetPvPRegionIndex struct{}

// PvPRegionIndexResponse represents the raw CN API response for PvPRegionIndex.
type CNPvPRegionIndex BNetPvPRegionIndex

// ToBNet converts the CN response to the unified BNetPvPRegionIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPRegionIndex) ToBNet() any {
	return r
}
