

package wowClassic_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PvPRewardsIndexModel is the unified BNet representation for PvPRewardsIndex.
type PvPRewardsIndexModel struct{}




// PvPRewardsIndex represents the raw CN API response for PvPRewardsIndex.
type CNPvPRewardsIndexModel PvPRewardsIndexModel

// ToBNet converts the CN  to the unified BNetPvPRewardsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPRewardsIndexModel) ToBNet() any {
	return r
}
