

package wowClassic_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PvPRegionIndexModel is the unified BNet representation for PvPRegionIndex.
type PvPRegionIndexModel struct{}




// PvPRegionIndex represents the raw CN API response for PvPRegionIndex.
type CNPvPRegionIndexModel PvPRegionIndexModel

// ToBNet converts the CN  to the unified BNetPvPRegionIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPRegionIndexModel) ToBNet() any {
	return r
}
