package wowClassic_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPvPRegionalSeasonResponse is the unified BNet representation for PvPRegionalSeason.
type BNetPvPRegionalSeason struct{}

// PvPRegionalSeasonResponse represents the raw CN API response for PvPRegionalSeason.
type CNPvPRegionalSeason BNetPvPRegionalSeason

// ToBNet converts the CN response to the unified BNetPvPRegionalSeasonResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPRegionalSeason) ToBNet() any {
	return r
}
