package wowClassic_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPvPRewardsIndexResponse is the unified BNet representation for PvPRewardsIndex.
type BNetPvPRewardsIndex struct{}

// PvPRewardsIndexResponse represents the raw CN API response for PvPRewardsIndex.
type CNPvPRewardsIndex BNetPvPRewardsIndex

// ToBNet converts the CN response to the unified BNetPvPRewardsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPRewardsIndex) ToBNet() any {
	return r
}
