

package wowClassic_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PvPRegionalSeasonModel is the unified BNet representation for PvPRegionalSeason.
type PvPRegionalSeasonModel struct{}




// PvPRegionalSeason represents the raw CN API response for PvPRegionalSeason.
type CNPvPRegionalSeasonModel PvPRegionalSeasonModel

// ToBNet converts the CN  to the unified BNetPvPRegionalSeason.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPRegionalSeasonModel) ToBNet() any {
	return r
}
