

package wowClassic_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PvPRegionalSeasonIndexModel is the unified BNet representation for PvPRegionalSeasonIndex.
type PvPRegionalSeasonIndexModel struct{}




// PvPRegionalSeasonIndex represents the raw CN API response for PvPRegionalSeasonIndex.
type CNPvPRegionalSeasonIndexModel PvPRegionalSeasonIndexModel

// ToBNet converts the CN  to the unified BNetPvPRegionalSeasonIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPRegionalSeasonIndexModel) ToBNet() any {
	return r
}
