

package wowClassic_PvPSeason

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PvPSeasonModel is the unified BNet representation for PvPSeason.
type PvPSeasonModel struct{}




// PvPSeason represents the raw CN API response for PvPSeason.
type CNPvPSeasonModel PvPSeasonModel

// ToBNet converts the CN  to the unified BNetPvPSeason.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPSeasonModel) ToBNet() any {
	return r
}
