

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wowClassic_PvPSeason

type PvPSeasonsIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	CurrentSeason struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"current_season"`
	Seasons []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"seasons"`
}





// PvPSeasonsIndex represents the raw CN API response for PvPSeasonsIndex.
type CNPvPSeasonsIndexModel PvPSeasonsIndexModel

// ToBNet converts the CN  to the unified BNetPvPSeasonsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPSeasonsIndexModel) ToBNet() any {
	return r
}
