

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package HeartStone_CardBacks

type CardBackSearchModel struct {
	CardBacks []struct {
		ID    int    `json:"id"`
		Image string `json:"image,omitzero"`
		Name  struct {
			DeDe string `json:"de_DE,omitzero"`
			EnUs string `json:"en_US,omitzero"`
			EsEs string `json:"es_ES,omitzero"`
			EsMx string `json:"es_MX,omitzero"`
			FrFr string `json:"fr_FR,omitzero"`
			ItIt string `json:"it_IT,omitzero"`
			JaJp string `json:"ja_JP,omitzero"`
			KoKr string `json:"ko_KR,omitzero"`
			PlPl string `json:"pl_PL,omitzero"`
			PtBr string `json:"pt_BR,omitzero"`
			RuRu string `json:"ru_RU,omitzero"`
			ThTh string `json:"th_TH,omitzero"`
			ZhCn string `json:"zh_CN,omitzero"`
			ZhTw string `json:"zh_TW,omitzero"`
		} `json:"name"`
		Slug         string `json:"slug,omitzero"`
		SortCategory int    `json:"sortCategory,omitzero"`
		Text         struct {
			DeDe string `json:"de_DE,omitzero"`
			EnUs string `json:"en_US,omitzero"`
			EsEs string `json:"es_ES,omitzero"`
			EsMx string `json:"es_MX,omitzero"`
			FrFr string `json:"fr_FR,omitzero"`
			ItIt string `json:"it_IT,omitzero"`
			JaJp string `json:"ja_JP,omitzero"`
			KoKr string `json:"ko_KR,omitzero"`
			PlPl string `json:"pl_PL,omitzero"`
			PtBr string `json:"pt_BR,omitzero"`
			RuRu string `json:"ru_RU,omitzero"`
			ThTh string `json:"th_TH,omitzero"`
			ZhCn string `json:"zh_CN,omitzero"`
			ZhTw string `json:"zh_TW,omitzero"`
		} `json:"text"`
	} `json:"cardBacks"`
	CardCount int `json:"cardCount,omitzero"`
	Page      int `json:"page,omitzero"`
	PageCount int `json:"pageCount,omitzero"`
}





// CardBackSearch represents the raw CN API response for CardBackSearch.
type CNCardBackSearchModel CardBackSearchModel

// ToBNet converts the CN  to the unified BNetCardBackSearch.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCardBackSearchModel) ToBNet() any {
	return r
}
