

package HeartStone_CardBacks

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// FetchonecardbackModel is the unified BNet representation for Fetchonecardback.
type FetchonecardbackModel struct{}




// Fetchonecardback represents the raw CN API response for Fetchonecardback.
type CNFetchonecardbackModel FetchonecardbackModel

// ToBNet converts the CN  to the unified BNetFetchonecardback.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNFetchonecardbackModel) ToBNet() any {
	return r
}
