package HeartStone_CardBacks

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetFetchonecardbackResponse is the unified BNet representation for Fetchonecardback.
type BNetFetchonecardback struct{}

// FetchonecardbackResponse represents the raw CN API response for Fetchonecardback.
type CNFetchonecardback BNetFetchonecardback

// ToBNet converts the CN response to the unified BNetFetchonecardbackResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNFetchonecardback) ToBNet() any {
	return r
}
