package wow_CharacterEncounters

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterRaidsResponse is the unified BNet representation for CharacterRaids.
type BNetCharacterRaids struct{}

// CharacterRaidsResponse represents the raw CN API response for CharacterRaids.
type CNCharacterRaids BNetCharacterRaids

// ToBNet converts the CN response to the unified BNetCharacterRaidsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterRaids) ToBNet() any {
	return r
}
