

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterEncounters

type CharacterRaidsModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Character struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name  string `json:"name,omitzero"`
		Realm struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"realm"`
	} `json:"character"`
	Expansions []struct {
		Expansion struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"expansion"`
		Instances []struct {
			Instance struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"instance"`
			Modes []struct {
				Difficulty struct {
					Name string `json:"name,omitzero"`
					Type string `json:"type,omitzero"`
				} `json:"difficulty"`
				Progress struct {
					CompletedCount int `json:"completed_count,omitzero"`
					Encounters     []struct {
						CompletedCount int `json:"completed_count,omitzero"`
						Encounter      struct {
							ID  int `json:"id,omitzero"`
							Key struct {
								Href string `json:"href,omitzero"`
							} `json:"key"`
							Name string `json:"name,omitzero"`
						} `json:"encounter"`
						LastKillTimestamp int `json:"last_kill_timestamp,omitzero"`
					} `json:"encounters"`
					TotalCount int `json:"total_count,omitzero"`
				} `json:"progress"`
				Status struct {
					Name string `json:"name,omitzero"`
					Type string `json:"type,omitzero"`
				} `json:"status"`
			} `json:"modes"`
		} `json:"instances"`
	} `json:"expansions"`
}





// CharacterRaids represents the raw CN API response for CharacterRaids.
type CNCharacterRaidsModel CharacterRaidsModel

// ToBNet converts the CN  to the unified BNetCharacterRaids.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterRaidsModel) ToBNet() any {
	return r
}
