package wow_CharacterEncounters

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterEncountersSummaryResponse is the unified BNet representation for CharacterEncountersSummary.
type BNetCharacterEncountersSummary struct{}

// CharacterEncountersSummaryResponse represents the raw CN API response for CharacterEncountersSummary.
type CNCharacterEncountersSummary BNetCharacterEncountersSummary

// ToBNet converts the CN response to the unified BNetCharacterEncountersSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterEncountersSummary) ToBNet() any {
	return r
}
