package wow_CharacterEncounters

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterDungeonsResponse is the unified BNet representation for CharacterDungeons.
type BNetCharacterDungeons struct{}

// CharacterDungeonsResponse represents the raw CN API response for CharacterDungeons.
type CNCharacterDungeons BNetCharacterDungeons

// ToBNet converts the CN response to the unified BNetCharacterDungeonsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterDungeons) ToBNet() any {
	return r
}
