package automodel

import (
	"io"
	"time"

	"github.com/twpayne/go-jsonstruct/v3"
)

var options = []jsonstruct.GeneratorOption{
	jsonstruct.WithFileHeader(""),
	jsonstruct.WithOmitEmptyTags(jsonstruct.OmitEmptyTagsAuto),
	jsonstruct.WithOmitZeroTags(jsonstruct.OmitZeroTagsAuto),
	jsonstruct.WithSkipUnparsableProperties(true),
	jsonstruct.WithStringTags(false),
	jsonstruct.WithUseJSONNumber(false),
	jsonstruct.WithGoFormat(true),
	jsonstruct.WithPackageComment("// AUTOMATICALLY GENERATED FILE, DO NOT EDIT\n" +
		"// This file is generated by tools/updater (model template)\n" +
		"// Author: @Thenecromance\n" +
		"// Update time: " + time.Now().Format(time.RFC3339)),
	jsonstruct.WithStructTagName("json"),
}

func fromJsonToGoStruct(input io.Reader, structName string, packageName string) (string, error) {
	custom := append(options,
		jsonstruct.WithTypeName(structName),
		jsonstruct.WithPackageName(packageName),
	)

	generator := jsonstruct.NewGenerator(custom...)

	if err := generator.ObserveJSONReader(input); err != nil {
		return "", err
	}

	buf, err := generator.Generate()
	if err != nil {
		return "", err
	}
	return string(buf), nil

}
