package wow_HousingDecor

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetDecorSearchResponse is the unified BNet representation for DecorSearch.
type BNetDecorSearch struct{}

// DecorSearchResponse represents the raw CN API response for DecorSearch.
type CNDecorSearch BNetDecorSearch

// ToBNet converts the CN response to the unified BNetDecorSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNDecorSearch) ToBNet() any {
	return r
}
