

package wow_HousingDecor

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// DecorModel is the unified BNet representation for Decor.
type DecorModel struct{}




// Decor represents the raw CN API response for Decor.
type CNDecorModel DecorModel

// ToBNet converts the CN  to the unified BNetDecor.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNDecorModel) ToBNet() any {
	return r
}
