package wow_HousingDecor

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetDecorIndexResponse is the unified BNet representation for DecorIndex.
type BNetDecorIndex struct{}

// DecorIndexResponse represents the raw CN API response for DecorIndex.
type CNDecorIndex BNetDecorIndex

// ToBNet converts the CN response to the unified BNetDecorIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNDecorIndex) ToBNet() any {
	return r
}
