package wow_HousingDecor

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetDecorResponse is the unified BNet representation for Decor.
type BNetDecor struct{}

// DecorResponse represents the raw CN API response for Decor.
type CNDecor BNetDecor

// ToBNet converts the CN response to the unified BNetDecorResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNDecor) ToBNet() any {
	return r
}
