package wow_HousingDecor

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetFixtureHookIndexResponse is the unified BNet representation for FixtureHookIndex.
type BNetFixtureHookIndex struct{}

// FixtureHookIndexResponse represents the raw CN API response for FixtureHookIndex.
type CNFixtureHookIndex BNetFixtureHookIndex

// ToBNet converts the CN response to the unified BNetFixtureHookIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNFixtureHookIndex) ToBNet() any {
	return r
}
