package wow_HousingDecor

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetFixtureResponse is the unified BNet representation for Fixture.
type BNetFixture struct{}

// FixtureResponse represents the raw CN API response for Fixture.
type CNFixture BNetFixture

// ToBNet converts the CN response to the unified BNetFixtureResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNFixture) ToBNet() any {
	return r
}
