package wow_HousingDecor

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetFixtureSearchResponse is the unified BNet representation for FixtureSearch.
type BNetFixtureSearch struct{}

// FixtureSearchResponse represents the raw CN API response for FixtureSearch.
type CNFixtureSearch BNetFixtureSearch

// ToBNet converts the CN response to the unified BNetFixtureSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNFixtureSearch) ToBNet() any {
	return r
}
