package wow_HousingDecor

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetFixtureIndexResponse is the unified BNet representation for FixtureIndex.
type BNetFixtureIndex struct{}

// FixtureIndexResponse represents the raw CN API response for FixtureIndex.
type CNFixtureIndex BNetFixtureIndex

// ToBNet converts the CN response to the unified BNetFixtureIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNFixtureIndex) ToBNet() any {
	return r
}
