

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_HousingDecor

type FixtureSearchModel struct {
	MaxPageSize int   `json:"maxPageSize,omitzero"`
	Page        int   `json:"page,omitzero"`
	PageCount   int   `json:"pageCount"`
	PageSize    int   `json:"pageSize"`
	Results     []any `json:"results"`
}





// FixtureSearch represents the raw CN API response for FixtureSearch.
type CNFixtureSearchModel FixtureSearchModel

// ToBNet converts the CN  to the unified BNetFixtureSearch.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNFixtureSearchModel) ToBNet() any {
	return r
}
