

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_HousingDecor

type FixtureHookSearchModel struct {
	MaxPageSize int `json:"maxPageSize,omitzero"`
	Page        int `json:"page,omitzero"`
	PageCount   int `json:"pageCount,omitzero"`
	PageSize    int `json:"pageSize,omitzero"`
	Results     []struct {
		Data struct {
			ID int `json:"id,omitzero"`
		} `json:"data"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"results"`
}





// FixtureHookSearch represents the raw CN API response for FixtureHookSearch.
type CNFixtureHookSearchModel FixtureHookSearchModel

// ToBNet converts the CN  to the unified BNetFixtureHookSearch.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNFixtureHookSearchModel) ToBNet() any {
	return r
}
