package wow_HousingDecor

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetFixtureHookSearchResponse is the unified BNet representation for FixtureHookSearch.
type BNetFixtureHookSearch struct{}

// FixtureHookSearchResponse represents the raw CN API response for FixtureHookSearch.
type CNFixtureHookSearch BNetFixtureHookSearch

// ToBNet converts the CN response to the unified BNetFixtureHookSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNFixtureHookSearch) ToBNet() any {
	return r
}
