

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_HousingDecor

type FixtureHookModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ID            int `json:"id,omitzero"`
	ParentFixture struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"parent_fixture"`
	TypeName string `json:"type_name,omitzero"`
}





// FixtureHook represents the raw CN API response for FixtureHook.
type CNFixtureHookModel FixtureHookModel

// ToBNet converts the CN  to the unified BNetFixtureHook.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNFixtureHookModel) ToBNet() any {
	return r
}
