package wow_HousingDecor

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetRoomIndexResponse is the unified BNet representation for RoomIndex.
type BNetRoomIndex struct{}

// RoomIndexResponse represents the raw CN API response for RoomIndex.
type CNRoomIndex BNetRoomIndex

// ToBNet converts the CN response to the unified BNetRoomIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNRoomIndex) ToBNet() any {
	return r
}
