

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_HousingDecor

type RoomSearchModel struct {
	MaxPageSize int   `json:"maxPageSize,omitzero"`
	Page        int   `json:"page,omitzero"`
	PageCount   int   `json:"pageCount"`
	PageSize    int   `json:"pageSize"`
	Results     []any `json:"results"`
}





// RoomSearch represents the raw CN API response for RoomSearch.
type CNRoomSearchModel RoomSearchModel

// ToBNet converts the CN  to the unified BNetRoomSearch.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNRoomSearchModel) ToBNet() any {
	return r
}
