package wow_HousingDecor

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetRoomSearchResponse is the unified BNet representation for RoomSearch.
type BNetRoomSearch struct{}

// RoomSearchResponse represents the raw CN API response for RoomSearch.
type CNRoomSearch BNetRoomSearch

// ToBNet converts the CN response to the unified BNetRoomSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNRoomSearch) ToBNet() any {
	return r
}
