

package wowClassic_Realm

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// RealmModel is the unified BNet representation for Realm.
type RealmModel struct{}




// Realm represents the raw CN API response for Realm.
type CNRealmModel RealmModel

// ToBNet converts the CN  to the unified BNetRealm.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNRealmModel) ToBNet() any {
	return r
}
