package wowClassic_Realm

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetRealmSearchResponse is the unified BNet representation for RealmSearch.
type BNetRealmSearch struct{}

// RealmSearchResponse represents the raw CN API response for RealmSearch.
type CNRealmSearch BNetRealmSearch

// ToBNet converts the CN response to the unified BNetRealmSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNRealmSearch) ToBNet() any {
	return r
}
