package D3_D3Item

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGetItemResponse is the unified BNet representation for GetItem.
type BNetGetItem struct{}

// GetItemResponse represents the raw CN API response for GetItem.
type CNGetItem BNetGetItem

// ToBNet converts the CN response to the unified BNetGetItemResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetItem) ToBNet() any {
	return r
}
