package wow_PlayableClass

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPlayableClassesIndexResponse is the unified BNet representation for PlayableClassesIndex.
type BNetPlayableClassesIndex struct{}

// PlayableClassesIndexResponse represents the raw CN API response for PlayableClassesIndex.
type CNPlayableClassesIndex BNetPlayableClassesIndex

// ToBNet converts the CN response to the unified BNetPlayableClassesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableClassesIndex) ToBNet() any {
	return r
}
