package wow_PlayableClass

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPlayableClassMediaResponse is the unified BNet representation for PlayableClassMedia.
type BNetPlayableClassMedia struct{}

// PlayableClassMediaResponse represents the raw CN API response for PlayableClassMedia.
type CNPlayableClassMedia BNetPlayableClassMedia

// ToBNet converts the CN response to the unified BNetPlayableClassMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableClassMedia) ToBNet() any {
	return r
}
