

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_PlayableClass

type PlayableClassModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	AdditionalPowerTypes []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"additional_power_types"`
	GenderName struct {
		Female string `json:"female,omitzero"`
		Male   string `json:"male,omitzero"`
	} `json:"gender_name"`
	ID    int `json:"id,omitzero"`
	Media struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	Name          string `json:"name,omitzero"`
	PlayableRaces []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"playable_races"`
	PowerType struct {
		ID  int `json:"id"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"power_type"`
	PvpTalentSlots struct {
		Href string `json:"href,omitzero"`
	} `json:"pvp_talent_slots"`
	Specializations []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"specializations"`
}





// PlayableClass represents the raw CN API response for PlayableClass.
type CNPlayableClassModel PlayableClassModel

// ToBNet converts the CN  to the unified BNetPlayableClass.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableClassModel) ToBNet() any {
	return r
}
