package wow_PlayableClass

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPlayableClassResponse is the unified BNet representation for PlayableClass.
type BNetPlayableClass struct{}

// PlayableClassResponse represents the raw CN API response for PlayableClass.
type CNPlayableClass BNetPlayableClass

// ToBNet converts the CN response to the unified BNetPlayableClassResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableClass) ToBNet() any {
	return r
}
