package wow_PlayableClass

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPvPTalentSlotsResponse is the unified BNet representation for PvPTalentSlots.
type BNetPvPTalentSlots struct{}

// PvPTalentSlotsResponse represents the raw CN API response for PvPTalentSlots.
type CNPvPTalentSlots BNetPvPTalentSlots

// ToBNet converts the CN response to the unified BNetPvPTalentSlotsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPTalentSlots) ToBNet() any {
	return r
}
