

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_PlayableClass

type PvPTalentSlotsModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	TalentSlots []struct {
		SlotNumber        int `json:"slot_number,omitzero"`
		UnlockPlayerLevel int `json:"unlock_player_level,omitzero"`
	} `json:"talent_slots"`
}





// PvPTalentSlots represents the raw CN API response for PvPTalentSlots.
type CNPvPTalentSlotsModel PvPTalentSlotsModel

// ToBNet converts the CN  to the unified BNetPvPTalentSlots.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPTalentSlotsModel) ToBNet() any {
	return r
}
