package wow_CharacterSoulbinds

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterSoulbindsResponse is the unified BNet representation for CharacterSoulbinds.
type BNetCharacterSoulbinds struct{}

// CharacterSoulbindsResponse represents the raw CN API response for CharacterSoulbinds.
type CNCharacterSoulbinds BNetCharacterSoulbinds

// ToBNet converts the CN response to the unified BNetCharacterSoulbindsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterSoulbinds) ToBNet() any {
	return r
}
