

package wowClassic_GuildCrest

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// GuildCrestEmblemMediaModel is the unified BNet representation for GuildCrestEmblemMedia.
type GuildCrestEmblemMediaModel struct{}




// GuildCrestEmblemMedia represents the raw CN API response for GuildCrestEmblemMedia.
type CNGuildCrestEmblemMediaModel GuildCrestEmblemMediaModel

// ToBNet converts the CN  to the unified BNetGuildCrestEmblemMedia.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuildCrestEmblemMediaModel) ToBNet() any {
	return r
}
