

package wowClassic_GuildCrest

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// GuildCrestBorderMediaModel is the unified BNet representation for GuildCrestBorderMedia.
type GuildCrestBorderMediaModel struct{}




// GuildCrestBorderMedia represents the raw CN API response for GuildCrestBorderMedia.
type CNGuildCrestBorderMediaModel GuildCrestBorderMediaModel

// ToBNet converts the CN  to the unified BNetGuildCrestBorderMedia.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuildCrestBorderMediaModel) ToBNet() any {
	return r
}
