

package wowClassic_GuildCrest

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// GuildCrestComponentsIndexModel is the unified BNet representation for GuildCrestComponentsIndex.
type GuildCrestComponentsIndexModel struct{}




// GuildCrestComponentsIndex represents the raw CN API response for GuildCrestComponentsIndex.
type CNGuildCrestComponentsIndexModel GuildCrestComponentsIndexModel

// ToBNet converts the CN  to the unified BNetGuildCrestComponentsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuildCrestComponentsIndexModel) ToBNet() any {
	return r
}
