package wowClassic_AuctionHouse

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAuctionHouseIndexResponse is the unified BNet representation for AuctionHouseIndex.
type BNetAuctionHouseIndex struct{}

// AuctionHouseIndexResponse represents the raw CN API response for AuctionHouseIndex.
type CNAuctionHouseIndex BNetAuctionHouseIndex

// ToBNet converts the CN response to the unified BNetAuctionHouseIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAuctionHouseIndex) ToBNet() any {
	return r
}
