

package wowClassic_AuctionHouse

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// AuctionsModel is the unified BNet representation for Auctions.
type AuctionsModel struct{}




// Auctions represents the raw CN API response for Auctions.
type CNAuctionsModel AuctionsModel

// ToBNet converts the CN  to the unified BNetAuctions.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAuctionsModel) ToBNet() any {
	return r
}
