

package wowClassic_AuctionHouse

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// AuctionHouseIndexModel is the unified BNet representation for AuctionHouseIndex.
type AuctionHouseIndexModel struct{}




// AuctionHouseIndex represents the raw CN API response for AuctionHouseIndex.
type CNAuctionHouseIndexModel AuctionHouseIndexModel

// ToBNet converts the CN  to the unified BNetAuctionHouseIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAuctionHouseIndexModel) ToBNet() any {
	return r
}
