

package wowClassic_PlayableRace

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PlayableRaceModel is the unified BNet representation for PlayableRace.
type PlayableRaceModel struct{}




// PlayableRace represents the raw CN API response for PlayableRace.
type CNPlayableRaceModel PlayableRaceModel

// ToBNet converts the CN  to the unified BNetPlayableRace.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableRaceModel) ToBNet() any {
	return r
}
