

package wowClassic_PlayableRace

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PlayableRacesIndexModel is the unified BNet representation for PlayableRacesIndex.
type PlayableRacesIndexModel struct{}




// PlayableRacesIndex represents the raw CN API response for PlayableRacesIndex.
type CNPlayableRacesIndexModel PlayableRacesIndexModel

// ToBNet converts the CN  to the unified BNetPlayableRacesIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableRacesIndexModel) ToBNet() any {
	return r
}
