package wow_Toy

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetToyResponse is the unified BNet representation for Toy.
type BNetToy struct{}

// ToyResponse represents the raw CN API response for Toy.
type CNToy BNetToy

// ToBNet converts the CN response to the unified BNetToyResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNToy) ToBNet() any {
	return r
}
