

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Toy

type ToyModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ID   int `json:"id,omitzero"`
	Item struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"item"`
	Media struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	ShouldExcludeIfUncollected bool `json:"should_exclude_if_uncollected,omitzero"`
	Source                     struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"source"`
}





// Toy represents the raw CN API response for Toy.
type CNToyModel ToyModel

// ToBNet converts the CN  to the unified BNetToy.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNToyModel) ToBNet() any {
	return r
}
