package wow_Toy

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetToyIndexResponse is the unified BNet representation for ToyIndex.
type BNetToyIndex struct{}

// ToyIndexResponse represents the raw CN API response for ToyIndex.
type CNToyIndex BNetToyIndex

// ToBNet converts the CN response to the unified BNetToyIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNToyIndex) ToBNet() any {
	return r
}
