package StarCraftII_Profile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetLadderSummaryResponse is the unified BNet representation for LadderSummary.
type BNetLadderSummary struct{}

// LadderSummaryResponse represents the raw CN API response for LadderSummary.
type CNLadderSummary BNetLadderSummary

// ToBNet converts the CN response to the unified BNetLadderSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNLadderSummary) ToBNet() any {
	return r
}
