

package StarCraftII_Profile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// LadderSummaryModel is the unified BNet representation for LadderSummary.
type LadderSummaryModel struct{}




// LadderSummary represents the raw CN API response for LadderSummary.
type CNLadderSummaryModel LadderSummaryModel

// ToBNet converts the CN  to the unified BNetLadderSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNLadderSummaryModel) ToBNet() any {
	return r
}
