

package StarCraftII_Profile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// MetadataModel is the unified BNet representation for Metadata.
type MetadataModel struct{}




// Metadata represents the raw CN API response for Metadata.
type CNMetadataModel MetadataModel

// ToBNet converts the CN  to the unified BNetMetadata.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMetadataModel) ToBNet() any {
	return r
}
