package StarCraftII_Profile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMetadataResponse is the unified BNet representation for Metadata.
type BNetMetadata struct{}

// MetadataResponse represents the raw CN API response for Metadata.
type CNMetadata BNetMetadata

// ToBNet converts the CN response to the unified BNetMetadataResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMetadata) ToBNet() any {
	return r
}
