package StarCraftII_Profile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetProfileResponse is the unified BNet representation for Profile.
type BNetProfile struct{}

// ProfileResponse represents the raw CN API response for Profile.
type CNProfile BNetProfile

// ToBNet converts the CN response to the unified BNetProfileResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNProfile) ToBNet() any {
	return r
}
