package wow_Neighborhood

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetNeighborhoodMapIndexResponse is the unified BNet representation for NeighborhoodMapIndex.
type BNetNeighborhoodMapIndex struct{}

// NeighborhoodMapIndexResponse represents the raw CN API response for NeighborhoodMapIndex.
type CNNeighborhoodMapIndex BNetNeighborhoodMapIndex

// ToBNet converts the CN response to the unified BNetNeighborhoodMapIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNNeighborhoodMapIndex) ToBNet() any {
	return r
}
