

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Neighborhood

type NeighborhoodModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ID              int `json:"id,omitzero"`
	NeighborhoodMap struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"neighborhood_map"`
	NeighborhoodName string `json:"neighborhood_name,omitzero"`
}





// Neighborhood represents the raw CN API response for Neighborhood.
type CNNeighborhoodModel NeighborhoodModel

// ToBNet converts the CN  to the unified BNetNeighborhood.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNNeighborhoodModel) ToBNet() any {
	return r
}
