package wow_Neighborhood

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetNeighborhoodMapResponse is the unified BNet representation for NeighborhoodMap.
type BNetNeighborhoodMap struct{}

// NeighborhoodMapResponse represents the raw CN API response for NeighborhoodMap.
type CNNeighborhoodMap BNetNeighborhoodMap

// ToBNet converts the CN response to the unified BNetNeighborhoodMapResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNNeighborhoodMap) ToBNet() any {
	return r
}
