package wow_WoWToken

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetWoWTokenIndexResponse is the unified BNet representation for WoWTokenIndex.
type BNetWoWTokenIndex struct{}

// WoWTokenIndexResponse represents the raw CN API response for WoWTokenIndex.
type CNWoWTokenIndex BNetWoWTokenIndex

// ToBNet converts the CN response to the unified BNetWoWTokenIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNWoWTokenIndex) ToBNet() any {
	return r
}
