

package wow_WoWToken

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// WoWTokenIndexCNModel is the unified BNet representation for WoWTokenIndexCN.
type WoWTokenIndexCNModel struct{}




// WoWTokenIndexCN represents the raw CN API response for WoWTokenIndexCN.
type CNWoWTokenIndexCNModel WoWTokenIndexCNModel

// ToBNet converts the CN  to the unified BNetWoWTokenIndexCN.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNWoWTokenIndexCNModel) ToBNet() any {
	return r
}
