

package wowClassic_CharacterHunterPets

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CharacterHunterPetsSummaryModel is the unified BNet representation for CharacterHunterPetsSummary.
type CharacterHunterPetsSummaryModel struct{}




// CharacterHunterPetsSummary represents the raw CN API response for CharacterHunterPetsSummary.
type CNCharacterHunterPetsSummaryModel CharacterHunterPetsSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterHunterPetsSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterHunterPetsSummaryModel) ToBNet() any {
	return r
}
