

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package D3_D3ArtisanandRecipe

type GetRecipeModel struct {
	Cost         int    `json:"cost,omitzero"`
	ID           string `json:"id,omitzero"`
	ItemProduced struct {
		Icon string `json:"icon,omitzero"`
		ID   string `json:"id,omitzero"`
		Name string `json:"name,omitzero"`
		Path string `json:"path,omitzero"`
		Slug string `json:"slug,omitzero"`
	} `json:"itemProduced"`
	Name     string `json:"name,omitzero"`
	Reagents []struct {
		Item struct {
			Icon string `json:"icon,omitzero"`
			ID   string `json:"id,omitzero"`
			Name string `json:"name,omitzero"`
			Path string `json:"path,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"item"`
		Quantity int `json:"quantity,omitzero"`
	} `json:"reagents"`
	Slug string `json:"slug,omitzero"`
}





// GetRecipe represents the raw CN API response for GetRecipe.
type CNGetRecipeModel GetRecipeModel

// ToBNet converts the CN  to the unified BNetGetRecipe.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetRecipeModel) ToBNet() any {
	return r
}
