package D3_D3ArtisanandRecipe

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGetRecipeResponse is the unified BNet representation for GetRecipe.
type BNetGetRecipe struct{}

// GetRecipeResponse represents the raw CN API response for GetRecipe.
type CNGetRecipe BNetGetRecipe

// ToBNet converts the CN response to the unified BNetGetRecipeResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetRecipe) ToBNet() any {
	return r
}
