

package wowClassic_Guild

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// GuildModel is the unified BNet representation for Guild.
type GuildModel struct{}




// Guild represents the raw CN API response for Guild.
type CNGuildModel GuildModel

// ToBNet converts the CN  to the unified BNetGuild.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuildModel) ToBNet() any {
	return r
}
