package wowClassic_Guild

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGuildAchievementsResponse is the unified BNet representation for GuildAchievements.
type BNetGuildAchievements struct{}

// GuildAchievementsResponse represents the raw CN API response for GuildAchievements.
type CNGuildAchievements BNetGuildAchievements

// ToBNet converts the CN response to the unified BNetGuildAchievementsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuildAchievements) ToBNet() any {
	return r
}
