package wowClassic_Guild

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGuildResponse is the unified BNet representation for Guild.
type BNetGuild struct{}

// GuildResponse represents the raw CN API response for Guild.
type CNGuild BNetGuild

// ToBNet converts the CN response to the unified BNetGuildResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuild) ToBNet() any {
	return r
}
