

package wowClassic_Guild

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// GuildAchievementsModel is the unified BNet representation for GuildAchievements.
type GuildAchievementsModel struct{}




// GuildAchievements represents the raw CN API response for GuildAchievements.
type CNGuildAchievementsModel GuildAchievementsModel

// ToBNet converts the CN  to the unified BNetGuildAchievements.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuildAchievementsModel) ToBNet() any {
	return r
}
