package wowClassic_Guild

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGuildRosterResponse is the unified BNet representation for GuildRoster.
type BNetGuildRoster struct{}

// GuildRosterResponse represents the raw CN API response for GuildRoster.
type CNGuildRoster BNetGuildRoster

// ToBNet converts the CN response to the unified BNetGuildRosterResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuildRoster) ToBNet() any {
	return r
}
