package wow_CharacterMedia

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterMediaSummaryResponse is the unified BNet representation for CharacterMediaSummary.
type BNetCharacterMediaSummary struct{}

// CharacterMediaSummaryResponse represents the raw CN API response for CharacterMediaSummary.
type CNCharacterMediaSummary BNetCharacterMediaSummary

// ToBNet converts the CN response to the unified BNetCharacterMediaSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterMediaSummary) ToBNet() any {
	return r
}
