

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_MythicRaidLeaderboard

type MythicRaidLeaderboardModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	CriteriaType string `json:"criteria_type,omitzero"`
	Entries      []struct {
		Faction struct {
			Type string `json:"type,omitzero"`
		} `json:"faction"`
		Guild struct {
			ID    int    `json:"id,omitzero"`
			Name  string `json:"name,omitzero"`
			Realm struct {
				ID   int    `json:"id,omitzero"`
				Name string `json:"name,omitzero"`
				Slug string `json:"slug,omitzero"`
			} `json:"realm"`
		} `json:"guild"`
		Rank      int    `json:"rank,omitzero"`
		Region    string `json:"region,omitzero"`
		Timestamp int    `json:"timestamp,omitzero"`
	} `json:"entries"`
	JournalInstance struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"journal_instance"`
	Slug string `json:"slug,omitzero"`
}





// MythicRaidLeaderboard represents the raw CN API response for MythicRaidLeaderboard.
type CNMythicRaidLeaderboardModel MythicRaidLeaderboardModel

// ToBNet converts the CN  to the unified BNetMythicRaidLeaderboard.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicRaidLeaderboardModel) ToBNet() any {
	return r
}
