package wow_MythicRaidLeaderboard

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMythicRaidLeaderboardResponse is the unified BNet representation for MythicRaidLeaderboard.
type BNetMythicRaidLeaderboard struct{}

// MythicRaidLeaderboardResponse represents the raw CN API response for MythicRaidLeaderboard.
type CNMythicRaidLeaderboard BNetMythicRaidLeaderboard

// ToBNet converts the CN response to the unified BNetMythicRaidLeaderboardResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicRaidLeaderboard) ToBNet() any {
	return r
}
