

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_PvPTier

type PvPTierModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Bracket struct {
		ID   int    `json:"id"`
		Type string `json:"type,omitzero"`
	} `json:"bracket"`
	ID        int `json:"id,omitzero"`
	MaxRating int `json:"max_rating,omitzero"`
	Media     struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	MinRating  int    `json:"min_rating"`
	Name       string `json:"name,omitzero"`
	RatingType int    `json:"rating_type"`
}





// PvPTier represents the raw CN API response for PvPTier.
type CNPvPTierModel PvPTierModel

// ToBNet converts the CN  to the unified BNetPvPTier.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPTierModel) ToBNet() any {
	return r
}
