package wow_PvPTier

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPvPTierMediaResponse is the unified BNet representation for PvPTierMedia.
type BNetPvPTierMedia struct{}

// PvPTierMediaResponse represents the raw CN API response for PvPTierMedia.
type CNPvPTierMedia BNetPvPTierMedia

// ToBNet converts the CN response to the unified BNetPvPTierMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPTierMedia) ToBNet() any {
	return r
}
