package wow_PvPTier

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPvPTierResponse is the unified BNet representation for PvPTier.
type BNetPvPTier struct{}

// PvPTierResponse represents the raw CN API response for PvPTier.
type CNPvPTier BNetPvPTier

// ToBNet converts the CN response to the unified BNetPvPTierResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPTier) ToBNet() any {
	return r
}
