package wow_PvPTier

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPvPTiersIndexResponse is the unified BNet representation for PvPTiersIndex.
type BNetPvPTiersIndex struct{}

// PvPTiersIndexResponse represents the raw CN API response for PvPTiersIndex.
type CNPvPTiersIndex BNetPvPTiersIndex

// ToBNet converts the CN response to the unified BNetPvPTiersIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPTiersIndex) ToBNet() any {
	return r
}
