

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Heirloom

type HeirloomModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ID   int `json:"id,omitzero"`
	Item struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"item"`
	Media struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	Source struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"source"`
	SourceDescription string `json:"source_description,omitzero"`
	Upgrades          []struct {
		Item struct {
			Binding struct {
				Name string `json:"name,omitzero"`
				Type string `json:"type,omitzero"`
			} `json:"binding"`
			BonusList     []int `json:"bonus_list"`
			Context       int   `json:"context"`
			InventoryType struct {
				Name string `json:"name,omitzero"`
				Type string `json:"type,omitzero"`
			} `json:"inventory_type"`
			Item struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
			} `json:"item"`
			ItemClass struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"item_class"`
			ItemSubclass struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"item_subclass"`
			Level struct {
				DisplayString string `json:"display_string,omitzero"`
				Value         int    `json:"value,omitzero"`
			} `json:"level"`
			Media struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
			} `json:"media"`
			Name    string `json:"name,omitzero"`
			Quality struct {
				Name string `json:"name,omitzero"`
				Type string `json:"type,omitzero"`
			} `json:"quality"`
			Requirements struct {
				Level struct {
					DisplayString string `json:"display_string,omitzero"`
				} `json:"level"`
			} `json:"requirements"`
			Stats []struct {
				Display struct {
					Color struct {
						A float64 `json:"a,omitzero"`
						B int     `json:"b"`
						G int     `json:"g,omitzero"`
						R int     `json:"r"`
					} `json:"color"`
					DisplayString string `json:"display_string,omitzero"`
				} `json:"display"`
				IsEquipBonus bool `json:"is_equip_bonus,omitempty,omitzero"`
				Type         struct {
					Name string `json:"name,omitzero"`
					Type string `json:"type,omitzero"`
				} `json:"type"`
				Value int `json:"value,omitzero"`
			} `json:"stats"`
			Upgrades struct {
				DisplayString string `json:"display_string,omitzero"`
				MaxValue      int    `json:"max_value,omitzero"`
				Value         int    `json:"value,omitzero"`
			} `json:"upgrades"`
			Weapon struct {
				AttackSpeed struct {
					DisplayString string `json:"display_string,omitzero"`
					Value         int    `json:"value,omitzero"`
				} `json:"attack_speed"`
				Damage struct {
					DamageClass struct {
						Name string `json:"name,omitzero"`
						Type string `json:"type,omitzero"`
					} `json:"damage_class"`
					DisplayString string `json:"display_string,omitzero"`
					MaxValue      int    `json:"max_value,omitzero"`
					MinValue      int    `json:"min_value,omitzero"`
				} `json:"damage"`
				Dps struct {
					DisplayString string  `json:"display_string,omitzero"`
					Value         float64 `json:"value,omitzero"`
				} `json:"dps"`
			} `json:"weapon"`
		} `json:"item"`
		Level int `json:"level"`
	} `json:"upgrades"`
}





// Heirloom represents the raw CN API response for Heirloom.
type CNHeirloomModel HeirloomModel

// ToBNet converts the CN  to the unified BNetHeirloom.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNHeirloomModel) ToBNet() any {
	return r
}
