package wow_Heirloom

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetHeirloomIndexResponse is the unified BNet representation for HeirloomIndex.
type BNetHeirloomIndex struct{}

// HeirloomIndexResponse represents the raw CN API response for HeirloomIndex.
type CNHeirloomIndex BNetHeirloomIndex

// ToBNet converts the CN response to the unified BNetHeirloomIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNHeirloomIndex) ToBNet() any {
	return r
}
