package wow_Heirloom

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetHeirloomResponse is the unified BNet representation for Heirloom.
type BNetHeirloom struct{}

// HeirloomResponse represents the raw CN API response for Heirloom.
type CNHeirloom BNetHeirloom

// ToBNet converts the CN response to the unified BNetHeirloomResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNHeirloom) ToBNet() any {
	return r
}
