

package wowClassic_CharacterProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CharacterProfileStatusModel is the unified BNet representation for CharacterProfileStatus.
type CharacterProfileStatusModel struct{}




// CharacterProfileStatus represents the raw CN API response for CharacterProfileStatus.
type CNCharacterProfileStatusModel CharacterProfileStatusModel

// ToBNet converts the CN  to the unified BNetCharacterProfileStatus.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterProfileStatusModel) ToBNet() any {
	return r
}
