package wow_Spell

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetSpellMediaResponse is the unified BNet representation for SpellMedia.
type BNetSpellMedia struct{}

// SpellMediaResponse represents the raw CN API response for SpellMedia.
type CNSpellMedia BNetSpellMedia

// ToBNet converts the CN response to the unified BNetSpellMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSpellMedia) ToBNet() any {
	return r
}
