

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Spell

type SpellModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Description string `json:"description,omitzero"`
	ID          int    `json:"id,omitzero"`
	Media       struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	Name string `json:"name,omitzero"`
}





// Spell represents the raw CN API response for Spell.
type CNSpellModel SpellModel

// ToBNet converts the CN  to the unified BNetSpell.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSpellModel) ToBNet() any {
	return r
}
