package wow_Spell

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetSpellSearchResponse is the unified BNet representation for SpellSearch.
type BNetSpellSearch struct{}

// SpellSearchResponse represents the raw CN API response for SpellSearch.
type CNSpellSearch BNetSpellSearch

// ToBNet converts the CN response to the unified BNetSpellSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSpellSearch) ToBNet() any {
	return r
}
