package wow_Spell

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetSpellResponse is the unified BNet representation for Spell.
type BNetSpell struct{}

// SpellResponse represents the raw CN API response for Spell.
type CNSpell BNetSpell

// ToBNet converts the CN response to the unified BNetSpellResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSpell) ToBNet() any {
	return r
}
