// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterMythicKeystoneProfile

type CharacterMythicKeystoneSeasonDetailsModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	BestRuns []struct {
		CompletedTimestamp int `json:"completed_timestamp,omitzero"`
		Dungeon            struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"dungeon"`
		Duration              int  `json:"duration,omitzero"`
		IsCompletedWithinTime bool `json:"is_completed_within_time"`
		KeystoneAffixes       []struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"keystone_affixes"`
		KeystoneLevel int `json:"keystone_level,omitzero"`
		Members       []struct {
			Character struct {
				ID    int    `json:"id,omitzero"`
				Name  string `json:"name,omitzero"`
				Realm struct {
					ID  int `json:"id,omitzero"`
					Key struct {
						Href string `json:"href,omitzero"`
					} `json:"key"`
					Slug string `json:"slug,omitzero"`
				} `json:"realm"`
			} `json:"character"`
			EquippedItemLevel int `json:"equipped_item_level,omitzero"`
			Race              struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"race"`
			Specialization struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"specialization"`
		} `json:"members"`
		MythicRating struct {
			Color struct {
				A float64 `json:"a,omitzero"`
				B int     `json:"b"`
				G int     `json:"g,omitzero"`
				R int     `json:"r,omitzero"`
			} `json:"color"`
			Rating float64 `json:"rating,omitzero"`
		} `json:"mythic_rating"`
	} `json:"best_runs"`
	Character struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name  string `json:"name,omitzero"`
		Realm struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"realm"`
	} `json:"character"`
	MythicRating struct {
		Color struct {
			A float64 `json:"a,omitzero"`
			B int     `json:"b"`
			G int     `json:"g,omitzero"`
			R int     `json:"r,omitzero"`
		} `json:"color"`
		Rating float64 `json:"rating,omitzero"`
	} `json:"mythic_rating"`
	Season struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"season"`
}

// CharacterMythicKeystoneSeasonDetails represents the raw CN API response for CharacterMythicKeystoneSeasonDetails.
type CNCharacterMythicKeystoneSeasonDetailsModel struct {
	BestRuns []struct {
		CompletedTimestamp int64 `json:"completed_timestamp"`
		Dungeon            struct {
			Icon string `json:"icon"`
			Id   int    `json:"id"`
			Key  struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
		} `json:"dungeon"`
		Duration              int  `json:"duration"`
		IsCompletedWithinTime bool `json:"is_completed_within_time"`
		KeystoneAffixes       []struct {
			Description string `json:"description"`
			Icon        string `json:"icon"`
			Id          int    `json:"id"`
			Name        string `json:"name"`
		} `json:"keystone_affixes"`
		KeystoneLevel int `json:"keystone_level"`
		MapRating     struct {
			Color struct {
				A int `json:"a"`
				B int `json:"b"`
				G int `json:"g"`
				R int `json:"r"`
			} `json:"color"`
			Rating float64 `json:"rating"`
		} `json:"map_rating"`
		Members []struct {
			Character struct {
				CharacterId string `json:"character_id"`
				ClassId     int    `json:"class_id"`
				Id          int    `json:"id"`
				Name        string `json:"name"`
				Realm       struct {
					Id   int    `json:"id"`
					Slug string `json:"slug"`
				} `json:"realm"`
			} `json:"character"`
			EquippedItemLevel int `json:"equipped_item_level"`
			Race              struct {
				Id   int    `json:"id"`
				Name string `json:"name"`
			} `json:"race"`
			Specialization struct {
				Id   int    `json:"id"`
				Name string `json:"name"`
			} `json:"specialization"`
		} `json:"members"`
		MythicRating struct {
			Color struct {
				A int `json:"a"`
				B int `json:"b"`
				G int `json:"g"`
				R int `json:"r"`
			} `json:"color"`
			Rating float64 `json:"rating"`
		} `json:"mythic_rating"`
	} `json:"best_runs"`
	Character struct {
		Id  int `json:"id"`
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name  string `json:"name"`
		Realm struct {
			Id  int `json:"id"`
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name string `json:"name"`
			Slug string `json:"slug"`
		} `json:"realm"`
	} `json:"character"`
	MythicRating struct {
		Color struct {
			A int `json:"a"`
			B int `json:"b"`
			G int `json:"g"`
			R int `json:"r"`
		} `json:"color"`
		Rating float64 `json:"rating"`
	} `json:"mythic_rating"`
	Season struct {
		Key struct {
			Href string `json:"href"`
		} `json:"Key"`
		Id        int    `json:"id"`
		SeasonStr string `json:"season_str"`
	} `json:"season"`
}

// ToBNet converts the CN  to the unified BNetCharacterMythicKeystoneSeasonDetails.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterMythicKeystoneSeasonDetailsModel) ToBNet() any {
	return r
}
