package wow_CharacterMythicKeystoneProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterMythicKeystoneSeasonDetailsResponse is the unified BNet representation for CharacterMythicKeystoneSeasonDetails.
type BNetCharacterMythicKeystoneSeasonDetails struct{}

// CharacterMythicKeystoneSeasonDetailsResponse represents the raw CN API response for CharacterMythicKeystoneSeasonDetails.
type CNCharacterMythicKeystoneSeasonDetails BNetCharacterMythicKeystoneSeasonDetails

// ToBNet converts the CN response to the unified BNetCharacterMythicKeystoneSeasonDetailsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterMythicKeystoneSeasonDetails) ToBNet() any {
	return r
}
