package wow_Journal

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetJournalInstanceMediaResponse is the unified BNet representation for JournalInstanceMedia.
type BNetJournalInstanceMedia struct{}

// JournalInstanceMediaResponse represents the raw CN API response for JournalInstanceMedia.
type CNJournalInstanceMedia BNetJournalInstanceMedia

// ToBNet converts the CN response to the unified BNetJournalInstanceMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNJournalInstanceMedia) ToBNet() any {
	return r
}
