

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Journal

type JournalExpansionModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Dungeons []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"dungeons"`
	ID    int    `json:"id,omitzero"`
	Name  string `json:"name,omitzero"`
	Raids []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"raids"`
}





// JournalExpansion represents the raw CN API response for JournalExpansion.
type CNJournalExpansionModel JournalExpansionModel

// ToBNet converts the CN  to the unified BNetJournalExpansion.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNJournalExpansionModel) ToBNet() any {
	return r
}
