package wow_Journal

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetJournalInstanceResponse is the unified BNet representation for JournalInstance.
type BNetJournalInstance struct{}

// JournalInstanceResponse represents the raw CN API response for JournalInstance.
type CNJournalInstance BNetJournalInstance

// ToBNet converts the CN response to the unified BNetJournalInstanceResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNJournalInstance) ToBNet() any {
	return r
}
