package wow_Journal

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetJournalInstancesIndexResponse is the unified BNet representation for JournalInstancesIndex.
type BNetJournalInstancesIndex struct{}

// JournalInstancesIndexResponse represents the raw CN API response for JournalInstancesIndex.
type CNJournalInstancesIndex BNetJournalInstancesIndex

// ToBNet converts the CN response to the unified BNetJournalInstancesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNJournalInstancesIndex) ToBNet() any {
	return r
}
