

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Journal

type JournalInstanceModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Area struct {
		ID   int    `json:"id,omitzero"`
		Name string `json:"name,omitzero"`
	} `json:"area"`
	Category struct {
		Type string `json:"type,omitzero"`
	} `json:"category"`
	Description string `json:"description,omitzero"`
	Encounters  []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"encounters"`
	Expansion struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"expansion"`
	ID       int `json:"id,omitzero"`
	Location struct {
		ID   int    `json:"id,omitzero"`
		Name string `json:"name,omitzero"`
	} `json:"location"`
	Map struct {
		ID   int    `json:"id,omitzero"`
		Name string `json:"name,omitzero"`
	} `json:"map"`
	Media struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	MinimumLevel int `json:"minimum_level,omitzero"`
	Modes        []struct {
		IsTracked bool `json:"is_tracked,omitzero"`
		Mode      struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"mode"`
		Players int `json:"players,omitzero"`
	} `json:"modes"`
	Name       string `json:"name,omitzero"`
	OrderIndex int    `json:"order_index"`
}





// JournalInstance represents the raw CN API response for JournalInstance.
type CNJournalInstanceModel JournalInstanceModel

// ToBNet converts the CN  to the unified BNetJournalInstance.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNJournalInstanceModel) ToBNet() any {
	return r
}
