package wow_Journal

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetJournalEncounterSearchResponse is the unified BNet representation for JournalEncounterSearch.
type BNetJournalEncounterSearch struct{}

// JournalEncounterSearchResponse represents the raw CN API response for JournalEncounterSearch.
type CNJournalEncounterSearch BNetJournalEncounterSearch

// ToBNet converts the CN response to the unified BNetJournalEncounterSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNJournalEncounterSearch) ToBNet() any {
	return r
}
