package wow_Journal

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetJournalEncountersIndexResponse is the unified BNet representation for JournalEncountersIndex.
type BNetJournalEncountersIndex struct{}

// JournalEncountersIndexResponse represents the raw CN API response for JournalEncountersIndex.
type CNJournalEncountersIndex BNetJournalEncountersIndex

// ToBNet converts the CN response to the unified BNetJournalEncountersIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNJournalEncountersIndex) ToBNet() any {
	return r
}
