package wow_Journal

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetJournalExpansionsIndexResponse is the unified BNet representation for JournalExpansionsIndex.
type BNetJournalExpansionsIndex struct{}

// JournalExpansionsIndexResponse represents the raw CN API response for JournalExpansionsIndex.
type CNJournalExpansionsIndex BNetJournalExpansionsIndex

// ToBNet converts the CN response to the unified BNetJournalExpansionsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNJournalExpansionsIndex) ToBNet() any {
	return r
}
