package wow_Journal

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetJournalEncounterResponse is the unified BNet representation for JournalEncounter.
type BNetJournalEncounter struct{}

// JournalEncounterResponse represents the raw CN API response for JournalEncounter.
type CNJournalEncounter BNetJournalEncounter

// ToBNet converts the CN response to the unified BNetJournalEncounterResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNJournalEncounter) ToBNet() any {
	return r
}
