package wow_Pet

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPetResponse is the unified BNet representation for Pet.
type BNetPet struct{}

// PetResponse represents the raw CN API response for Pet.
type CNPet BNetPet

// ToBNet converts the CN response to the unified BNetPetResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPet) ToBNet() any {
	return r
}
