

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Pet

type PetModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Abilities []struct {
		Ability struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"ability"`
		RequiredLevel int `json:"required_level,omitzero"`
		Slot          int `json:"slot"`
	} `json:"abilities"`
	BattlePetType struct {
		ID   int    `json:"id,omitzero"`
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"battle_pet_type"`
	Creature struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"creature"`
	Description             string `json:"description,omitzero"`
	Icon                    string `json:"icon,omitzero"`
	ID                      int    `json:"id,omitzero"`
	IsAllianceOnly          bool   `json:"is_alliance_only"`
	IsBattlepet             bool   `json:"is_battlepet,omitzero"`
	IsCapturable            bool   `json:"is_capturable"`
	IsHordeOnly             bool   `json:"is_horde_only"`
	IsRandomCreatureDisplay bool   `json:"is_random_creature_display"`
	IsTradable              bool   `json:"is_tradable,omitzero"`
	Media                   struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	Name   string `json:"name,omitzero"`
	Source struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"source"`
}





// Pet represents the raw CN API response for Pet.
type CNPetModel PetModel

// ToBNet converts the CN  to the unified BNetPet.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPetModel) ToBNet() any {
	return r
}
