

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Pet

type PetAbilitiesIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Abilities []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"abilities"`
}





// PetAbilitiesIndex represents the raw CN API response for PetAbilitiesIndex.
type CNPetAbilitiesIndexModel PetAbilitiesIndexModel

// ToBNet converts the CN  to the unified BNetPetAbilitiesIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPetAbilitiesIndexModel) ToBNet() any {
	return r
}
