package wow_Pet

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPetAbilityMediaResponse is the unified BNet representation for PetAbilityMedia.
type BNetPetAbilityMedia struct{}

// PetAbilityMediaResponse represents the raw CN API response for PetAbilityMedia.
type CNPetAbilityMedia BNetPetAbilityMedia

// ToBNet converts the CN response to the unified BNetPetAbilityMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPetAbilityMedia) ToBNet() any {
	return r
}
