package wow_Pet

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPetAbilityResponse is the unified BNet representation for PetAbility.
type BNetPetAbility struct{}

// PetAbilityResponse represents the raw CN API response for PetAbility.
type CNPetAbility BNetPetAbility

// ToBNet converts the CN response to the unified BNetPetAbilityResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPetAbility) ToBNet() any {
	return r
}
