package wow_Pet

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPetMediaResponse is the unified BNet representation for PetMedia.
type BNetPetMedia struct{}

// PetMediaResponse represents the raw CN API response for PetMedia.
type CNPetMedia BNetPetMedia

// ToBNet converts the CN response to the unified BNetPetMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPetMedia) ToBNet() any {
	return r
}
