package wow_Pet

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPetsIndexResponse is the unified BNet representation for PetsIndex.
type BNetPetsIndex struct{}

// PetsIndexResponse represents the raw CN API response for PetsIndex.
type CNPetsIndex BNetPetsIndex

// ToBNet converts the CN response to the unified BNetPetsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPetsIndex) ToBNet() any {
	return r
}
