package wow_Talent

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPvPTalentsIndexResponse is the unified BNet representation for PvPTalentsIndex.
type BNetPvPTalentsIndex struct{}

// PvPTalentsIndexResponse represents the raw CN API response for PvPTalentsIndex.
type CNPvPTalentsIndex BNetPvPTalentsIndex

// ToBNet converts the CN response to the unified BNetPvPTalentsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPTalentsIndex) ToBNet() any {
	return r
}
