package wow_Talent

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPvPTalentResponse is the unified BNet representation for PvPTalent.
type BNetPvPTalent struct{}

// PvPTalentResponse represents the raw CN API response for PvPTalent.
type CNPvPTalent BNetPvPTalent

// ToBNet converts the CN response to the unified BNetPvPTalentResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPvPTalent) ToBNet() any {
	return r
}
