

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Talent

type TalentTreeModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ClassTalentNodes []struct {
		DisplayCol int   `json:"display_col,omitzero"`
		DisplayRow int   `json:"display_row,omitzero"`
		ID         int   `json:"id,omitzero"`
		LockedBy   []int `json:"locked_by,omitempty"`
		NodeType   struct {
			ID   int    `json:"id"`
			Type string `json:"type,omitzero"`
		} `json:"node_type"`
		Ranks []struct {
			ChoiceOfTooltips []struct {
				SpellTooltip struct {
					CastTime    string `json:"cast_time,omitzero"`
					Cooldown    string `json:"cooldown,omitempty,omitzero"`
					Description string `json:"description,omitzero"`
					PowerCost   any    `json:"power_cost,omitempty"`
					Range       string `json:"range,omitempty,omitzero"`
					Spell       struct {
						ID  int `json:"id,omitzero"`
						Key struct {
							Href string `json:"href,omitzero"`
						} `json:"key"`
						Name string `json:"name,omitzero"`
					} `json:"spell"`
				} `json:"spell_tooltip"`
				Talent struct {
					ID  int `json:"id,omitzero"`
					Key struct {
						Href string `json:"href,omitzero"`
					} `json:"key"`
					Name string `json:"name,omitzero"`
				} `json:"talent"`
			} `json:"choice_of_tooltips,omitempty"`
			DefaultPoints int `json:"default_points,omitempty,omitzero"`
			Rank          int `json:"rank,omitzero"`
			Tooltip       *struct {
				SpellTooltip struct {
					CastTime    string  `json:"cast_time,omitzero"`
					Cooldown    string  `json:"cooldown,omitempty,omitzero"`
					Description string  `json:"description,omitzero"`
					PowerCost   *string `json:"power_cost"`
					Range       string  `json:"range,omitempty,omitzero"`
					Spell       struct {
						ID  int `json:"id,omitzero"`
						Key struct {
							Href string `json:"href,omitzero"`
						} `json:"key"`
						Name string `json:"name,omitzero"`
					} `json:"spell"`
				} `json:"spell_tooltip"`
				Talent struct {
					ID  int `json:"id,omitzero"`
					Key struct {
						Href string `json:"href,omitzero"`
					} `json:"key"`
					Name string `json:"name,omitzero"`
				} `json:"talent"`
			} `json:"tooltip,omitempty,omitzero"`
		} `json:"ranks"`
		RawPositionX int   `json:"raw_position_x,omitzero"`
		RawPositionY int   `json:"raw_position_y,omitzero"`
		Unlocks      []int `json:"unlocks,omitempty"`
	} `json:"class_talent_nodes"`
	HeroTalentTrees []struct {
		HeroTalentNodes []struct {
			DisplayCol int   `json:"display_col,omitzero"`
			DisplayRow int   `json:"display_row,omitzero"`
			ID         int   `json:"id,omitzero"`
			LockedBy   []int `json:"locked_by,omitempty"`
			NodeType   struct {
				ID   int    `json:"id"`
				Type string `json:"type,omitzero"`
			} `json:"node_type"`
			Ranks []struct {
				ChoiceOfTooltips []struct {
					SpellTooltip struct {
						CastTime    string `json:"cast_time,omitzero"`
						Description string `json:"description,omitzero"`
						Spell       struct {
							ID  int `json:"id,omitzero"`
							Key struct {
								Href string `json:"href,omitzero"`
							} `json:"key"`
							Name string `json:"name,omitzero"`
						} `json:"spell"`
					} `json:"spell_tooltip"`
					Talent struct {
						ID  int `json:"id,omitzero"`
						Key struct {
							Href string `json:"href,omitzero"`
						} `json:"key"`
						Name string `json:"name,omitzero"`
					} `json:"talent"`
				} `json:"choice_of_tooltips,omitempty"`
				DefaultPoints int `json:"default_points,omitempty,omitzero"`
				Rank          int `json:"rank,omitzero"`
				Tooltip       *struct {
					SpellTooltip struct {
						CastTime    string `json:"cast_time,omitzero"`
						Cooldown    string `json:"cooldown,omitempty,omitzero"`
						Description string `json:"description,omitzero"`
						PowerCost   any    `json:"power_cost,omitempty"`
						Range       string `json:"range,omitempty,omitzero"`
						Spell       struct {
							ID  int `json:"id,omitzero"`
							Key struct {
								Href string `json:"href,omitzero"`
							} `json:"key"`
							Name string `json:"name,omitzero"`
						} `json:"spell"`
					} `json:"spell_tooltip"`
					Talent struct {
						ID  int `json:"id,omitzero"`
						Key struct {
							Href string `json:"href,omitzero"`
						} `json:"key"`
						Name string `json:"name,omitzero"`
					} `json:"talent"`
				} `json:"tooltip,omitempty,omitzero"`
			} `json:"ranks"`
			RawPositionX int   `json:"raw_position_x,omitzero"`
			RawPositionY int   `json:"raw_position_y,omitzero"`
			Unlocks      []int `json:"unlocks,omitempty"`
		} `json:"hero_talent_nodes"`
		ID    int `json:"id,omitzero"`
		Media struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
		} `json:"media"`
		Name          string `json:"name,omitzero"`
		PlayableClass struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"playable_class"`
		PlayableSpecializations []struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"playable_specializations"`
	} `json:"hero_talent_trees"`
	ID    int `json:"id,omitzero"`
	Media struct {
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	Name          string `json:"name,omitzero"`
	PlayableClass struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"playable_class"`
	PlayableSpecialization struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"playable_specialization"`
	RestrictionLines []struct {
		IsForClass     bool    `json:"is_for_class"`
		RequiredPoints int     `json:"required_points,omitzero"`
		RestrictedRow  float64 `json:"restricted_row,omitzero"`
	} `json:"restriction_lines"`
	SpecTalentNodes []struct {
		DisplayCol int   `json:"display_col,omitzero"`
		DisplayRow int   `json:"display_row,omitzero"`
		ID         int   `json:"id,omitzero"`
		LockedBy   []int `json:"locked_by,omitempty"`
		NodeType   struct {
			ID   int    `json:"id"`
			Type string `json:"type,omitzero"`
		} `json:"node_type"`
		Ranks []struct {
			ChoiceOfTooltips []struct {
				SpellTooltip struct {
					CastTime    string  `json:"cast_time,omitzero"`
					Description string  `json:"description,omitzero"`
					PowerCost   *string `json:"power_cost"`
					Range       string  `json:"range,omitempty,omitzero"`
					Spell       struct {
						ID  int `json:"id,omitzero"`
						Key struct {
							Href string `json:"href,omitzero"`
						} `json:"key"`
						Name string `json:"name,omitzero"`
					} `json:"spell"`
				} `json:"spell_tooltip"`
				Talent struct {
					ID  int `json:"id,omitzero"`
					Key struct {
						Href string `json:"href,omitzero"`
					} `json:"key"`
					Name string `json:"name,omitzero"`
				} `json:"talent"`
			} `json:"choice_of_tooltips,omitempty"`
			Rank    int `json:"rank,omitzero"`
			Tooltip *struct {
				SpellTooltip struct {
					CastTime    string `json:"cast_time,omitzero"`
					Cooldown    string `json:"cooldown,omitempty,omitzero"`
					Description string `json:"description,omitzero"`
					PowerCost   string `json:"power_cost,omitempty,omitzero"`
					Range       string `json:"range,omitempty,omitzero"`
					Spell       struct {
						ID  int `json:"id,omitzero"`
						Key struct {
							Href string `json:"href,omitzero"`
						} `json:"key"`
						Name string `json:"name,omitzero"`
					} `json:"spell"`
				} `json:"spell_tooltip"`
				Talent struct {
					ID  int `json:"id,omitzero"`
					Key struct {
						Href string `json:"href,omitzero"`
					} `json:"key"`
					Name string `json:"name,omitzero"`
				} `json:"talent"`
			} `json:"tooltip,omitempty,omitzero"`
		} `json:"ranks"`
		RawPositionX int   `json:"raw_position_x,omitzero"`
		RawPositionY int   `json:"raw_position_y,omitzero"`
		Unlocks      []int `json:"unlocks,omitempty"`
	} `json:"spec_talent_nodes"`
}





// TalentTree represents the raw CN API response for TalentTree.
type CNTalentTreeModel TalentTreeModel

// ToBNet converts the CN  to the unified BNetTalentTree.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTalentTreeModel) ToBNet() any {
	return r
}
