package wow_Talent

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetTalentResponse is the unified BNet representation for Talent.
type BNetTalent struct{}

// TalentResponse represents the raw CN API response for Talent.
type CNTalent BNetTalent

// ToBNet converts the CN response to the unified BNetTalentResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTalent) ToBNet() any {
	return r
}
