

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Talent

type TalentsIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Talents []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"talents"`
}





// TalentsIndex represents the raw CN API response for TalentsIndex.
type CNTalentsIndexModel TalentsIndexModel

// ToBNet converts the CN  to the unified BNetTalentsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTalentsIndexModel) ToBNet() any {
	return r
}
