package wow_Talent

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetTalentTreeResponse is the unified BNet representation for TalentTree.
type BNetTalentTree struct{}

// TalentTreeResponse represents the raw CN API response for TalentTree.
type CNTalentTree BNetTalentTree

// ToBNet converts the CN response to the unified BNetTalentTreeResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTalentTree) ToBNet() any {
	return r
}
