package wow_Talent

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetTalentTreeIndexResponse is the unified BNet representation for TalentTreeIndex.
type BNetTalentTreeIndex struct{}

// TalentTreeIndexResponse represents the raw CN API response for TalentTreeIndex.
type CNTalentTreeIndex BNetTalentTreeIndex

// ToBNet converts the CN response to the unified BNetTalentTreeIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTalentTreeIndex) ToBNet() any {
	return r
}
