

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Talent

type TalentTreeIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ClassTalentTrees []struct {
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"class_talent_trees"`
	HeroTalentTrees []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"hero_talent_trees"`
	SpecTalentTrees []struct {
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"spec_talent_trees"`
}





// TalentTreeIndex represents the raw CN API response for TalentTreeIndex.
type CNTalentTreeIndexModel TalentTreeIndexModel

// ToBNet converts the CN  to the unified BNetTalentTreeIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTalentTreeIndexModel) ToBNet() any {
	return r
}
