

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterCollections

type CharacterMountsCollectionSummaryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Mounts []struct {
		IsFavorite bool `json:"is_favorite,omitempty,omitzero"`
		IsUseable  bool `json:"is_useable"`
		Mount      struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"mount"`
	} `json:"mounts"`
}





// CharacterMountsCollectionSummary represents the raw CN API response for CharacterMountsCollectionSummary.
type CNCharacterMountsCollectionSummaryModel CharacterMountsCollectionSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterMountsCollectionSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterMountsCollectionSummaryModel) ToBNet() any {
	return r
}
