

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterCollections

type CharacterCollectionsIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Character struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name  string `json:"name,omitzero"`
		Realm struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"realm"`
	} `json:"character"`
	Decors struct {
		Href string `json:"href,omitzero"`
	} `json:"decors"`
	Heirlooms struct {
		Href string `json:"href,omitzero"`
	} `json:"heirlooms"`
	Mounts struct {
		Href string `json:"href,omitzero"`
	} `json:"mounts"`
	Pets struct {
		Href string `json:"href,omitzero"`
	} `json:"pets"`
	Toys struct {
		Href string `json:"href,omitzero"`
	} `json:"toys"`
	Transmogs struct {
		Href string `json:"href,omitzero"`
	} `json:"transmogs"`
}





// CharacterCollectionsIndex represents the raw CN API response for CharacterCollectionsIndex.
type CNCharacterCollectionsIndexModel CharacterCollectionsIndexModel

// ToBNet converts the CN  to the unified BNetCharacterCollectionsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterCollectionsIndexModel) ToBNet() any {
	return r
}
