package wow_CharacterCollections

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterCollectionsIndexResponse is the unified BNet representation for CharacterCollectionsIndex.
type BNetCharacterCollectionsIndex struct{}

// CharacterCollectionsIndexResponse represents the raw CN API response for CharacterCollectionsIndex.
type CNCharacterCollectionsIndex BNetCharacterCollectionsIndex

// ToBNet converts the CN response to the unified BNetCharacterCollectionsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterCollectionsIndex) ToBNet() any {
	return r
}
