package wow_CharacterCollections

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterDecorCollectionSummaryResponse is the unified BNet representation for CharacterDecorCollectionSummary.
type BNetCharacterDecorCollectionSummary struct{}

// CharacterDecorCollectionSummaryResponse represents the raw CN API response for CharacterDecorCollectionSummary.
type CNCharacterDecorCollectionSummary BNetCharacterDecorCollectionSummary

// ToBNet converts the CN response to the unified BNetCharacterDecorCollectionSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterDecorCollectionSummary) ToBNet() any {
	return r
}
