

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterCollections

type CharacterPetsCollectionSummaryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Pets []struct {
		ActiveSlot      int `json:"active_slot,omitempty"`
		CreatureDisplay *struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
		} `json:"creature_display,omitempty,omitzero"`
		ID       int    `json:"id,omitzero"`
		IsActive bool   `json:"is_active,omitempty,omitzero"`
		Level    int    `json:"level,omitzero"`
		Name     string `json:"name,omitempty,omitzero"`
		Quality  struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"quality"`
		Species struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"species"`
		Stats struct {
			BreedID int `json:"breed_id,omitzero"`
			Health  int `json:"health,omitzero"`
			Power   int `json:"power,omitzero"`
			Speed   int `json:"speed,omitzero"`
		} `json:"stats"`
	} `json:"pets"`
	UnlockedBattlePetSlots int `json:"unlocked_battle_pet_slots,omitzero"`
}





// CharacterPetsCollectionSummary represents the raw CN API response for CharacterPetsCollectionSummary.
type CNCharacterPetsCollectionSummaryModel CharacterPetsCollectionSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterPetsCollectionSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterPetsCollectionSummaryModel) ToBNet() any {
	return r
}
