package wow_CharacterCollections

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterToysCollectionSummaryResponse is the unified BNet representation for CharacterToysCollectionSummary.
type BNetCharacterToysCollectionSummary struct{}

// CharacterToysCollectionSummaryResponse represents the raw CN API response for CharacterToysCollectionSummary.
type CNCharacterToysCollectionSummary BNetCharacterToysCollectionSummary

// ToBNet converts the CN response to the unified BNetCharacterToysCollectionSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterToysCollectionSummary) ToBNet() any {
	return r
}
