

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterCollections

type CharacterDecorCollectionSummaryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	DecorCollected []struct {
		Decor struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"decor"`
		Quantity int `json:"quantity,omitzero"`
	} `json:"decor_collected"`
}





// CharacterDecorCollectionSummary represents the raw CN API response for CharacterDecorCollectionSummary.
type CNCharacterDecorCollectionSummaryModel CharacterDecorCollectionSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterDecorCollectionSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterDecorCollectionSummaryModel) ToBNet() any {
	return r
}
