

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterCollections

type CharacterTransmogCollectionSummaryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	AppearanceSets []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"appearance_sets"`
	Slots []struct {
		Appearances []struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
		} `json:"appearances"`
		Slot struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"slot"`
	} `json:"slots"`
}





// CharacterTransmogCollectionSummary represents the raw CN API response for CharacterTransmogCollectionSummary.
type CNCharacterTransmogCollectionSummaryModel CharacterTransmogCollectionSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterTransmogCollectionSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterTransmogCollectionSummaryModel) ToBNet() any {
	return r
}
