package wow_CharacterCollections

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterTransmogCollectionSummaryResponse is the unified BNet representation for CharacterTransmogCollectionSummary.
type BNetCharacterTransmogCollectionSummary struct{}

// CharacterTransmogCollectionSummaryResponse represents the raw CN API response for CharacterTransmogCollectionSummary.
type CNCharacterTransmogCollectionSummary BNetCharacterTransmogCollectionSummary

// ToBNet converts the CN response to the unified BNetCharacterTransmogCollectionSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterTransmogCollectionSummary) ToBNet() any {
	return r
}
