

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterAchievements

type CharacterAchievementsSummaryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Achievements []struct {
		Achievement struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"achievement"`
		CompletedTimestamp int `json:"completed_timestamp,omitempty,omitzero"`
		Criteria           *struct {
			Amount        int `json:"amount,omitempty"`
			ChildCriteria []struct {
				Amount        int `json:"amount,omitempty"`
				ChildCriteria []struct {
					Amount        int `json:"amount,omitempty"`
					ChildCriteria []struct {
						Amount      int  `json:"amount,omitempty,omitzero"`
						ID          int  `json:"id,omitzero"`
						IsCompleted bool `json:"is_completed"`
					} `json:"child_criteria,omitempty"`
					ID          int  `json:"id,omitzero"`
					IsCompleted bool `json:"is_completed"`
				} `json:"child_criteria,omitempty"`
				ID          int  `json:"id,omitzero"`
				IsCompleted bool `json:"is_completed"`
			} `json:"child_criteria,omitempty"`
			ID          int  `json:"id,omitzero"`
			IsCompleted bool `json:"is_completed"`
		} `json:"criteria,omitempty,omitzero"`
		ID int `json:"id,omitzero"`
	} `json:"achievements"`
	CategoryProgress []struct {
		Category struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"category"`
		Points   int `json:"points"`
		Quantity int `json:"quantity,omitzero"`
	} `json:"category_progress"`
	Character struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name  string `json:"name,omitzero"`
		Realm struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"realm"`
	} `json:"character"`
	RecentEvents []struct {
		Achievement struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"achievement"`
		Timestamp int `json:"timestamp,omitzero"`
	} `json:"recent_events"`
	Statistics struct {
		Href string `json:"href,omitzero"`
	} `json:"statistics"`
	TotalPoints   int `json:"total_points,omitzero"`
	TotalQuantity int `json:"total_quantity,omitzero"`
}





// CharacterAchievementsSummary represents the raw CN API response for CharacterAchievementsSummary.
type CNCharacterAchievementsSummaryModel CharacterAchievementsSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterAchievementsSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterAchievementsSummaryModel) ToBNet() any {
	return r
}
