package wow_CharacterAchievements

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterAchievementsSummaryResponse is the unified BNet representation for CharacterAchievementsSummary.
type BNetCharacterAchievementsSummary struct{}

// CharacterAchievementsSummaryResponse represents the raw CN API response for CharacterAchievementsSummary.
type CNCharacterAchievementsSummary BNetCharacterAchievementsSummary

// ToBNet converts the CN response to the unified BNetCharacterAchievementsSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterAchievementsSummary) ToBNet() any {
	return r
}
