package StarCraftII_Account

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPlayerResponse is the unified BNet representation for Player.
type BNetPlayer struct{}

// PlayerResponse represents the raw CN API response for Player.
type CNPlayer BNetPlayer

// ToBNet converts the CN response to the unified BNetPlayerResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayer) ToBNet() any {
	return r
}
