

package StarCraftII_Account

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PlayerModel is the unified BNet representation for Player.
type PlayerModel struct{}




// Player represents the raw CN API response for Player.
type CNPlayerModel PlayerModel

// ToBNet converts the CN  to the unified BNetPlayer.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayerModel) ToBNet() any {
	return r
}
