

package wowClassic_CharacterSpecializations

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CharacterSpecializationsSummaryModel is the unified BNet representation for CharacterSpecializationsSummary.
type CharacterSpecializationsSummaryModel struct{}




// CharacterSpecializationsSummary represents the raw CN API response for CharacterSpecializationsSummary.
type CNCharacterSpecializationsSummaryModel CharacterSpecializationsSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterSpecializationsSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterSpecializationsSummaryModel) ToBNet() any {
	return r
}
