

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package D3_D3Act

type GetActModel struct {
	Name   string `json:"name,omitzero"`
	Number int    `json:"number,omitzero"`
	Quests []struct {
		ID   int    `json:"id,omitzero"`
		Name string `json:"name,omitzero"`
		Slug string `json:"slug,omitzero"`
	} `json:"quests"`
	Slug string `json:"slug,omitzero"`
}





// GetAct represents the raw CN API response for GetAct.
type CNGetActModel GetActModel

// ToBNet converts the CN  to the unified BNetGetAct.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetActModel) ToBNet() any {
	return r
}
