package D3_D3Act

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGetActIndexResponse is the unified BNet representation for GetActIndex.
type BNetGetActIndex struct{}

// GetActIndexResponse represents the raw CN API response for GetActIndex.
type CNGetActIndex BNetGetActIndex

// ToBNet converts the CN response to the unified BNetGetActIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetActIndex) ToBNet() any {
	return r
}
