

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package D3_D3Act

type GetActIndexModel struct {
	Acts []struct {
		Name   string `json:"name,omitzero"`
		Number int    `json:"number,omitzero"`
		Quests []struct {
			ID   int    `json:"id,omitzero"`
			Name string `json:"name,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"quests"`
		Slug string `json:"slug,omitzero"`
	} `json:"acts"`
}





// GetActIndex represents the raw CN API response for GetActIndex.
type CNGetActIndexModel GetActIndexModel

// ToBNet converts the CN  to the unified BNetGetActIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetActIndexModel) ToBNet() any {
	return r
}
