package D3_D3Act

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGetActResponse is the unified BNet representation for GetAct.
type BNetGetAct struct{}

// GetActResponse represents the raw CN API response for GetAct.
type CNGetAct BNetGetAct

// ToBNet converts the CN response to the unified BNetGetActResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetAct) ToBNet() any {
	return r
}
