

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_PlayableSpecialization

type PlayableSpecializationModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	GenderDescription struct {
		Female string `json:"female,omitzero"`
		Male   string `json:"male,omitzero"`
	} `json:"gender_description"`
	HeroTalentTrees []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"hero_talent_trees"`
	ID    int `json:"id,omitzero"`
	Media struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	Name          string `json:"name,omitzero"`
	PlayableClass struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"playable_class"`
	PowerType struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"power_type"`
	PrimaryStatType struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"primary_stat_type"`
	PvpTalents []struct {
		SpellTooltip struct {
			CastTime    string `json:"cast_time,omitzero"`
			Cooldown    string `json:"cooldown,omitempty,omitzero"`
			Description string `json:"description,omitzero"`
			PowerCost   string `json:"power_cost,omitempty,omitzero"`
			Range       string `json:"range,omitempty,omitzero"`
		} `json:"spell_tooltip"`
		Talent struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"talent"`
	} `json:"pvp_talents"`
	Role struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"role"`
	SpecTalentTree struct {
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"spec_talent_tree"`
}





// PlayableSpecialization represents the raw CN API response for PlayableSpecialization.
type CNPlayableSpecializationModel PlayableSpecializationModel

// ToBNet converts the CN  to the unified BNetPlayableSpecialization.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableSpecializationModel) ToBNet() any {
	return r
}
