

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_PlayableSpecialization

type PlayableSpecializationMediaModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Assets []struct {
		FileDataID int    `json:"file_data_id,omitzero"`
		Key        string `json:"key,omitzero"`
		Value      string `json:"value,omitzero"`
	} `json:"assets"`
	ID int `json:"id,omitzero"`
}





// PlayableSpecializationMedia represents the raw CN API response for PlayableSpecializationMedia.
type CNPlayableSpecializationMediaModel PlayableSpecializationMediaModel

// ToBNet converts the CN  to the unified BNetPlayableSpecializationMedia.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableSpecializationMediaModel) ToBNet() any {
	return r
}
