package wow_PlayableSpecialization

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPlayableSpecializationResponse is the unified BNet representation for PlayableSpecialization.
type BNetPlayableSpecialization struct{}

// PlayableSpecializationResponse represents the raw CN API response for PlayableSpecialization.
type CNPlayableSpecialization BNetPlayableSpecialization

// ToBNet converts the CN response to the unified BNetPlayableSpecializationResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableSpecialization) ToBNet() any {
	return r
}
