package wow_PlayableSpecialization

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPlayableSpecializationMediaResponse is the unified BNet representation for PlayableSpecializationMedia.
type BNetPlayableSpecializationMedia struct{}

// PlayableSpecializationMediaResponse represents the raw CN API response for PlayableSpecializationMedia.
type CNPlayableSpecializationMedia BNetPlayableSpecializationMedia

// ToBNet converts the CN response to the unified BNetPlayableSpecializationMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableSpecializationMedia) ToBNet() any {
	return r
}
