package wow_PlayableSpecialization

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPlayableSpecializationsIndexResponse is the unified BNet representation for PlayableSpecializationsIndex.
type BNetPlayableSpecializationsIndex struct{}

// PlayableSpecializationsIndexResponse represents the raw CN API response for PlayableSpecializationsIndex.
type CNPlayableSpecializationsIndex BNetPlayableSpecializationsIndex

// ToBNet converts the CN response to the unified BNetPlayableSpecializationsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableSpecializationsIndex) ToBNet() any {
	return r
}
