package D3_D3Profile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGetApiHeroResponse is the unified BNet representation for GetApiHero.
type BNetGetApiHero struct{}

// GetApiHeroResponse represents the raw CN API response for GetApiHero.
type CNGetApiHero BNetGetApiHero

// ToBNet converts the CN response to the unified BNetGetApiHeroResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetApiHero) ToBNet() any {
	return r
}
