

package D3_D3Profile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// GetApiDetailedFollowerItemsModel is the unified BNet representation for GetApiDetailedFollowerItems.
type GetApiDetailedFollowerItemsModel struct{}




// GetApiDetailedFollowerItems represents the raw CN API response for GetApiDetailedFollowerItems.
type CNGetApiDetailedFollowerItemsModel GetApiDetailedFollowerItemsModel

// ToBNet converts the CN  to the unified BNetGetApiDetailedFollowerItems.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetApiDetailedFollowerItemsModel) ToBNet() any {
	return r
}
