package D3_D3Profile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGetApiDetailedHeroItemsResponse is the unified BNet representation for GetApiDetailedHeroItems.
type BNetGetApiDetailedHeroItems struct{}

// GetApiDetailedHeroItemsResponse represents the raw CN API response for GetApiDetailedHeroItems.
type CNGetApiDetailedHeroItems BNetGetApiDetailedHeroItems

// ToBNet converts the CN response to the unified BNetGetApiDetailedHeroItemsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetApiDetailedHeroItems) ToBNet() any {
	return r
}
