package D3_D3Profile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGetApiAccountResponse is the unified BNet representation for GetApiAccount.
type BNetGetApiAccount struct{}

// GetApiAccountResponse represents the raw CN API response for GetApiAccount.
type CNGetApiAccount BNetGetApiAccount

// ToBNet converts the CN response to the unified BNetGetApiAccountResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetApiAccount) ToBNet() any {
	return r
}
