package D3_D3Profile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGetApiDetailedFollowerItemsResponse is the unified BNet representation for GetApiDetailedFollowerItems.
type BNetGetApiDetailedFollowerItems struct{}

// GetApiDetailedFollowerItemsResponse represents the raw CN API response for GetApiDetailedFollowerItems.
type CNGetApiDetailedFollowerItems BNetGetApiDetailedFollowerItems

// ToBNet converts the CN response to the unified BNetGetApiDetailedFollowerItemsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetApiDetailedFollowerItems) ToBNet() any {
	return r
}
