

package D3_D3Profile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// GetApiAccountModel is the unified BNet representation for GetApiAccount.
type GetApiAccountModel struct{}




// GetApiAccount represents the raw CN API response for GetApiAccount.
type CNGetApiAccountModel GetApiAccountModel

// ToBNet converts the CN  to the unified BNetGetApiAccount.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetApiAccountModel) ToBNet() any {
	return r
}
