

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package D3_D3Follower

type GetFollowerModel struct {
	Name     string `json:"name,omitzero"`
	Portrait string `json:"portrait,omitzero"`
	RealName string `json:"realName,omitzero"`
	Skills   []struct {
		Description     string `json:"description,omitzero"`
		DescriptionHtml string `json:"descriptionHtml,omitzero"`
		Icon            string `json:"icon,omitzero"`
		Level           int    `json:"level,omitzero"`
		Name            string `json:"name,omitzero"`
		Slug            string `json:"slug,omitzero"`
		TooltipURL      string `json:"tooltipUrl,omitzero"`
	} `json:"skills"`
	Slug string `json:"slug,omitzero"`
}





// GetFollower represents the raw CN API response for GetFollower.
type CNGetFollowerModel GetFollowerModel

// ToBNet converts the CN  to the unified BNetGetFollower.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetFollowerModel) ToBNet() any {
	return r
}
