package wow_Quest

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetQuestCategoriesIndexResponse is the unified BNet representation for QuestCategoriesIndex.
type BNetQuestCategoriesIndex struct{}

// QuestCategoriesIndexResponse represents the raw CN API response for QuestCategoriesIndex.
type CNQuestCategoriesIndex BNetQuestCategoriesIndex

// ToBNet converts the CN response to the unified BNetQuestCategoriesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNQuestCategoriesIndex) ToBNet() any {
	return r
}
