

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Quest

type QuestModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Area struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"area"`
	Description  string `json:"description,omitzero"`
	ID           int    `json:"id,omitzero"`
	Requirements struct {
		Faction struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"faction"`
		MaxCharacterLevel int `json:"max_character_level,omitzero"`
		MinCharacterLevel int `json:"min_character_level,omitzero"`
	} `json:"requirements"`
	Rewards struct {
		Experience int `json:"experience,omitzero"`
		Money      struct {
			Units struct {
				Copper int `json:"copper"`
				Gold   int `json:"gold,omitzero"`
				Silver int `json:"silver,omitzero"`
			} `json:"units"`
			Value int `json:"value,omitzero"`
		} `json:"money"`
		Reputations []struct {
			Reward struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"reward"`
			Value int `json:"value,omitzero"`
		} `json:"reputations"`
	} `json:"rewards"`
	Title string `json:"title,omitzero"`
}





// Quest represents the raw CN API response for Quest.
type CNQuestModel QuestModel

// ToBNet converts the CN  to the unified BNetQuest.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNQuestModel) ToBNet() any {
	return r
}
