

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Quest

type QuestCategoryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Category string `json:"category,omitzero"`
	ID       int    `json:"id,omitzero"`
	Quests   []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"quests"`
}





// QuestCategory represents the raw CN API response for QuestCategory.
type CNQuestCategoryModel QuestCategoryModel

// ToBNet converts the CN  to the unified BNetQuestCategory.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNQuestCategoryModel) ToBNet() any {
	return r
}
