package wow_Quest

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetQuestCategoryResponse is the unified BNet representation for QuestCategory.
type BNetQuestCategory struct{}

// QuestCategoryResponse represents the raw CN API response for QuestCategory.
type CNQuestCategory BNetQuestCategory

// ToBNet converts the CN response to the unified BNetQuestCategoryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNQuestCategory) ToBNet() any {
	return r
}
