package wow_Quest

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetQuestResponse is the unified BNet representation for Quest.
type BNetQuest struct{}

// QuestResponse represents the raw CN API response for Quest.
type CNQuest BNetQuest

// ToBNet converts the CN response to the unified BNetQuestResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNQuest) ToBNet() any {
	return r
}
