package wow_Quest

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetQuestsIndexResponse is the unified BNet representation for QuestsIndex.
type BNetQuestsIndex struct{}

// QuestsIndexResponse represents the raw CN API response for QuestsIndex.
type CNQuestsIndex BNetQuestsIndex

// ToBNet converts the CN response to the unified BNetQuestsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNQuestsIndex) ToBNet() any {
	return r
}
