

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Quest

type QuestTypeModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ID     int `json:"id,omitzero"`
	Quests []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"quests"`
	Type string `json:"type,omitzero"`
}





// QuestType represents the raw CN API response for QuestType.
type CNQuestTypeModel QuestTypeModel

// ToBNet converts the CN  to the unified BNetQuestType.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNQuestTypeModel) ToBNet() any {
	return r
}
