

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Quest

type QuestsIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Areas struct {
		Href string `json:"href,omitzero"`
	} `json:"areas"`
	Categories struct {
		Href string `json:"href,omitzero"`
	} `json:"categories"`
	Types struct {
		Href string `json:"href,omitzero"`
	} `json:"types"`
}





// QuestsIndex represents the raw CN API response for QuestsIndex.
type CNQuestsIndexModel QuestsIndexModel

// ToBNet converts the CN  to the unified BNetQuestsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNQuestsIndexModel) ToBNet() any {
	return r
}
