package wow_Quest

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetQuestTypesIndexResponse is the unified BNet representation for QuestTypesIndex.
type BNetQuestTypesIndex struct{}

// QuestTypesIndexResponse represents the raw CN API response for QuestTypesIndex.
type CNQuestTypesIndex BNetQuestTypesIndex

// ToBNet converts the CN response to the unified BNetQuestTypesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNQuestTypesIndex) ToBNet() any {
	return r
}
