

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Quest

type QuestAreaModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Area   string `json:"area,omitzero"`
	ID     int    `json:"id,omitzero"`
	Quests []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"quests"`
}





// QuestArea represents the raw CN API response for QuestArea.
type CNQuestAreaModel QuestAreaModel

// ToBNet converts the CN  to the unified BNetQuestArea.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNQuestAreaModel) ToBNet() any {
	return r
}
