

package wowClassic_CharacterPvP

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CharacterPvPBracketStatisticsModel is the unified BNet representation for CharacterPvPBracketStatistics.
type CharacterPvPBracketStatisticsModel struct{}




// CharacterPvPBracketStatistics represents the raw CN API response for CharacterPvPBracketStatistics.
type CNCharacterPvPBracketStatisticsModel CharacterPvPBracketStatisticsModel

// ToBNet converts the CN  to the unified BNetCharacterPvPBracketStatistics.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterPvPBracketStatisticsModel) ToBNet() any {
	return r
}
