

package wowClassic_CharacterPvP

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CharacterPvPSummaryModel is the unified BNet representation for CharacterPvPSummary.
type CharacterPvPSummaryModel struct{}




// CharacterPvPSummary represents the raw CN API response for CharacterPvPSummary.
type CNCharacterPvPSummaryModel CharacterPvPSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterPvPSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterPvPSummaryModel) ToBNet() any {
	return r
}
