

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package HeartStone_Decks

type GetdeckbycardlistModel struct {
	CardCount int `json:"cardCount,omitzero"`
	Cards     []struct {
		Armor                     int    `json:"armor,omitempty,omitzero"`
		ArtistName                string `json:"artistName,omitzero"`
		Attack                    int    `json:"attack,omitempty,omitzero"`
		BannedFromSideboard       int    `json:"bannedFromSideboard,omitempty,omitzero"`
		CardSetID                 int    `json:"cardSetId,omitzero"`
		CardTypeID                int    `json:"cardTypeId,omitzero"`
		ChildIDs                  []int  `json:"childIds,omitempty"`
		ClassID                   int    `json:"classId,omitzero"`
		Collectible               int    `json:"collectible,omitzero"`
		CopyOfCardID              []int  `json:"copyOfCardId,omitempty"`
		CropImage                 string `json:"cropImage,omitzero"`
		FlavorText                string `json:"flavorText,omitzero"`
		Health                    int    `json:"health,omitempty,omitzero"`
		ID                        int    `json:"id,omitzero"`
		Image                     string `json:"image,omitzero"`
		ImageGold                 string `json:"imageGold"`
		IsZilliaxCosmeticModule   bool   `json:"isZilliaxCosmeticModule"`
		IsZilliaxFunctionalModule bool   `json:"isZilliaxFunctionalModule"`
		KeywordIDs                []int  `json:"keywordIds,omitempty"`
		ManaCost                  int    `json:"manaCost"`
		MinionTypeID              int    `json:"minionTypeId,omitempty,omitzero"`
		MultiClassIDs             []any  `json:"multiClassIds"`
		Name                      string `json:"name,omitzero"`
		RarityID                  int    `json:"rarityId,omitzero"`
		Slug                      string `json:"slug,omitzero"`
		SpellSchoolID             int    `json:"spellSchoolId,omitempty,omitzero"`
		Text                      string `json:"text,omitzero"`
	} `json:"cards"`
	Class struct {
		ID   int    `json:"id,omitzero"`
		Name string `json:"name,omitzero"`
		Slug string `json:"slug,omitzero"`
	} `json:"class"`
	DeckCode string `json:"deckCode,omitzero"`
	Format   string `json:"format,omitzero"`
	Hero     struct {
		ArtistName                string `json:"artistName,omitzero"`
		CardSetID                 int    `json:"cardSetId,omitzero"`
		CardTypeID                int    `json:"cardTypeId,omitzero"`
		ChildIDs                  []int  `json:"childIds"`
		ClassID                   int    `json:"classId,omitzero"`
		Collectible               int    `json:"collectible,omitzero"`
		CropImage                 string `json:"cropImage,omitzero"`
		FlavorText                string `json:"flavorText"`
		Health                    int    `json:"health,omitzero"`
		ID                        int    `json:"id,omitzero"`
		Image                     string `json:"image,omitzero"`
		ImageGold                 string `json:"imageGold"`
		IsZilliaxCosmeticModule   bool   `json:"isZilliaxCosmeticModule"`
		IsZilliaxFunctionalModule bool   `json:"isZilliaxFunctionalModule"`
		ManaCost                  int    `json:"manaCost"`
		MultiClassIDs             []any  `json:"multiClassIds"`
		Name                      string `json:"name,omitzero"`
		RarityID                  int    `json:"rarityId,omitzero"`
		Slug                      string `json:"slug,omitzero"`
		Text                      string `json:"text"`
	} `json:"hero"`
	HeroPower struct {
		ArtistName                any    `json:"artistName"`
		CardSetID                 int    `json:"cardSetId,omitzero"`
		CardTypeID                int    `json:"cardTypeId,omitzero"`
		ClassID                   int    `json:"classId,omitzero"`
		Collectible               int    `json:"collectible"`
		CopyOfCardID              []int  `json:"copyOfCardId"`
		CropImage                 string `json:"cropImage,omitzero"`
		FlavorText                string `json:"flavorText"`
		ID                        int    `json:"id,omitzero"`
		Image                     string `json:"image,omitzero"`
		ImageGold                 string `json:"imageGold"`
		IsZilliaxCosmeticModule   bool   `json:"isZilliaxCosmeticModule"`
		IsZilliaxFunctionalModule bool   `json:"isZilliaxFunctionalModule"`
		ManaCost                  int    `json:"manaCost,omitzero"`
		MultiClassIDs             []any  `json:"multiClassIds"`
		Name                      string `json:"name,omitzero"`
		ParentID                  int    `json:"parentId,omitzero"`
		RarityID                  int    `json:"rarityId,omitzero"`
		Slug                      string `json:"slug,omitzero"`
		Text                      string `json:"text,omitzero"`
	} `json:"heroPower"`
	Version int `json:"version,omitzero"`
}





// Getdeckbycardlist represents the raw CN API response for Getdeckbycardlist.
type CNGetdeckbycardlistModel GetdeckbycardlistModel

// ToBNet converts the CN  to the unified BNetGetdeckbycardlist.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetdeckbycardlistModel) ToBNet() any {
	return r
}
