package HeartStone_Decks

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGetdeckbycodeResponse is the unified BNet representation for Getdeckbycode.
type BNetGetdeckbycode struct{}

// GetdeckbycodeResponse represents the raw CN API response for Getdeckbycode.
type CNGetdeckbycode BNetGetdeckbycode

// ToBNet converts the CN response to the unified BNetGetdeckbycodeResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetdeckbycode) ToBNet() any {
	return r
}
