

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package D3_D3CharacterClassandSkill

type GetApiSkillModel struct {
	Runes []struct {
		Description     string `json:"description,omitzero"`
		DescriptionHtml string `json:"descriptionHtml,omitzero"`
		Level           int    `json:"level,omitzero"`
		Name            string `json:"name,omitzero"`
		Slug            string `json:"slug,omitzero"`
		Type            string `json:"type,omitzero"`
	} `json:"runes"`
	Skill struct {
		Description     string `json:"description,omitzero"`
		DescriptionHtml string `json:"descriptionHtml,omitzero"`
		Icon            string `json:"icon,omitzero"`
		Level           int    `json:"level,omitzero"`
		Name            string `json:"name,omitzero"`
		Slug            string `json:"slug,omitzero"`
		TooltipURL      string `json:"tooltipUrl,omitzero"`
	} `json:"skill"`
}





// GetApiSkill represents the raw CN API response for GetApiSkill.
type CNGetApiSkillModel GetApiSkillModel

// ToBNet converts the CN  to the unified BNetGetApiSkill.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetApiSkillModel) ToBNet() any {
	return r
}
