package D3_D3CharacterClassandSkill

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGetApiSkillResponse is the unified BNet representation for GetApiSkill.
type BNetGetApiSkill struct{}

// GetApiSkillResponse represents the raw CN API response for GetApiSkill.
type CNGetApiSkill BNetGetApiSkill

// ToBNet converts the CN response to the unified BNetGetApiSkillResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetApiSkill) ToBNet() any {
	return r
}
