package wow_CharacterReputations

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterReputationsSummaryResponse is the unified BNet representation for CharacterReputationsSummary.
type BNetCharacterReputationsSummary struct{}

// CharacterReputationsSummaryResponse represents the raw CN API response for CharacterReputationsSummary.
type CNCharacterReputationsSummary BNetCharacterReputationsSummary

// ToBNet converts the CN response to the unified BNetCharacterReputationsSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterReputationsSummary) ToBNet() any {
	return r
}
