

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterReputations

type CharacterReputationsSummaryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Character struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name  string `json:"name,omitzero"`
		Realm struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"realm"`
	} `json:"character"`
	Reputations []struct {
		Faction struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"faction"`
		Paragon *struct {
			Max   int `json:"max,omitzero"`
			Raw   int `json:"raw,omitzero"`
			Value int `json:"value,omitzero"`
		} `json:"paragon,omitempty,omitzero"`
		Standing struct {
			Max         int    `json:"max"`
			Name        string `json:"name,omitzero"`
			Raw         int    `json:"raw"`
			RenownLevel int    `json:"renown_level,omitempty,omitzero"`
			Tier        int    `json:"tier,omitempty"`
			Value       int    `json:"value"`
		} `json:"standing"`
	} `json:"reputations"`
}





// CharacterReputationsSummary represents the raw CN API response for CharacterReputationsSummary.
type CNCharacterReputationsSummaryModel CharacterReputationsSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterReputationsSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterReputationsSummaryModel) ToBNet() any {
	return r
}
