

package wowClassic_CharacterAchievements

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CharacterAchievementsSummaryModel is the unified BNet representation for CharacterAchievementsSummary.
type CharacterAchievementsSummaryModel struct{}




// CharacterAchievementsSummary represents the raw CN API response for CharacterAchievementsSummary.
type CNCharacterAchievementsSummaryModel CharacterAchievementsSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterAchievementsSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterAchievementsSummaryModel) ToBNet() any {
	return r
}
