

package wowClassic_CharacterAchievements

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CharacterAchievementStatisticsModel is the unified BNet representation for CharacterAchievementStatistics.
type CharacterAchievementStatisticsModel struct{}




// CharacterAchievementStatistics represents the raw CN API response for CharacterAchievementStatistics.
type CNCharacterAchievementStatisticsModel CharacterAchievementStatisticsModel

// ToBNet converts the CN  to the unified BNetCharacterAchievementStatistics.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterAchievementStatisticsModel) ToBNet() any {
	return r
}
