

package wowClassic_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// AccountProfileSummaryModel is the unified BNet representation for AccountProfileSummary.
type AccountProfileSummaryModel struct{}




// AccountProfileSummary represents the raw CN API response for AccountProfileSummary.
type CNAccountProfileSummaryModel AccountProfileSummaryModel

// ToBNet converts the CN  to the unified BNetAccountProfileSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountProfileSummaryModel) ToBNet() any {
	return r
}
