FROM golang:1.26rc1-alpine
# Install additional OS packages if needed.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# Set the working directory
WORKDIR /workspace
