package wowClassic_PowerType

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPowerTypesIndexResponse is the unified BNet representation for PowerTypesIndex.
type BNetPowerTypesIndex struct{}

// PowerTypesIndexResponse represents the raw CN API response for PowerTypesIndex.
type CNPowerTypesIndex BNetPowerTypesIndex

// ToBNet converts the CN response to the unified BNetPowerTypesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPowerTypesIndex) ToBNet() any {
	return r
}
