

package wowClassic_PowerType

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PowerTypeModel is the unified BNet representation for PowerType.
type PowerTypeModel struct{}




// PowerType represents the raw CN API response for PowerType.
type CNPowerTypeModel PowerTypeModel

// ToBNet converts the CN  to the unified BNetPowerType.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPowerTypeModel) ToBNet() any {
	return r
}
