

package wowClassic_PowerType

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PowerTypesIndexModel is the unified BNet representation for PowerTypesIndex.
type PowerTypesIndexModel struct{}




// PowerTypesIndex represents the raw CN API response for PowerTypesIndex.
type CNPowerTypesIndexModel PowerTypesIndexModel

// ToBNet converts the CN  to the unified BNetPowerTypesIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPowerTypesIndexModel) ToBNet() any {
	return r
}
