package wow_Covenant

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetConduitResponse is the unified BNet representation for Conduit.
type BNetConduit struct{}

// ConduitResponse represents the raw CN API response for Conduit.
type CNConduit BNetConduit

// ToBNet converts the CN response to the unified BNetConduitResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNConduit) ToBNet() any {
	return r
}
