package wow_Covenant

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetConduitIndexResponse is the unified BNet representation for ConduitIndex.
type BNetConduitIndex struct{}

// ConduitIndexResponse represents the raw CN API response for ConduitIndex.
type CNConduitIndex BNetConduitIndex

// ToBNet converts the CN response to the unified BNetConduitIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNConduitIndex) ToBNet() any {
	return r
}
