package wow_Covenant

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCovenantResponse is the unified BNet representation for Covenant.
type BNetCovenant struct{}

// CovenantResponse represents the raw CN API response for Covenant.
type CNCovenant BNetCovenant

// ToBNet converts the CN response to the unified BNetCovenantResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCovenant) ToBNet() any {
	return r
}
