package wow_Covenant

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCovenantIndexResponse is the unified BNet representation for CovenantIndex.
type BNetCovenantIndex struct{}

// CovenantIndexResponse represents the raw CN API response for CovenantIndex.
type CNCovenantIndex BNetCovenantIndex

// ToBNet converts the CN response to the unified BNetCovenantIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCovenantIndex) ToBNet() any {
	return r
}
