

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:31:45+08:00
package wow_Covenant

type CovenantModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ClassAbilities []struct {
		ID            int `json:"id,omitzero"`
		PlayableClass struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"playable_class"`
		SpellTooltip struct {
			CastTime    string  `json:"cast_time,omitzero"`
			Cooldown    string  `json:"cooldown,omitempty,omitzero"`
			Description string  `json:"description,omitzero"`
			PowerCost   *string `json:"power_cost"`
			Range       string  `json:"range,omitempty,omitzero"`
			Spell       struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"spell"`
		} `json:"spell_tooltip"`
	} `json:"class_abilities"`
	Description string `json:"description,omitzero"`
	ID          int    `json:"id,omitzero"`
	Media       struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	Name          string `json:"name,omitzero"`
	RenownRewards []struct {
		Level  int `json:"level,omitzero"`
		Reward struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"reward"`
	} `json:"renown_rewards"`
	SignatureAbility struct {
		ID           int `json:"id,omitzero"`
		SpellTooltip struct {
			CastTime    string `json:"cast_time,omitzero"`
			Cooldown    string `json:"cooldown,omitzero"`
			Description string `json:"description,omitzero"`
			Spell       struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"spell"`
		} `json:"spell_tooltip"`
	} `json:"signature_ability"`
	Soulbinds []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"soulbinds"`
}





// Covenant represents the raw CN API response for Covenant.
type CNCovenantModel CovenantModel

// ToBNet converts the CN  to the unified BNetCovenant.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCovenantModel) ToBNet() any {
	return r
}
