package wow_Covenant

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCovenantIndexResponse is the unified BNet representation for CovenantIndex.
type BNetCovenantIndex struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Covenants []struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"covenants"`
}

// CovenantIndexResponse represents the raw CN API response for CovenantIndex.
type CNCovenantIndex BNetCovenantIndex

// ToBNet converts the CN response to the unified BNetCovenantIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCovenantIndex) ToBNet() any {
	return r
}
