package wow_Covenant

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetSoulbindIndexResponse is the unified BNet representation for SoulbindIndex.
type BNetSoulbindIndex struct{}

// SoulbindIndexResponse represents the raw CN API response for SoulbindIndex.
type CNSoulbindIndex BNetSoulbindIndex

// ToBNet converts the CN response to the unified BNetSoulbindIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSoulbindIndex) ToBNet() any {
	return r
}
