package wow_Covenant

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetSoulbindIndexResponse is the unified BNet representation for SoulbindIndex.
type BNetSoulbindIndex struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Soulbinds []struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"soulbinds"`
}

// SoulbindIndexResponse represents the raw CN API response for SoulbindIndex.
type CNSoulbindIndex BNetSoulbindIndex

// ToBNet converts the CN response to the unified BNetSoulbindIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSoulbindIndex) ToBNet() any {
	return r
}
