package wow_Covenant

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetSoulbindResponse is the unified BNet representation for Soulbind.
type BNetSoulbind struct{}

// SoulbindResponse represents the raw CN API response for Soulbind.
type CNSoulbind BNetSoulbind

// ToBNet converts the CN response to the unified BNetSoulbindResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSoulbind) ToBNet() any {
	return r
}
