

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:31:45+08:00
package wow_Covenant

type SoulbindModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Covenant struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"covenant"`
	Creature struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"creature"`
	Follower struct {
		ID   int    `json:"id,omitzero"`
		Name string `json:"name,omitzero"`
	} `json:"follower"`
	ID         int    `json:"id,omitzero"`
	Name       string `json:"name,omitzero"`
	TalentTree struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"talent_tree"`
}





// Soulbind represents the raw CN API response for Soulbind.
type CNSoulbindModel SoulbindModel

// ToBNet converts the CN  to the unified BNetSoulbind.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSoulbindModel) ToBNet() any {
	return r
}
