package wow_Covenant

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetSoulbindResponse is the unified BNet representation for Soulbind.
type BNetSoulbind struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Id       int    `json:"id"`
	Name     string `json:"name"`
	Covenant struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"covenant"`
	Creature struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"creature"`
	Follower struct {
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"follower"`
	TalentTree struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		Id   int    `json:"id"`
	} `json:"talent_tree"`
}

// SoulbindResponse represents the raw CN API response for Soulbind.
type CNSoulbind BNetSoulbind

// ToBNet converts the CN response to the unified BNetSoulbindResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSoulbind) ToBNet() any {
	return r
}
