

package wowClassic_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CreatureFamiliesIndexModel is the unified BNet representation for CreatureFamiliesIndex.
type CreatureFamiliesIndexModel struct{}




// CreatureFamiliesIndex represents the raw CN API response for CreatureFamiliesIndex.
type CNCreatureFamiliesIndexModel CreatureFamiliesIndexModel

// ToBNet converts the CN  to the unified BNetCreatureFamiliesIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureFamiliesIndexModel) ToBNet() any {
	return r
}
