

package wowClassic_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CreatureTypeModel is the unified BNet representation for CreatureType.
type CreatureTypeModel struct{}




// CreatureType represents the raw CN API response for CreatureType.
type CNCreatureTypeModel CreatureTypeModel

// ToBNet converts the CN  to the unified BNetCreatureType.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureTypeModel) ToBNet() any {
	return r
}
