

package wowClassic_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CreatureFamilyMediaModel is the unified BNet representation for CreatureFamilyMedia.
type CreatureFamilyMediaModel struct{}




// CreatureFamilyMedia represents the raw CN API response for CreatureFamilyMedia.
type CNCreatureFamilyMediaModel CreatureFamilyMediaModel

// ToBNet converts the CN  to the unified BNetCreatureFamilyMedia.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureFamilyMediaModel) ToBNet() any {
	return r
}
