

package wowClassic_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CreatureModel is the unified BNet representation for Creature.
type CreatureModel struct{}




// Creature represents the raw CN API response for Creature.
type CNCreatureModel CreatureModel

// ToBNet converts the CN  to the unified BNetCreature.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureModel) ToBNet() any {
	return r
}
