package wowClassic_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCreatureTypesIndexResponse is the unified BNet representation for CreatureTypesIndex.
type BNetCreatureTypesIndex struct{}

// CreatureTypesIndexResponse represents the raw CN API response for CreatureTypesIndex.
type CNCreatureTypesIndex BNetCreatureTypesIndex

// ToBNet converts the CN response to the unified BNetCreatureTypesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureTypesIndex) ToBNet() any {
	return r
}
