

package wowClassic_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CreatureDisplayMediaModel is the unified BNet representation for CreatureDisplayMedia.
type CreatureDisplayMediaModel struct{}




// CreatureDisplayMedia represents the raw CN API response for CreatureDisplayMedia.
type CNCreatureDisplayMediaModel CreatureDisplayMediaModel

// ToBNet converts the CN  to the unified BNetCreatureDisplayMedia.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureDisplayMediaModel) ToBNet() any {
	return r
}
