package wowClassic_Creature

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCreatureFamiliesIndexResponse is the unified BNet representation for CreatureFamiliesIndex.
type BNetCreatureFamiliesIndex struct{}

// CreatureFamiliesIndexResponse represents the raw CN API response for CreatureFamiliesIndex.
type CNCreatureFamiliesIndex BNetCreatureFamiliesIndex

// ToBNet converts the CN response to the unified BNetCreatureFamiliesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCreatureFamiliesIndex) ToBNet() any {
	return r
}
