package wowClassic_CharacterAppearance

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterAppearanceSummaryResponse is the unified BNet representation for CharacterAppearanceSummary.
type BNetCharacterAppearanceSummary struct{}

// CharacterAppearanceSummaryResponse represents the raw CN API response for CharacterAppearanceSummary.
type CNCharacterAppearanceSummary BNetCharacterAppearanceSummary

// ToBNet converts the CN response to the unified BNetCharacterAppearanceSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterAppearanceSummary) ToBNet() any {
	return r
}
