

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_MediaSearch

type MediaSearchModel struct {
	MaxPageSize       int  `json:"maxPageSize,omitzero"`
	Page              int  `json:"page,omitzero"`
	PageCount         int  `json:"pageCount,omitzero"`
	PageSize          int  `json:"pageSize,omitzero"`
	ResultCountCapped bool `json:"resultCountCapped,omitzero"`
	Results           []struct {
		Data struct {
			Assets []struct {
				FileDataID int    `json:"file_data_id,omitzero"`
				Key        string `json:"key,omitzero"`
				Value      string `json:"value,omitzero"`
			} `json:"assets"`
			ID int `json:"id,omitzero"`
		} `json:"data"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"results"`
}





// MediaSearch represents the raw CN API response for MediaSearch.
type CNMediaSearchModel MediaSearchModel

// ToBNet converts the CN  to the unified BNetMediaSearch.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMediaSearchModel) ToBNet() any {
	return r
}
