

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:31:45+08:00
package wow_ConnectedRealm

type ConnectedRealmsIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ConnectedRealms []struct {
		Href string `json:"href,omitzero"`
	} `json:"connected_realms"`
}





// ConnectedRealmsIndex represents the raw CN API response for ConnectedRealmsIndex.
type CNConnectedRealmsIndexModel ConnectedRealmsIndexModel

// ToBNet converts the CN  to the unified BNetConnectedRealmsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNConnectedRealmsIndexModel) ToBNet() any {
	return r
}
