package wow_ConnectedRealm

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetConnectedRealmResponse is the unified BNet representation for ConnectedRealm.
type BNetConnectedRealm struct{}

// ConnectedRealmResponse represents the raw CN API response for ConnectedRealm.
type CNConnectedRealm BNetConnectedRealm

// ToBNet converts the CN response to the unified BNetConnectedRealmResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNConnectedRealm) ToBNet() any {
	return r
}
