

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:31:45+08:00
package wow_ConnectedRealm

type ConnectedRealmSearchModel struct {
	MaxPageSize int   `json:"maxPageSize,omitzero"`
	Page        int   `json:"page,omitzero"`
	PageCount   int   `json:"pageCount"`
	PageSize    int   `json:"pageSize"`
	Results     []any `json:"results"`
}





// ConnectedRealmSearch represents the raw CN API response for ConnectedRealmSearch.
type CNConnectedRealmSearchModel ConnectedRealmSearchModel

// ToBNet converts the CN  to the unified BNetConnectedRealmSearch.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNConnectedRealmSearchModel) ToBNet() any {
	return r
}
