

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:31:45+08:00
package wow_ConnectedRealm

type ConnectedRealmModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Auctions struct {
		Href string `json:"href,omitzero"`
	} `json:"auctions"`
	HasQueue           bool `json:"has_queue"`
	ID                 int  `json:"id,omitzero"`
	MythicLeaderboards struct {
		Href string `json:"href,omitzero"`
	} `json:"mythic_leaderboards"`
	Population struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"population"`
	Realms []struct {
		Category       string `json:"category,omitzero"`
		ConnectedRealm struct {
			Href string `json:"href,omitzero"`
		} `json:"connected_realm"`
		ID           int    `json:"id,omitzero"`
		IsTournament bool   `json:"is_tournament"`
		Locale       string `json:"locale,omitzero"`
		Name         string `json:"name,omitzero"`
		Region       struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"region"`
		Slug     string `json:"slug,omitzero"`
		Timezone string `json:"timezone,omitzero"`
		Type     struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"type"`
	} `json:"realms"`
	Status struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"status"`
}





// ConnectedRealm represents the raw CN API response for ConnectedRealm.
type CNConnectedRealmModel ConnectedRealmModel

// ToBNet converts the CN  to the unified BNetConnectedRealm.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNConnectedRealmModel) ToBNet() any {
	return r
}
