package wow_ConnectedRealm

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetConnectedRealmsIndexResponse is the unified BNet representation for ConnectedRealmsIndex.
type BNetConnectedRealmsIndex struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	ConnectedRealms []struct {
		Href string `json:"href"`
	} `json:"connected_realms"`
}

// ConnectedRealmsIndexResponse represents the raw CN API response for ConnectedRealmsIndex.
type CNConnectedRealmsIndex BNetConnectedRealmsIndex

// ToBNet converts the CN response to the unified BNetConnectedRealmsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNConnectedRealmsIndex) ToBNet() any {
	return r
}
