

package wow_CharacterHouse

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CharacterHouseSummaryModel is the unified BNet representation for CharacterHouseSummary.
type CharacterHouseSummaryModel struct{}




// CharacterHouseSummary represents the raw CN API response for CharacterHouseSummary.
type CNCharacterHouseSummaryModel CharacterHouseSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterHouseSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterHouseSummaryModel) ToBNet() any {
	return r
}
