package wow_CharacterHouse

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterHouseSummaryResponse is the unified BNet representation for CharacterHouseSummary.
type BNetCharacterHouseSummary struct{}

// CharacterHouseSummaryResponse represents the raw CN API response for CharacterHouseSummary.
type CNCharacterHouseSummary BNetCharacterHouseSummary

// ToBNet converts the CN response to the unified BNetCharacterHouseSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterHouseSummary) ToBNet() any {
	return r
}
