

package StarCraftII_Ladder

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// GrandmasterLeaderboardModel is the unified BNet representation for GrandmasterLeaderboard.
type GrandmasterLeaderboardModel struct{}




// GrandmasterLeaderboard represents the raw CN API response for GrandmasterLeaderboard.
type CNGrandmasterLeaderboardModel GrandmasterLeaderboardModel

// ToBNet converts the CN  to the unified BNetGrandmasterLeaderboard.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGrandmasterLeaderboardModel) ToBNet() any {
	return r
}
