package wowClassic_ConnectedRealm

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetConnectedRealmsSearchResponse is the unified BNet representation for ConnectedRealmsSearch.
type BNetConnectedRealmsSearch struct{}

// ConnectedRealmsSearchResponse represents the raw CN API response for ConnectedRealmsSearch.
type CNConnectedRealmsSearch BNetConnectedRealmsSearch

// ToBNet converts the CN response to the unified BNetConnectedRealmsSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNConnectedRealmsSearch) ToBNet() any {
	return r
}
