

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wowClassic_ConnectedRealm

type ConnectedRealmsSearchModel struct {
	MaxPageSize int   `json:"maxPageSize,omitzero"`
	Page        int   `json:"page,omitzero"`
	PageCount   int   `json:"pageCount"`
	PageSize    int   `json:"pageSize"`
	Results     []any `json:"results"`
}





// ConnectedRealmsSearch represents the raw CN API response for ConnectedRealmsSearch.
type CNConnectedRealmsSearchModel ConnectedRealmsSearchModel

// ToBNet converts the CN  to the unified BNetConnectedRealmsSearch.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNConnectedRealmsSearchModel) ToBNet() any {
	return r
}
