

package wowClassic_ConnectedRealm

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// ConnectedRealmModel is the unified BNet representation for ConnectedRealm.
type ConnectedRealmModel struct{}




// ConnectedRealm represents the raw CN API response for ConnectedRealm.
type CNConnectedRealmModel ConnectedRealmModel

// ToBNet converts the CN  to the unified BNetConnectedRealm.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNConnectedRealmModel) ToBNet() any {
	return r
}
