

package wowClassic_PlayableClass

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PlayableClassesIndexModel is the unified BNet representation for PlayableClassesIndex.
type PlayableClassesIndexModel struct{}




// PlayableClassesIndex represents the raw CN API response for PlayableClassesIndex.
type CNPlayableClassesIndexModel PlayableClassesIndexModel

// ToBNet converts the CN  to the unified BNetPlayableClassesIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableClassesIndexModel) ToBNet() any {
	return r
}
