

package wowClassic_PlayableClass

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PlayableClassModel is the unified BNet representation for PlayableClass.
type PlayableClassModel struct{}




// PlayableClass represents the raw CN API response for PlayableClass.
type CNPlayableClassModel PlayableClassModel

// ToBNet converts the CN  to the unified BNetPlayableClass.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableClassModel) ToBNet() any {
	return r
}
