

package wowClassic_PlayableClass

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// PlayableClassMediaModel is the unified BNet representation for PlayableClassMedia.
type PlayableClassMediaModel struct{}




// PlayableClassMedia represents the raw CN API response for PlayableClassMedia.
type CNPlayableClassMediaModel PlayableClassMediaModel

// ToBNet converts the CN  to the unified BNetPlayableClassMedia.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableClassMediaModel) ToBNet() any {
	return r
}
