

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Region

type RegionsIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Regions []struct {
		Href string `json:"href,omitzero"`
	} `json:"regions"`
}





// RegionsIndex represents the raw CN API response for RegionsIndex.
type CNRegionsIndexModel RegionsIndexModel

// ToBNet converts the CN  to the unified BNetRegionsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNRegionsIndexModel) ToBNet() any {
	return r
}
