package wow_Region

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetRegionsIndexResponse is the unified BNet representation for RegionsIndex.
type BNetRegionsIndex struct{}

// RegionsIndexResponse represents the raw CN API response for RegionsIndex.
type CNRegionsIndex BNetRegionsIndex

// ToBNet converts the CN response to the unified BNetRegionsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNRegionsIndex) ToBNet() any {
	return r
}
