package wowClassic_WoWToken

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetWoWTokenIndexCNResponse is the unified BNet representation for WoWTokenIndexCN.
type BNetWoWTokenIndexCN struct{}

// WoWTokenIndexCNResponse represents the raw CN API response for WoWTokenIndexCN.
type CNWoWTokenIndexCN BNetWoWTokenIndexCN

// ToBNet converts the CN response to the unified BNetWoWTokenIndexCNResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNWoWTokenIndexCN) ToBNet() any {
	return r
}
