package wowClassic_WoWToken
// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater
// Author: @Thenecromance 
import (
	"Unofficial_API/api/Authentication"
	"Unofficial_API/utils"
	"context"
	"io"
	"net/http"
)

 
//==============================================================================================

type WoWTokenIndexFields struct {
	Namespace string//The namespace to use to locate this document.
	Locale string//The locale to reflect in localized data.
	
	ExtraFields map[any]any // extra fields
	utils.RequestMethod
}

//func WoWTokenIndex(CN)Field(input *WoWTokenIndex(CN)Fields) *WoWTokenIndex(CN)Fields {
//input.RequestMethod = utils.RequestMethod{
//			Methods: "GET",
//			Path: "/data/wow/token/index",
//			CnRegion:true ,
//}
//return input
//}


//WoWTokenIndex(CN) Returns the WoW Token index.
//
//@see: /data/wow/token/index
func StringWoWTokenIndex(ctx context.Context, fields *WoWTokenIndexFields) (string, error) {
	if fields == nil {
		fields = &WoWTokenIndexFields{}
	}

	func(input *WoWTokenIndexFields) {
	
if input.Namespace==""{
input.Namespace = "dynamic-classic-cn"
}

	
if input.Locale==""{
input.Locale = "zh_CN"
}

	
		input.RequestMethod = utils.RequestMethod{
			Methods: "GET",
			Path: "/data/wow/token/index",
			CnRegion:true ,
		}
	}(fields)
	cli := http.Client{}
	req, err := http.NewRequestWithContext(
		ctx,
		fields.Methods,
		"https://us.api.blizzard.com"+fields.Path,
		nil)
	
	if err != nil {
		return "", err
	}
	req.Header.Add("Authorization", "Bearer "+Authentication.GetToken())
	q := req.URL.Query()
	q.Add("namespace", fields.Namespace)
	q.Add("locale", fields.Locale)
	
	req.URL.RawQuery = q.Encode()

	resp, err := cli.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(responseBytes), nil
}

func CNWoWTokenIndex(ctx context.Context, fields *WoWTokenIndexFields) (any, error) {

obj, err := StringWoWTokenIndex(CN)(ctx,fields)
if err != nil {
		return nil,err
	}
resp :=&WoWTokenIndexResponse{}
err = json.Unmarshal([]byte(obj), resp )
	if err != nil {
		return nil,err
	}

return resp,nil 
}

var WoWTokenIndex = CNWoWTokenIndex
/*func BNetWoWTokenIndex(CN)(ctx context.Context, fields *WoWTokenIndex(CN)Fields)(any,error){

obj ,err := CNWoWTokenIndex(CN)(ctx,fields)
if err != nil {
	return nil,err
}


return obj.(*WoWTokenIndex(CN)Response).ToBNet(),nil
}*/


