

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Item

type ItemSubclassModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ClassID                int    `json:"class_id"`
	DisplayName            string `json:"display_name,omitzero"`
	HideSubclassInTooltips bool   `json:"hide_subclass_in_tooltips,omitzero"`
	SubclassID             int    `json:"subclass_id"`
}





// ItemSubclass represents the raw CN API response for ItemSubclass.
type CNItemSubclassModel ItemSubclassModel

// ToBNet converts the CN  to the unified BNetItemSubclass.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemSubclassModel) ToBNet() any {
	return r
}
