

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Item

type ItemModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Appearances []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"appearances"`
	ID            int `json:"id,omitzero"`
	InventoryType struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"inventory_type"`
	IsEquippable bool `json:"is_equippable,omitzero"`
	IsStackable  bool `json:"is_stackable"`
	ItemClass    struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"item_class"`
	ItemSubclass struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"item_subclass"`
	Level    int `json:"level,omitzero"`
	MaxCount int `json:"max_count,omitzero"`
	Media    struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	Name        string `json:"name,omitzero"`
	PreviewItem struct {
		Binding struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"binding"`
		BonusList  []int `json:"bonus_list"`
		Context    int   `json:"context"`
		Durability struct {
			DisplayString string `json:"display_string,omitzero"`
			Value         int    `json:"value,omitzero"`
		} `json:"durability"`
		InventoryType struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"inventory_type"`
		Item struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
		} `json:"item"`
		ItemClass struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"item_class"`
		ItemSubclass struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"item_subclass"`
		Level struct {
			DisplayString string `json:"display_string,omitzero"`
			Value         int    `json:"value,omitzero"`
		} `json:"level"`
		Media struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
		} `json:"media"`
		Name    string `json:"name,omitzero"`
		Quality struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"quality"`
		Requirements struct {
			Level struct {
				DisplayString string `json:"display_string,omitzero"`
				Value         int    `json:"value,omitzero"`
			} `json:"level"`
		} `json:"requirements"`
		Spells []struct {
			Description string `json:"description,omitzero"`
			Spell       struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"spell"`
		} `json:"spells"`
		Stats []struct {
			Display struct {
				Color struct {
					A float64 `json:"a,omitzero"`
					B int     `json:"b"`
					G int     `json:"g,omitzero"`
					R int     `json:"r"`
				} `json:"color"`
				DisplayString string `json:"display_string,omitzero"`
			} `json:"display"`
			IsNegated bool `json:"is_negated,omitempty,omitzero"`
			Type      struct {
				Name string `json:"name,omitzero"`
				Type string `json:"type,omitzero"`
			} `json:"type"`
			Value int `json:"value,omitzero"`
		} `json:"stats"`
		UniqueEquipped string `json:"unique_equipped,omitzero"`
		Weapon         struct {
			AttackSpeed struct {
				DisplayString string `json:"display_string,omitzero"`
				Value         int    `json:"value,omitzero"`
			} `json:"attack_speed"`
			Damage struct {
				DamageClass struct {
					Name string `json:"name,omitzero"`
					Type string `json:"type,omitzero"`
				} `json:"damage_class"`
				DisplayString string `json:"display_string,omitzero"`
				MaxValue      int    `json:"max_value,omitzero"`
				MinValue      int    `json:"min_value,omitzero"`
			} `json:"damage"`
			Dps struct {
				DisplayString string  `json:"display_string,omitzero"`
				Value         float64 `json:"value,omitzero"`
			} `json:"dps"`
		} `json:"weapon"`
	} `json:"preview_item"`
	PurchasePrice    int `json:"purchase_price,omitzero"`
	PurchaseQuantity int `json:"purchase_quantity,omitzero"`
	Quality          struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"quality"`
	RequiredLevel int `json:"required_level,omitzero"`
	SellPrice     int `json:"sell_price,omitzero"`
}





// Item represents the raw CN API response for Item.
type CNItemModel ItemModel

// ToBNet converts the CN  to the unified BNetItem.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemModel) ToBNet() any {
	return r
}
