

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Item

type ItemClassesIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ItemClasses []struct {
		ID  int `json:"id"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"item_classes"`
}





// ItemClassesIndex represents the raw CN API response for ItemClassesIndex.
type CNItemClassesIndexModel ItemClassesIndexModel

// ToBNet converts the CN  to the unified BNetItemClassesIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemClassesIndexModel) ToBNet() any {
	return r
}
