package wow_Item

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetItemSetResponse is the unified BNet representation for ItemSet.
type BNetItemSet struct{}

// ItemSetResponse represents the raw CN API response for ItemSet.
type CNItemSet BNetItemSet

// ToBNet converts the CN response to the unified BNetItemSetResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemSet) ToBNet() any {
	return r
}
