package wow_Item

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetItemSetsIndexResponse is the unified BNet representation for ItemSetsIndex.
type BNetItemSetsIndex struct{}

// ItemSetsIndexResponse represents the raw CN API response for ItemSetsIndex.
type CNItemSetsIndex BNetItemSetsIndex

// ToBNet converts the CN response to the unified BNetItemSetsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemSetsIndex) ToBNet() any {
	return r
}
