

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Item

type ItemSetModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Effects []struct {
		DisplayString string `json:"display_string,omitzero"`
		RequiredCount int    `json:"required_count,omitzero"`
	} `json:"effects"`
	ID             int  `json:"id,omitzero"`
	IsEffectActive bool `json:"is_effect_active"`
	Items          []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"items"`
	Name string `json:"name,omitzero"`
}





// ItemSet represents the raw CN API response for ItemSet.
type CNItemSetModel ItemSetModel

// ToBNet converts the CN  to the unified BNetItemSet.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemSetModel) ToBNet() any {
	return r
}
