

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Item

type ItemSetsIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ItemSets []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"item_sets"`
}





// ItemSetsIndex represents the raw CN API response for ItemSetsIndex.
type CNItemSetsIndexModel ItemSetsIndexModel

// ToBNet converts the CN  to the unified BNetItemSetsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNItemSetsIndexModel) ToBNet() any {
	return r
}
