package wow_PowerType

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetPowerTypeResponse is the unified BNet representation for PowerType.
type BNetPowerType struct{}

// PowerTypeResponse represents the raw CN API response for PowerType.
type CNPowerType BNetPowerType

// ToBNet converts the CN response to the unified BNetPowerTypeResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPowerType) ToBNet() any {
	return r
}
