

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_PowerType

type PowerTypeModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ID   int    `json:"id"`
	Name string `json:"name,omitzero"`
}





// PowerType represents the raw CN API response for PowerType.
type CNPowerTypeModel PowerTypeModel

// ToBNet converts the CN  to the unified BNetPowerType.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPowerTypeModel) ToBNet() any {
	return r
}
