package wow_Profession

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetProfessionResponse is the unified BNet representation for Profession.
type BNetProfession struct{}

// ProfessionResponse represents the raw CN API response for Profession.
type CNProfession BNetProfession

// ToBNet converts the CN response to the unified BNetProfessionResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNProfession) ToBNet() any {
	return r
}
