

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Profession

type ProfessionSkillTierModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Categories []struct {
		Name    string `json:"name,omitzero"`
		Recipes []struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"recipes"`
	} `json:"categories"`
	ID                int    `json:"id,omitzero"`
	MaximumSkillLevel int    `json:"maximum_skill_level,omitzero"`
	MinimumSkillLevel int    `json:"minimum_skill_level,omitzero"`
	Name              string `json:"name,omitzero"`
}





// ProfessionSkillTier represents the raw CN API response for ProfessionSkillTier.
type CNProfessionSkillTierModel ProfessionSkillTierModel

// ToBNet converts the CN  to the unified BNetProfessionSkillTier.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNProfessionSkillTierModel) ToBNet() any {
	return r
}
