package wow_Profession

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetProfessionMediaResponse is the unified BNet representation for ProfessionMedia.
type BNetProfessionMedia struct{}

// ProfessionMediaResponse represents the raw CN API response for ProfessionMedia.
type CNProfessionMedia BNetProfessionMedia

// ToBNet converts the CN response to the unified BNetProfessionMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNProfessionMedia) ToBNet() any {
	return r
}
