package wow_Profession

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetProfessionsIndexResponse is the unified BNet representation for ProfessionsIndex.
type BNetProfessionsIndex struct{}

// ProfessionsIndexResponse represents the raw CN API response for ProfessionsIndex.
type CNProfessionsIndex BNetProfessionsIndex

// ToBNet converts the CN response to the unified BNetProfessionsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNProfessionsIndex) ToBNet() any {
	return r
}
