

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Profession

type ProfessionsIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Professions []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"professions"`
}





// ProfessionsIndex represents the raw CN API response for ProfessionsIndex.
type CNProfessionsIndexModel ProfessionsIndexModel

// ToBNet converts the CN  to the unified BNetProfessionsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNProfessionsIndexModel) ToBNet() any {
	return r
}
