

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Profession

type RecipeModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	CraftedItem struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"crafted_item"`
	CraftedQuantity struct {
		Value float64 `json:"value,omitzero"`
	} `json:"crafted_quantity"`
	ID    int `json:"id,omitzero"`
	Media struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"media"`
	Name     string `json:"name,omitzero"`
	Reagents []struct {
		Quantity int `json:"quantity,omitzero"`
		Reagent  struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"reagent"`
	} `json:"reagents"`
}





// Recipe represents the raw CN API response for Recipe.
type CNRecipeModel RecipeModel

// ToBNet converts the CN  to the unified BNetRecipe.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNRecipeModel) ToBNet() any {
	return r
}
