package wow_Profession

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetRecipeMediaResponse is the unified BNet representation for RecipeMedia.
type BNetRecipeMedia struct{}

// RecipeMediaResponse represents the raw CN API response for RecipeMedia.
type CNRecipeMedia BNetRecipeMedia

// ToBNet converts the CN response to the unified BNetRecipeMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNRecipeMedia) ToBNet() any {
	return r
}
