package wow_Profession

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetRecipeResponse is the unified BNet representation for Recipe.
type BNetRecipe struct{}

// RecipeResponse represents the raw CN API response for Recipe.
type CNRecipe BNetRecipe

// ToBNet converts the CN response to the unified BNetRecipeResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNRecipe) ToBNet() any {
	return r
}
