

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Guild

type GuildActivityModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Activities []struct {
		Activity struct {
			Type string `json:"type,omitzero"`
		} `json:"activity"`
		CharacterAchievement *struct {
			Achievement struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"achievement"`
			Character struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name  string `json:"name,omitzero"`
				Realm struct {
					ID  int `json:"id,omitzero"`
					Key struct {
						Href string `json:"href,omitzero"`
					} `json:"key"`
					Name string `json:"name,omitzero"`
					Slug string `json:"slug,omitzero"`
				} `json:"realm"`
			} `json:"character"`
		} `json:"character_achievement,omitempty,omitzero"`
		EncounterCompleted *struct {
			Encounter struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"encounter"`
			Mode struct {
				Name string `json:"name,omitzero"`
				Type string `json:"type,omitzero"`
			} `json:"mode"`
		} `json:"encounter_completed,omitempty,omitzero"`
		Timestamp int `json:"timestamp,omitzero"`
	} `json:"activities"`
	Guild struct {
		Faction struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"faction"`
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name  string `json:"name,omitzero"`
		Realm struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"realm"`
	} `json:"guild"`
}





// GuildActivity represents the raw CN API response for GuildActivity.
type CNGuildActivityModel GuildActivityModel

// ToBNet converts the CN  to the unified BNetGuildActivity.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuildActivityModel) ToBNet() any {
	return r
}
