

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Guild

type GuildModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	AchievementPoints int `json:"achievement_points,omitzero"`
	Achievements      struct {
		Href string `json:"href,omitzero"`
	} `json:"achievements"`
	Activity struct {
		Href string `json:"href,omitzero"`
	} `json:"activity"`
	CreatedTimestamp int `json:"created_timestamp,omitzero"`
	Faction          struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"faction"`
	ID          int    `json:"id,omitzero"`
	MemberCount int    `json:"member_count,omitzero"`
	Name        string `json:"name,omitzero"`
	NameSearch  string `json:"name_search,omitzero"`
	Realm       struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
		Slug string `json:"slug,omitzero"`
	} `json:"realm"`
	Roster struct {
		Href string `json:"href,omitzero"`
	} `json:"roster"`
}





// Guild represents the raw CN API response for Guild.
type CNGuildModel GuildModel

// ToBNet converts the CN  to the unified BNetGuild.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuildModel) ToBNet() any {
	return r
}
