package wow_Guild

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGuildActivityResponse is the unified BNet representation for GuildActivity.
type BNetGuildActivity struct{}

// GuildActivityResponse represents the raw CN API response for GuildActivity.
type CNGuildActivity BNetGuildActivity

// ToBNet converts the CN response to the unified BNetGuildActivityResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuildActivity) ToBNet() any {
	return r
}
