package wow_CharacterTitles

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterTitlesSummaryResponse is the unified BNet representation for CharacterTitlesSummary.
type BNetCharacterTitlesSummary struct{}

// CharacterTitlesSummaryResponse represents the raw CN API response for CharacterTitlesSummary.
type CNCharacterTitlesSummary BNetCharacterTitlesSummary

// ToBNet converts the CN response to the unified BNetCharacterTitlesSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterTitlesSummary) ToBNet() any {
	return r
}
