package wow_MythicKeystoneDungeon

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMythicKeystonePeriodResponse is the unified BNet representation for MythicKeystonePeriod.
type BNetMythicKeystonePeriod struct{}

// MythicKeystonePeriodResponse represents the raw CN API response for MythicKeystonePeriod.
type CNMythicKeystonePeriod BNetMythicKeystonePeriod

// ToBNet converts the CN response to the unified BNetMythicKeystonePeriodResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystonePeriod) ToBNet() any {
	return r
}
