package wow_MythicKeystoneDungeon

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMythicKeystoneSeasonResponse is the unified BNet representation for MythicKeystoneSeason.
type BNetMythicKeystoneSeason struct{}

// MythicKeystoneSeasonResponse represents the raw CN API response for MythicKeystoneSeason.
type CNMythicKeystoneSeason BNetMythicKeystoneSeason

// ToBNet converts the CN response to the unified BNetMythicKeystoneSeasonResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneSeason) ToBNet() any {
	return r
}
