

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_MythicKeystoneDungeon

type MythicKeystoneDungeonModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Dungeon struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"dungeon"`
	ID               int  `json:"id,omitzero"`
	IsTracked        bool `json:"is_tracked"`
	KeystoneUpgrades []struct {
		QualifyingDuration int `json:"qualifying_duration,omitzero"`
		UpgradeLevel       int `json:"upgrade_level,omitzero"`
	} `json:"keystone_upgrades"`
	Map struct {
		ID   int    `json:"id,omitzero"`
		Name string `json:"name,omitzero"`
	} `json:"map"`
	Name string `json:"name,omitzero"`
	Zone struct {
		Slug string `json:"slug,omitzero"`
	} `json:"zone"`
}





// MythicKeystoneDungeon represents the raw CN API response for MythicKeystoneDungeon.
type CNMythicKeystoneDungeonModel MythicKeystoneDungeonModel

// ToBNet converts the CN  to the unified BNetMythicKeystoneDungeon.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneDungeonModel) ToBNet() any {
	return r
}
