package wow_MythicKeystoneDungeon

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMythicKeystoneDungeonsIndexResponse is the unified BNet representation for MythicKeystoneDungeonsIndex.
type BNetMythicKeystoneDungeonsIndex struct{}

// MythicKeystoneDungeonsIndexResponse represents the raw CN API response for MythicKeystoneDungeonsIndex.
type CNMythicKeystoneDungeonsIndex BNetMythicKeystoneDungeonsIndex

// ToBNet converts the CN response to the unified BNetMythicKeystoneDungeonsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneDungeonsIndex) ToBNet() any {
	return r
}
