package wow_MythicKeystoneDungeon

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMythicKeystoneIndexResponse is the unified BNet representation for MythicKeystoneIndex.
type BNetMythicKeystoneIndex struct{}

// MythicKeystoneIndexResponse represents the raw CN API response for MythicKeystoneIndex.
type CNMythicKeystoneIndex BNetMythicKeystoneIndex

// ToBNet converts the CN response to the unified BNetMythicKeystoneIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneIndex) ToBNet() any {
	return r
}
