

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_MythicKeystoneDungeon

type MythicKeystoneIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Dungeons struct {
		Href string `json:"href,omitzero"`
	} `json:"dungeons"`
	Seasons struct {
		Href string `json:"href,omitzero"`
	} `json:"seasons"`
}





// MythicKeystoneIndex represents the raw CN API response for MythicKeystoneIndex.
type CNMythicKeystoneIndexModel MythicKeystoneIndexModel

// ToBNet converts the CN  to the unified BNetMythicKeystoneIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneIndexModel) ToBNet() any {
	return r
}
