

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_MythicKeystoneDungeon

type MythicKeystoneSeasonModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	EndTimestamp int `json:"end_timestamp,omitzero"`
	ID           int `json:"id,omitzero"`
	Periods      []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"periods"`
	SeasonName     string `json:"season_name,omitzero"`
	StartTimestamp int    `json:"start_timestamp,omitzero"`
}





// MythicKeystoneSeason represents the raw CN API response for MythicKeystoneSeason.
type CNMythicKeystoneSeasonModel MythicKeystoneSeasonModel

// ToBNet converts the CN  to the unified BNetMythicKeystoneSeason.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneSeasonModel) ToBNet() any {
	return r
}
