

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_MythicKeystoneDungeon

type MythicKeystonePeriodsIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	CurrentPeriod struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"current_period"`
	Periods []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"periods"`
}





// MythicKeystonePeriodsIndex represents the raw CN API response for MythicKeystonePeriodsIndex.
type CNMythicKeystonePeriodsIndexModel MythicKeystonePeriodsIndexModel

// ToBNet converts the CN  to the unified BNetMythicKeystonePeriodsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystonePeriodsIndexModel) ToBNet() any {
	return r
}
