package wow_MythicKeystoneDungeon

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMythicKeystoneSeasonsIndexResponse is the unified BNet representation for MythicKeystoneSeasonsIndex.
type BNetMythicKeystoneSeasonsIndex struct{}

// MythicKeystoneSeasonsIndexResponse represents the raw CN API response for MythicKeystoneSeasonsIndex.
type CNMythicKeystoneSeasonsIndex BNetMythicKeystoneSeasonsIndex

// ToBNet converts the CN response to the unified BNetMythicKeystoneSeasonsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneSeasonsIndex) ToBNet() any {
	return r
}
