

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_MythicKeystoneDungeon

type MythicKeystoneSeasonsIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	CurrentSeason struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"current_season"`
	Seasons []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"seasons"`
}





// MythicKeystoneSeasonsIndex represents the raw CN API response for MythicKeystoneSeasonsIndex.
type CNMythicKeystoneSeasonsIndexModel MythicKeystoneSeasonsIndexModel

// ToBNet converts the CN  to the unified BNetMythicKeystoneSeasonsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneSeasonsIndexModel) ToBNet() any {
	return r
}
