package wow_MythicKeystoneDungeon

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMythicKeystonePeriodsIndexResponse is the unified BNet representation for MythicKeystonePeriodsIndex.
type BNetMythicKeystonePeriodsIndex struct{}

// MythicKeystonePeriodsIndexResponse represents the raw CN API response for MythicKeystonePeriodsIndex.
type CNMythicKeystonePeriodsIndex BNetMythicKeystonePeriodsIndex

// ToBNet converts the CN response to the unified BNetMythicKeystonePeriodsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystonePeriodsIndex) ToBNet() any {
	return r
}
