

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_PlayableRace

type PlayableRaceModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Faction struct {
		Name string `json:"name,omitzero"`
		Type string `json:"type,omitzero"`
	} `json:"faction"`
	GenderName struct {
		Female string `json:"female,omitzero"`
		Male   string `json:"male,omitzero"`
	} `json:"gender_name"`
	ID              int    `json:"id,omitzero"`
	IsAlliedRace    bool   `json:"is_allied_race"`
	IsSelectable    bool   `json:"is_selectable,omitzero"`
	Name            string `json:"name,omitzero"`
	PlayableClasses []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"playable_classes"`
	RacialSpells []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"racial_spells"`
}





// PlayableRace represents the raw CN API response for PlayableRace.
type CNPlayableRaceModel PlayableRaceModel

// ToBNet converts the CN  to the unified BNetPlayableRace.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNPlayableRaceModel) ToBNet() any {
	return r
}
