

package wowClassic_CharacterMedia

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CharacterMediaSummaryModel is the unified BNet representation for CharacterMediaSummary.
type CharacterMediaSummaryModel struct{}




// CharacterMediaSummary represents the raw CN API response for CharacterMediaSummary.
type CNCharacterMediaSummaryModel CharacterMediaSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterMediaSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterMediaSummaryModel) ToBNet() any {
	return r
}
