package wow_Reputations

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetReputationFactionsIndexResponse is the unified BNet representation for ReputationFactionsIndex.
type BNetReputationFactionsIndex struct{}

// ReputationFactionsIndexResponse represents the raw CN API response for ReputationFactionsIndex.
type CNReputationFactionsIndex BNetReputationFactionsIndex

// ToBNet converts the CN response to the unified BNetReputationFactionsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNReputationFactionsIndex) ToBNet() any {
	return r
}
