package wow_Reputations

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetReputationTiersResponse is the unified BNet representation for ReputationTiers.
type BNetReputationTiers struct{}

// ReputationTiersResponse represents the raw CN API response for ReputationTiers.
type CNReputationTiers BNetReputationTiers

// ToBNet converts the CN response to the unified BNetReputationTiersResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNReputationTiers) ToBNet() any {
	return r
}
