package wow_Reputations

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetReputationTiersIndexResponse is the unified BNet representation for ReputationTiersIndex.
type BNetReputationTiersIndex struct{}

// ReputationTiersIndexResponse represents the raw CN API response for ReputationTiersIndex.
type CNReputationTiersIndex BNetReputationTiersIndex

// ToBNet converts the CN response to the unified BNetReputationTiersIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNReputationTiersIndex) ToBNet() any {
	return r
}
