

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Reputations

type ReputationFactionModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Description     string `json:"description,omitzero"`
	ID              int    `json:"id,omitzero"`
	Name            string `json:"name,omitzero"`
	ReputationTiers struct {
		ID  int `json:"id"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
	} `json:"reputation_tiers"`
}





// ReputationFaction represents the raw CN API response for ReputationFaction.
type CNReputationFactionModel ReputationFactionModel

// ToBNet converts the CN  to the unified BNetReputationFaction.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNReputationFactionModel) ToBNet() any {
	return r
}
