

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Reputations

type ReputationTiersModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Faction struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"faction"`
	ID    int `json:"id,omitzero"`
	Tiers []struct {
		ID       int    `json:"id"`
		MaxValue int    `json:"max_value,omitzero"`
		MinValue int    `json:"min_value"`
		Name     string `json:"name,omitzero"`
	} `json:"tiers"`
}





// ReputationTiers represents the raw CN API response for ReputationTiers.
type CNReputationTiersModel ReputationTiersModel

// ToBNet converts the CN  to the unified BNetReputationTiers.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNReputationTiersModel) ToBNet() any {
	return r
}
