

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Reputations

type ReputationFactionsIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Factions []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"factions"`
	RootFactions []struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitzero"`
	} `json:"root_factions"`
}





// ReputationFactionsIndex represents the raw CN API response for ReputationFactionsIndex.
type CNReputationFactionsIndexModel ReputationFactionsIndexModel

// ToBNet converts the CN  to the unified BNetReputationFactionsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNReputationFactionsIndexModel) ToBNet() any {
	return r
}
