

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Reputations

type ReputationTiersIndexModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ReputationTiers []struct {
		ID  int `json:"id"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name string `json:"name,omitempty,omitzero"`
	} `json:"reputation_tiers"`
}





// ReputationTiersIndex represents the raw CN API response for ReputationTiersIndex.
type CNReputationTiersIndexModel ReputationTiersIndexModel

// ToBNet converts the CN  to the unified BNetReputationTiersIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNReputationTiersIndexModel) ToBNet() any {
	return r
}
