package wowClassic_Region

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetRegionResponse is the unified BNet representation for Region.
type BNetRegion struct{}

// RegionResponse represents the raw CN API response for Region.
type CNRegion BNetRegion

// ToBNet converts the CN response to the unified BNetRegionResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNRegion) ToBNet() any {
	return r
}
