package wowClassic_CharacterEquipment

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterEquipmentSummaryResponse is the unified BNet representation for CharacterEquipmentSummary.
type BNetCharacterEquipmentSummary struct{}

// CharacterEquipmentSummaryResponse represents the raw CN API response for CharacterEquipmentSummary.
type CNCharacterEquipmentSummary BNetCharacterEquipmentSummary

// ToBNet converts the CN response to the unified BNetCharacterEquipmentSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterEquipmentSummary) ToBNet() any {
	return r
}
