

package wowClassic_CharacterEquipment

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// CharacterEquipmentSummaryModel is the unified BNet representation for CharacterEquipmentSummary.
type CharacterEquipmentSummaryModel struct{}




// CharacterEquipmentSummary represents the raw CN API response for CharacterEquipmentSummary.
type CNCharacterEquipmentSummaryModel CharacterEquipmentSummaryModel

// ToBNet converts the CN  to the unified BNetCharacterEquipmentSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterEquipmentSummaryModel) ToBNet() any {
	return r
}
