package wow_CharacterProfessions

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCharacterProfessionsSummaryResponse is the unified BNet representation for CharacterProfessionsSummary.
type BNetCharacterProfessionsSummary struct{}

// CharacterProfessionsSummaryResponse represents the raw CN API response for CharacterProfessionsSummary.
type CNCharacterProfessionsSummary BNetCharacterProfessionsSummary

// ToBNet converts the CN response to the unified BNetCharacterProfessionsSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterProfessionsSummary) ToBNet() any {
	return r
}
