

package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// AccountCollectionsIndexModel is the unified BNet representation for AccountCollectionsIndex.
type AccountCollectionsIndexModel struct{}




// AccountCollectionsIndex represents the raw CN API response for AccountCollectionsIndex.
type CNAccountCollectionsIndexModel AccountCollectionsIndexModel

// ToBNet converts the CN  to the unified BNetAccountCollectionsIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountCollectionsIndexModel) ToBNet() any {
	return r
}
