package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAccountTransmogCollectionSummaryResponse is the unified BNet representation for AccountTransmogCollectionSummary.
type BNetAccountTransmogCollectionSummary struct{}

// AccountTransmogCollectionSummaryResponse represents the raw CN API response for AccountTransmogCollectionSummary.
type CNAccountTransmogCollectionSummary BNetAccountTransmogCollectionSummary

// ToBNet converts the CN response to the unified BNetAccountTransmogCollectionSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountTransmogCollectionSummary) ToBNet() any {
	return r
}
