package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAccountHeirloomsCollectionSummaryResponse is the unified BNet representation for AccountHeirloomsCollectionSummary.
type BNetAccountHeirloomsCollectionSummary struct{}

// AccountHeirloomsCollectionSummaryResponse represents the raw CN API response for AccountHeirloomsCollectionSummary.
type CNAccountHeirloomsCollectionSummary BNetAccountHeirloomsCollectionSummary

// ToBNet converts the CN response to the unified BNetAccountHeirloomsCollectionSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountHeirloomsCollectionSummary) ToBNet() any {
	return r
}
