

package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// AccountToysCollectionSummaryModel is the unified BNet representation for AccountToysCollectionSummary.
type AccountToysCollectionSummaryModel struct{}




// AccountToysCollectionSummary represents the raw CN API response for AccountToysCollectionSummary.
type CNAccountToysCollectionSummaryModel AccountToysCollectionSummaryModel

// ToBNet converts the CN  to the unified BNetAccountToysCollectionSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountToysCollectionSummaryModel) ToBNet() any {
	return r
}
