package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAccountCollectionsIndexResponse is the unified BNet representation for AccountCollectionsIndex.
type BNetAccountCollectionsIndex struct{}

// AccountCollectionsIndexResponse represents the raw CN API response for AccountCollectionsIndex.
type CNAccountCollectionsIndex BNetAccountCollectionsIndex

// ToBNet converts the CN response to the unified BNetAccountCollectionsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountCollectionsIndex) ToBNet() any {
	return r
}
