package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAccountProfileSummaryResponse is the unified BNet representation for AccountProfileSummary.
type BNetAccountProfileSummary struct{}

// AccountProfileSummaryResponse represents the raw CN API response for AccountProfileSummary.
type CNAccountProfileSummary BNetAccountProfileSummary

// ToBNet converts the CN response to the unified BNetAccountProfileSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountProfileSummary) ToBNet() any {
	return r
}
