package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAccountToysCollectionSummaryResponse is the unified BNet representation for AccountToysCollectionSummary.
type BNetAccountToysCollectionSummary struct{}

// AccountToysCollectionSummaryResponse represents the raw CN API response for AccountToysCollectionSummary.
type CNAccountToysCollectionSummary BNetAccountToysCollectionSummary

// ToBNet converts the CN response to the unified BNetAccountToysCollectionSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountToysCollectionSummary) ToBNet() any {
	return r
}
