

package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// AccountHeirloomsCollectionSummaryModel is the unified BNet representation for AccountHeirloomsCollectionSummary.
type AccountHeirloomsCollectionSummaryModel struct{}




// AccountHeirloomsCollectionSummary represents the raw CN API response for AccountHeirloomsCollectionSummary.
type CNAccountHeirloomsCollectionSummaryModel AccountHeirloomsCollectionSummaryModel

// ToBNet converts the CN  to the unified BNetAccountHeirloomsCollectionSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountHeirloomsCollectionSummaryModel) ToBNet() any {
	return r
}
