package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAccountMountsCollectionSummaryResponse is the unified BNet representation for AccountMountsCollectionSummary.
type BNetAccountMountsCollectionSummary struct{}

// AccountMountsCollectionSummaryResponse represents the raw CN API response for AccountMountsCollectionSummary.
type CNAccountMountsCollectionSummary BNetAccountMountsCollectionSummary

// ToBNet converts the CN response to the unified BNetAccountMountsCollectionSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountMountsCollectionSummary) ToBNet() any {
	return r
}
