

package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// AccountTransmogCollectionSummaryModel is the unified BNet representation for AccountTransmogCollectionSummary.
type AccountTransmogCollectionSummaryModel struct{}




// AccountTransmogCollectionSummary represents the raw CN API response for AccountTransmogCollectionSummary.
type CNAccountTransmogCollectionSummaryModel AccountTransmogCollectionSummaryModel

// ToBNet converts the CN  to the unified BNetAccountTransmogCollectionSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountTransmogCollectionSummaryModel) ToBNet() any {
	return r
}
