package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAccountDecorCollectionSummaryResponse is the unified BNet representation for AccountDecorCollectionSummary.
type BNetAccountDecorCollectionSummary struct{}

// AccountDecorCollectionSummaryResponse represents the raw CN API response for AccountDecorCollectionSummary.
type CNAccountDecorCollectionSummary BNetAccountDecorCollectionSummary

// ToBNet converts the CN response to the unified BNetAccountDecorCollectionSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountDecorCollectionSummary) ToBNet() any {
	return r
}
