

package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// AccountMountsCollectionSummaryModel is the unified BNet representation for AccountMountsCollectionSummary.
type AccountMountsCollectionSummaryModel struct{}




// AccountMountsCollectionSummary represents the raw CN API response for AccountMountsCollectionSummary.
type CNAccountMountsCollectionSummaryModel AccountMountsCollectionSummaryModel

// ToBNet converts the CN  to the unified BNetAccountMountsCollectionSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountMountsCollectionSummaryModel) ToBNet() any {
	return r
}
