package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAccountPetsCollectionSummaryResponse is the unified BNet representation for AccountPetsCollectionSummary.
type BNetAccountPetsCollectionSummary struct{}

// AccountPetsCollectionSummaryResponse represents the raw CN API response for AccountPetsCollectionSummary.
type CNAccountPetsCollectionSummary BNetAccountPetsCollectionSummary

// ToBNet converts the CN response to the unified BNetAccountPetsCollectionSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountPetsCollectionSummary) ToBNet() any {
	return r
}
