

package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// AccountPetsCollectionSummaryModel is the unified BNet representation for AccountPetsCollectionSummary.
type AccountPetsCollectionSummaryModel struct{}




// AccountPetsCollectionSummary represents the raw CN API response for AccountPetsCollectionSummary.
type CNAccountPetsCollectionSummaryModel AccountPetsCollectionSummaryModel

// ToBNet converts the CN  to the unified BNetAccountPetsCollectionSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAccountPetsCollectionSummaryModel) ToBNet() any {
	return r
}
