package wow_AccountProfile

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetProtectedCharacterProfileSummaryResponse is the unified BNet representation for ProtectedCharacterProfileSummary.
type BNetProtectedCharacterProfileSummary struct{}

// ProtectedCharacterProfileSummaryResponse represents the raw CN API response for ProtectedCharacterProfileSummary.
type CNProtectedCharacterProfileSummary BNetProtectedCharacterProfileSummary

// ToBNet converts the CN response to the unified BNetProtectedCharacterProfileSummaryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNProtectedCharacterProfileSummary) ToBNet() any {
	return r
}
