package HeartStone_Cards

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetCardsearchResponse is the unified BNet representation for Cardsearch.
type BNetCardsearch struct{}

// CardsearchResponse represents the raw CN API response for Cardsearch.
type CNCardsearch BNetCardsearch

// ToBNet converts the CN response to the unified BNetCardsearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCardsearch) ToBNet() any {
	return r
}
