package HeartStone_Cards

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetDetailedcardsearchexampleResponse is the unified BNet representation for Detailedcardsearchexample.
type BNetDetailedcardsearchexample struct{}

// DetailedcardsearchexampleResponse represents the raw CN API response for Detailedcardsearchexample.
type CNDetailedcardsearchexample BNetDetailedcardsearchexample

// ToBNet converts the CN response to the unified BNetDetailedcardsearchexampleResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNDetailedcardsearchexample) ToBNet() any {
	return r
}
