

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package HeartStone_Cards

type DetailedcardsearchexampleModel struct {
	CardCount int   `json:"cardCount"`
	Cards     []any `json:"cards"`
	Page      int   `json:"page,omitzero"`
	PageCount int   `json:"pageCount"`
}





// Detailedcardsearchexample represents the raw CN API response for Detailedcardsearchexample.
type CNDetailedcardsearchexampleModel DetailedcardsearchexampleModel

// ToBNet converts the CN  to the unified BNetDetailedcardsearchexample.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNDetailedcardsearchexampleModel) ToBNet() any {
	return r
}
