

package HeartStone_Cards

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// FetchonecardModel is the unified BNet representation for Fetchonecard.
type FetchonecardModel struct{}




// Fetchonecard represents the raw CN API response for Fetchonecard.
type CNFetchonecardModel FetchonecardModel

// ToBNet converts the CN  to the unified BNetFetchonecard.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNFetchonecardModel) ToBNet() any {
	return r
}
