package HeartStone_Cards

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetFetchonecardResponse is the unified BNet representation for Fetchonecard.
type BNetFetchonecard struct{}

// FetchonecardResponse represents the raw CN API response for Fetchonecard.
type CNFetchonecard BNetFetchonecard

// ToBNet converts the CN response to the unified BNetFetchonecardResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNFetchonecard) ToBNet() any {
	return r
}
