package HeartStone_Cards

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMercenariescardsearchResponse is the unified BNet representation for Mercenariescardsearch.
type BNetMercenariescardsearch struct{}

// MercenariescardsearchResponse represents the raw CN API response for Mercenariescardsearch.
type CNMercenariescardsearch BNetMercenariescardsearch

// ToBNet converts the CN response to the unified BNetMercenariescardsearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMercenariescardsearch) ToBNet() any {
	return r
}
