

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package HeartStone_Cards

type MercenariescardsearchModel struct {
	CardCount int `json:"cardCount,omitzero"`
	Cards     []struct {
		ArtistName                *string `json:"artistName"`
		Attack                    int     `json:"attack,omitzero"`
		CardSetID                 int     `json:"cardSetId,omitzero"`
		CardTypeID                int     `json:"cardTypeId,omitzero"`
		ClassID                   *int    `json:"classId"`
		Collectible               int     `json:"collectible"`
		CropImage                 *string `json:"cropImage"`
		FlavorText                string  `json:"flavorText"`
		Health                    int     `json:"health,omitzero"`
		ID                        int     `json:"id,omitzero"`
		Image                     string  `json:"image,omitzero"`
		ImageGold                 string  `json:"imageGold"`
		IsZilliaxCosmeticModule   bool    `json:"isZilliaxCosmeticModule"`
		IsZilliaxFunctionalModule bool    `json:"isZilliaxFunctionalModule"`
		ManaCost                  int     `json:"manaCost"`
		MercenaryHero             struct {
			Collectible  int  `json:"collectible,omitzero"`
			CraftingCost int  `json:"craftingCost,omitzero"`
			Default      int  `json:"default"`
			Faction      *int `json:"faction"`
			MercID       int  `json:"mercId,omitzero"`
			Rarity       int  `json:"rarity,omitzero"`
			RoleID       int  `json:"roleId,omitzero"`
			StatsByLevel struct {
				_1 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"1"`
				_10 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"10"`
				_11 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"11"`
				_12 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"12"`
				_13 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"13"`
				_14 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"14"`
				_15 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"15"`
				_16 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"16"`
				_17 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"17"`
				_18 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"18"`
				_19 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"19"`
				_2 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"2"`
				_20 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"20"`
				_21 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"21"`
				_22 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"22"`
				_23 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"23"`
				_24 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"24"`
				_25 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"25"`
				_26 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"26"`
				_27 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"27"`
				_28 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"28"`
				_29 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"29"`
				_3 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"3"`
				_30 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"30"`
				_4 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"4"`
				_5 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"5"`
				_6 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"6"`
				_7 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"7"`
				_8 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"8"`
				_9 struct {
					Attack int `json:"attack,omitzero"`
					Health int `json:"health,omitzero"`
				} `json:"9"`
			} `json:"statsByLevel"`
		} `json:"mercenaryHero"`
		MinionTypeID  int    `json:"minionTypeId,omitzero"`
		MultiClassIDs []any  `json:"multiClassIds"`
		MultiTypeIDs  []int  `json:"multiTypeIds,omitempty"`
		Name          string `json:"name,omitzero"`
		RarityID      int    `json:"rarityId,omitzero"`
		Slug          string `json:"slug,omitzero"`
		Text          string `json:"text"`
	} `json:"cards"`
	Page      int `json:"page,omitzero"`
	PageCount int `json:"pageCount,omitzero"`
}





// Mercenariescardsearch represents the raw CN API response for Mercenariescardsearch.
type CNMercenariescardsearchModel MercenariescardsearchModel

// ToBNet converts the CN  to the unified BNetMercenariescardsearch.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMercenariescardsearchModel) ToBNet() any {
	return r
}
