package HeartStone_Metadata

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAllmetadataResponse is the unified BNet representation for Allmetadata.
type BNetAllmetadata struct{}

// AllmetadataResponse represents the raw CN API response for Allmetadata.
type CNAllmetadata BNetAllmetadata

// ToBNet converts the CN response to the unified BNetAllmetadataResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAllmetadata) ToBNet() any {
	return r
}
