

package HeartStone_Metadata

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// SpecificmetadataModel is the unified BNet representation for Specificmetadata.
type SpecificmetadataModel struct{}




// Specificmetadata represents the raw CN API response for Specificmetadata.
type CNSpecificmetadataModel SpecificmetadataModel

// ToBNet converts the CN  to the unified BNetSpecificmetadata.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSpecificmetadataModel) ToBNet() any {
	return r
}
