package HeartStone_Metadata

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetSpecificmetadataResponse is the unified BNet representation for Specificmetadata.
type BNetSpecificmetadata struct{}

// SpecificmetadataResponse represents the raw CN API response for Specificmetadata.
type CNSpecificmetadata BNetSpecificmetadata

// ToBNet converts the CN response to the unified BNetSpecificmetadataResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNSpecificmetadata) ToBNet() any {
	return r
}
