

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_MythicKeystoneLeaderboard

type MythicKeystoneLeaderboardModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	ConnectedRealm struct {
		Href string `json:"href,omitzero"`
	} `json:"connected_realm"`
	KeystoneAffixes []struct {
		KeystoneAffix struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"keystone_affix"`
		StartingLevel int `json:"starting_level,omitzero"`
	} `json:"keystone_affixes"`
	LeadingGroups []struct {
		CompletedTimestamp int `json:"completed_timestamp,omitzero"`
		Duration           int `json:"duration,omitzero"`
		KeystoneLevel      int `json:"keystone_level,omitzero"`
		Members            []struct {
			Faction struct {
				Type string `json:"type,omitzero"`
			} `json:"faction"`
			Profile struct {
				ID    int    `json:"id,omitzero"`
				Name  string `json:"name,omitzero"`
				Realm struct {
					ID  int `json:"id,omitzero"`
					Key struct {
						Href string `json:"href,omitzero"`
					} `json:"key"`
					Slug string `json:"slug,omitzero"`
				} `json:"realm"`
			} `json:"profile"`
			Specialization struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
			} `json:"specialization"`
		} `json:"members"`
		Ranking int `json:"ranking,omitzero"`
	} `json:"leading_groups"`
	Map struct {
		ID   int    `json:"id,omitzero"`
		Name string `json:"name,omitzero"`
	} `json:"map"`
	MapChallengeModeID   int    `json:"map_challenge_mode_id,omitzero"`
	Name                 string `json:"name,omitzero"`
	Period               int    `json:"period,omitzero"`
	PeriodEndTimestamp   int    `json:"period_end_timestamp,omitzero"`
	PeriodStartTimestamp int    `json:"period_start_timestamp,omitzero"`
}





// MythicKeystoneLeaderboard represents the raw CN API response for MythicKeystoneLeaderboard.
type CNMythicKeystoneLeaderboardModel MythicKeystoneLeaderboardModel

// ToBNet converts the CN  to the unified BNetMythicKeystoneLeaderboard.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneLeaderboardModel) ToBNet() any {
	return r
}
