package wow_MythicKeystoneLeaderboard

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMythicKeystoneLeaderboardsIndexResponse is the unified BNet representation for MythicKeystoneLeaderboardsIndex.
type BNetMythicKeystoneLeaderboardsIndex struct{}

// MythicKeystoneLeaderboardsIndexResponse represents the raw CN API response for MythicKeystoneLeaderboardsIndex.
type CNMythicKeystoneLeaderboardsIndex BNetMythicKeystoneLeaderboardsIndex

// ToBNet converts the CN response to the unified BNetMythicKeystoneLeaderboardsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMythicKeystoneLeaderboardsIndex) ToBNet() any {
	return r
}
