package wow_Title

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetTitleResponse is the unified BNet representation for Title.
type BNetTitle struct{}

// TitleResponse represents the raw CN API response for Title.
type CNTitle BNetTitle

// ToBNet converts the CN response to the unified BNetTitleResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTitle) ToBNet() any {
	return r
}
