

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_Title

type TitleModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	GenderName struct {
		Female string `json:"female,omitzero"`
		Male   string `json:"male,omitzero"`
	} `json:"gender_name"`
	ID   int    `json:"id,omitzero"`
	Name string `json:"name,omitzero"`
}





// Title represents the raw CN API response for Title.
type CNTitleModel TitleModel

// ToBNet converts the CN  to the unified BNetTitle.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTitleModel) ToBNet() any {
	return r
}
