package wow_Title

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetTitlesIndexResponse is the unified BNet representation for TitlesIndex.
type BNetTitlesIndex struct{}

// TitlesIndexResponse represents the raw CN API response for TitlesIndex.
type CNTitlesIndex BNetTitlesIndex

// ToBNet converts the CN response to the unified BNetTitlesIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNTitlesIndex) ToBNet() any {
	return r
}
