package D3_D3ItemType

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGetItemTypeIndexResponse is the unified BNet representation for GetItemTypeIndex.
type BNetGetItemTypeIndex struct{}

// GetItemTypeIndexResponse represents the raw CN API response for GetItemTypeIndex.
type CNGetItemTypeIndex BNetGetItemTypeIndex

// ToBNet converts the CN response to the unified BNetGetItemTypeIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetItemTypeIndex) ToBNet() any {
	return r
}
