

// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package D3_D3ItemType

type GetItemTypeIndexModel []struct {
	ID   string `json:"id,omitzero"`
	Name string `json:"name,omitzero"`
	Path string `json:"path,omitzero"`
}





// GetItemTypeIndex represents the raw CN API response for GetItemTypeIndex.
type CNGetItemTypeIndexModel GetItemTypeIndexModel

// ToBNet converts the CN  to the unified BNetGetItemTypeIndex.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetItemTypeIndexModel) ToBNet() any {
	return r
}
