package D3_D3ItemType

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGetItemTypeResponse is the unified BNet representation for GetItemType.
type BNetGetItemType struct{}

// GetItemTypeResponse represents the raw CN API response for GetItemType.
type CNGetItemType BNetGetItemType

// ToBNet converts the CN response to the unified BNetGetItemTypeResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGetItemType) ToBNet() any {
	return r
}
