package StarCraftII_Legacy

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetAchievementsResponse is the unified BNet representation for Achievements.
type BNetAchievements struct{}

// AchievementsResponse represents the raw CN API response for Achievements.
type CNAchievements BNetAchievements

// ToBNet converts the CN response to the unified BNetAchievementsResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAchievements) ToBNet() any {
	return r
}
