

package StarCraftII_Legacy

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// AchievementsModel is the unified BNet representation for Achievements.
type AchievementsModel struct{}




// Achievements represents the raw CN API response for Achievements.
type CNAchievementsModel AchievementsModel

// ToBNet converts the CN  to the unified BNetAchievements.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNAchievementsModel) ToBNet() any {
	return r
}
