package StarCraftII_Legacy

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetLadderResponse is the unified BNet representation for Ladder.
type BNetLadder struct{}

// LadderResponse represents the raw CN API response for Ladder.
type CNLadder BNetLadder

// ToBNet converts the CN response to the unified BNetLadderResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNLadder) ToBNet() any {
	return r
}
