package StarCraftII_Legacy

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetLaddersResponse is the unified BNet representation for Ladders.
type BNetLadders struct{}

// LaddersResponse represents the raw CN API response for Ladders.
type CNLadders BNetLadders

// ToBNet converts the CN response to the unified BNetLaddersResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNLadders) ToBNet() any {
	return r
}
