

package StarCraftII_Legacy

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// LaddersModel is the unified BNet representation for Ladders.
type LaddersModel struct{}




// Ladders represents the raw CN API response for Ladders.
type CNLaddersModel LaddersModel

// ToBNet converts the CN  to the unified BNetLadders.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNLaddersModel) ToBNet() any {
	return r
}
