

package StarCraftII_Legacy

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// MatchHistoryModel is the unified BNet representation for MatchHistory.
type MatchHistoryModel struct{}




// MatchHistory represents the raw CN API response for MatchHistory.
type CNMatchHistoryModel MatchHistoryModel

// ToBNet converts the CN  to the unified BNetMatchHistory.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMatchHistoryModel) ToBNet() any {
	return r
}
