package StarCraftII_Legacy

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMatchHistoryResponse is the unified BNet representation for MatchHistory.
type BNetMatchHistory struct{}

// MatchHistoryResponse represents the raw CN API response for MatchHistory.
type CNMatchHistory BNetMatchHistory

// ToBNet converts the CN response to the unified BNetMatchHistoryResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMatchHistory) ToBNet() any {
	return r
}
