

package StarCraftII_Legacy

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// RewardsModel is the unified BNet representation for Rewards.
type RewardsModel struct{}




// Rewards represents the raw CN API response for Rewards.
type CNRewardsModel RewardsModel

// ToBNet converts the CN  to the unified BNetRewards.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNRewardsModel) ToBNet() any {
	return r
}
