// // AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance
// Update time: 2026-01-08T18:27:09+08:00
package wow_CharacterEquipment

import "github.com/jinzhu/copier"

type CharacterEquipmentSummaryModel struct {
	Links struct {
		Self struct {
			Href string `json:"href,omitzero"`
		} `json:"self"`
	} `json:"_links"`
	Character struct {
		ID  int `json:"id,omitzero"`
		Key struct {
			Href string `json:"href,omitzero"`
		} `json:"key"`
		Name  string `json:"name,omitzero"`
		Realm struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
			Slug string `json:"slug,omitzero"`
		} `json:"realm"`
	} `json:"character"`
	EquippedItemSets []struct {
		DisplayString string `json:"display_string,omitzero"`
		Effects       []struct {
			DisplayString string `json:"display_string,omitzero"`
			IsActive      bool   `json:"is_active,omitzero"`
			RequiredCount int    `json:"required_count,omitzero"`
		} `json:"effects"`
		ItemSet struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"item_set"`
		Items []struct {
			IsEquipped bool `json:"is_equipped,omitempty,omitzero"`
			Item       struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"item"`
		} `json:"items"`
	} `json:"equipped_item_sets"`
	EquippedItems []struct {
		Armor *struct {
			Display struct {
				Color struct {
					A float64 `json:"a,omitzero"`
					B int     `json:"b,omitzero"`
					G int     `json:"g,omitzero"`
					R int     `json:"r,omitzero"`
				} `json:"color"`
				DisplayString string `json:"display_string,omitzero"`
			} `json:"display"`
			Value int `json:"value,omitzero"`
		} `json:"armor,omitempty,omitzero"`
		Binding struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"binding"`
		BonusList   []int  `json:"bonus_list,omitempty"`
		Context     int    `json:"context,omitzero"`
		Description string `json:"description,omitempty,omitzero"`
		Durability  *struct {
			DisplayString string `json:"display_string,omitzero"`
			Value         int    `json:"value,omitzero"`
		} `json:"durability,omitempty,omitzero"`
		Enchantments []struct {
			DisplayString   string `json:"display_string,omitzero"`
			EnchantmentID   int    `json:"enchantment_id,omitzero"`
			EnchantmentSlot struct {
				ID   int    `json:"id"`
				Type string `json:"type,omitzero"`
			} `json:"enchantment_slot"`
			SourceItem *struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"source_item,omitempty,omitzero"`
		} `json:"enchantments,omitempty"`
		InventoryType struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"inventory_type"`
		IsSubclassHidden bool `json:"is_subclass_hidden,omitempty,omitzero"`
		Item             struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
		} `json:"item"`
		ItemClass struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"item_class"`
		ItemSubclass struct {
			ID  int `json:"id"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
			Name string `json:"name,omitzero"`
		} `json:"item_subclass"`
		Level struct {
			DisplayString string `json:"display_string,omitzero"`
			Value         int    `json:"value,omitzero"`
		} `json:"level"`
		LimitCategory string `json:"limit_category,omitempty,omitzero"`
		Media         struct {
			ID  int `json:"id,omitzero"`
			Key struct {
				Href string `json:"href,omitzero"`
			} `json:"key"`
		} `json:"media"`
		ModifiedAppearanceID int `json:"modified_appearance_id,omitempty"`
		ModifiedCraftingStat []struct {
			ID   int    `json:"id,omitzero"`
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"modified_crafting_stat,omitempty"`
		Name            string `json:"name,omitzero"`
		NameDescription *struct {
			Color struct {
				A float64 `json:"a,omitzero"`
				B int     `json:"b"`
				G int     `json:"g,omitzero"`
				R int     `json:"r"`
			} `json:"color"`
			DisplayString string `json:"display_string,omitzero"`
		} `json:"name_description,omitempty,omitzero"`
		Quality struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"quality"`
		Quantity     int `json:"quantity,omitzero"`
		Requirements *struct {
			Faction *struct {
				DisplayString string `json:"display_string,omitzero"`
				Value         struct {
					Name string `json:"name,omitzero"`
					Type string `json:"type,omitzero"`
				} `json:"value"`
			} `json:"faction,omitempty,omitzero"`
			Level *struct {
				DisplayString string `json:"display_string,omitzero"`
				Value         int    `json:"value,omitzero"`
			} `json:"level,omitempty,omitzero"`
			PlayableClasses *struct {
				DisplayString string `json:"display_string,omitzero"`
				Links         []struct {
					ID  int `json:"id,omitzero"`
					Key struct {
						Href string `json:"href,omitzero"`
					} `json:"key"`
					Name string `json:"name,omitzero"`
				} `json:"links"`
			} `json:"playable_classes,omitempty,omitzero"`
		} `json:"requirements,omitempty,omitzero"`
		SellPrice *struct {
			DisplayStrings struct {
				Copper string `json:"copper,omitzero"`
				Gold   string `json:"gold,omitzero"`
				Header string `json:"header,omitzero"`
				Silver string `json:"silver,omitzero"`
			} `json:"display_strings"`
			Value int `json:"value,omitzero"`
		} `json:"sell_price,omitempty,omitzero"`
		Set *struct {
			DisplayString string `json:"display_string,omitzero"`
			Effects       []struct {
				DisplayString string `json:"display_string,omitzero"`
				IsActive      bool   `json:"is_active,omitzero"`
				RequiredCount int    `json:"required_count,omitzero"`
			} `json:"effects"`
			ItemSet struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"item_set"`
			Items []struct {
				IsEquipped bool `json:"is_equipped,omitempty,omitzero"`
				Item       struct {
					ID  int `json:"id,omitzero"`
					Key struct {
						Href string `json:"href,omitzero"`
					} `json:"key"`
					Name string `json:"name,omitzero"`
				} `json:"item"`
			} `json:"items"`
		} `json:"set,omitempty,omitzero"`
		ShieldBlock *struct {
			Display struct {
				Color struct {
					A float64 `json:"a,omitzero"`
					B int     `json:"b,omitzero"`
					G int     `json:"g,omitzero"`
					R int     `json:"r,omitzero"`
				} `json:"color"`
				DisplayString string `json:"display_string,omitzero"`
			} `json:"display"`
			Value int `json:"value,omitzero"`
		} `json:"shield_block,omitempty,omitzero"`
		Slot struct {
			Name string `json:"name,omitzero"`
			Type string `json:"type,omitzero"`
		} `json:"slot"`
		Sockets []struct {
			Context       int    `json:"context,omitempty,omitzero"`
			DisplayString string `json:"display_string,omitzero"`
			Item          struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"item"`
			Media struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
			} `json:"media"`
			SocketType struct {
				Name string `json:"name,omitzero"`
				Type string `json:"type,omitzero"`
			} `json:"socket_type"`
		} `json:"sockets,omitempty"`
		Spells []struct {
			Description  string `json:"description,omitzero"`
			DisplayColor *struct {
				A float64 `json:"a,omitzero"`
				B int     `json:"b,omitzero"`
				G int     `json:"g,omitzero"`
				R int     `json:"r,omitzero"`
			} `json:"display_color,omitempty,omitzero"`
			Spell struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"spell"`
		} `json:"spells,omitempty"`
		Stats []struct {
			Display struct {
				Color struct {
					A float64 `json:"a,omitzero"`
					B int     `json:"b"`
					G int     `json:"g,omitzero"`
					R int     `json:"r"`
				} `json:"color"`
				DisplayString string `json:"display_string,omitzero"`
			} `json:"display"`
			IsEquipBonus bool `json:"is_equip_bonus,omitempty,omitzero"`
			IsNegated    bool `json:"is_negated,omitempty,omitzero"`
			Type         struct {
				Name string `json:"name,omitzero"`
				Type string `json:"type,omitzero"`
			} `json:"type"`
			Value int `json:"value,omitzero"`
		} `json:"stats,omitempty"`
		Transmog *struct {
			DisplayString string `json:"display_string,omitzero"`
			Item          struct {
				ID  int `json:"id,omitzero"`
				Key struct {
					Href string `json:"href,omitzero"`
				} `json:"key"`
				Name string `json:"name,omitzero"`
			} `json:"item"`
			ItemModifiedAppearanceID int `json:"item_modified_appearance_id,omitzero"`
		} `json:"transmog,omitempty,omitzero"`
		UniqueEquipped string `json:"unique_equipped,omitempty,omitzero"`
		Weapon         *struct {
			AttackSpeed struct {
				DisplayString string `json:"display_string,omitzero"`
				Value         int    `json:"value,omitzero"`
			} `json:"attack_speed"`
			Damage struct {
				DamageClass struct {
					Name string `json:"name,omitzero"`
					Type string `json:"type,omitzero"`
				} `json:"damage_class"`
				DisplayString string `json:"display_string,omitzero"`
				MaxValue      int    `json:"max_value,omitzero"`
				MinValue      int    `json:"min_value,omitzero"`
			} `json:"damage"`
			Dps struct {
				DisplayString string  `json:"display_string,omitzero"`
				Value         float64 `json:"value,omitzero"`
			} `json:"dps"`
		} `json:"weapon,omitempty,omitzero"`
	} `json:"equipped_items"`
}

// CharacterEquipmentSummary represents the raw CN API response for CharacterEquipmentSummary.
type CNCharacterEquipmentSummaryModel struct {
	Character struct {
		Name  string `json:"name"`
		Realm struct {
			Name string `json:"name"`
			Slug string `json:"slug"`
		} `json:"realm"`
	} `json:"character"`
	EquippedItemSets []struct {
		DisplayString string `json:"display_string"`
		Effects       []struct {
			DisplayString string `json:"display_string"`
			IsActive      bool   `json:"is_active"`
			RequiredCount int    `json:"required_count"`
		} `json:"effects"`
		ItemSet struct {
			Name string `json:"name"`
		} `json:"item_set"`
		Items []struct {
			Item struct {
				Name string `json:"name"`
			} `json:"item"`
			IsEquipped bool `json:"is_equipped,omitempty"`
		} `json:"items"`
	} `json:"equipped_item_sets"`
	EquippedItems []struct {
		Armor struct {
			Display struct {
				Color *struct {
					A int `json:"a"`
					B int `json:"b"`
					G int `json:"g"`
					R int `json:"r"`
				} `json:"color"`
				DisplayString string `json:"display_string"`
			} `json:"display"`
			Value int `json:"value"`
		} `json:"armor"`
		ArtifactXp     int `json:"artifact_xp"`
		AzeriteDetails struct {
			Level struct {
				DisplayString string `json:"display_string"`
				Value         int    `json:"value"`
			} `json:"level"`
			PercentageToNextLevel int         `json:"percentage_to_next_level"`
			SelectedEssences      interface{} `json:"selected_essences"`
			SelectedPowers        interface{} `json:"selected_powers"`
			SelectedPowersString  string      `json:"selected_powers_string"`
		} `json:"azerite_details"`
		Binding struct {
			Name string `json:"name"`
			Type string `json:"type"`
		} `json:"binding"`
		BonusList  []int `json:"bonus_list"`
		Context    int   `json:"context"`
		Durability struct {
			DisplayString string `json:"display_string"`
			Value         int    `json:"value"`
		} `json:"durability"`
		InventoryType struct {
			Name string `json:"name"`
			Type string `json:"type"`
		} `json:"inventory_type"`
		ItemClass struct {
			Name string `json:"name"`
		} `json:"item_class"`
		ItemSubclass struct {
			Name string `json:"name"`
		} `json:"item_subclass"`
		Legacy string `json:"legacy"`
		Level  struct {
			DisplayString string `json:"display_string"`
			Value         int    `json:"value"`
		} `json:"level"`
		Media struct {
			Key struct {
				Href string `json:"href"`
			} `json:"Key"`
			Icon string `json:"icon"`
			Id   int    `json:"id"`
		} `json:"media"`
		ModifiedAppearanceId int    `json:"modified_appearance_id,omitempty"`
		Name                 string `json:"name"`
		NameDescription      struct {
			Color *struct {
				A int `json:"a"`
				B int `json:"b"`
				G int `json:"g"`
				R int `json:"r"`
			} `json:"color"`
			DisplayString string `json:"display_string"`
		} `json:"name_description"`
		Quality struct {
			Name string `json:"name"`
			Type string `json:"type"`
		} `json:"quality"`
		Quantity     int `json:"quantity"`
		Requirements struct {
			Level struct {
				DisplayString string `json:"display_string"`
				Value         int    `json:"value"`
			} `json:"level"`
			PlayableClasses struct {
				DisplayString string `json:"display_string"`
				Links         []struct {
					Name string `json:"name"`
				} `json:"links"`
			} `json:"playable_classes"`
			PlayableSpecializations interface{} `json:"playable_specializations"`
		} `json:"requirements"`
		SellPrice struct {
			DisplayStrings struct {
				Copper string `json:"copper"`
				Gold   string `json:"gold"`
				Header string `json:"header"`
				Silver string `json:"silver"`
			} `json:"display_strings"`
			Value int `json:"value"`
		} `json:"sell_price"`
		Set struct {
			DisplayString string `json:"display_string"`
			Effects       []struct {
				DisplayString string `json:"display_string"`
				IsActive      bool   `json:"is_active"`
				RequiredCount int    `json:"required_count"`
			} `json:"effects"`
			ItemSet struct {
				Name string `json:"name"`
			} `json:"item_set"`
			Items []struct {
				IsEquipped bool `json:"is_equipped,omitempty"`
				Item       struct {
					Name string `json:"name"`
				} `json:"item"`
			} `json:"items"`
		} `json:"set"`
		Slot struct {
			Name string `json:"name"`
			Type string `json:"type"`
		} `json:"slot"`
		Stats []struct {
			Display struct {
				Color struct {
					A int `json:"a"`
					B int `json:"b"`
					G int `json:"g"`
					R int `json:"r"`
				} `json:"color"`
				DisplayString string `json:"display_string"`
			} `json:"display"`
			Type struct {
				Name string `json:"name"`
				Type string `json:"type"`
			} `json:"type"`
			Value        int  `json:"value"`
			IsNegated    bool `json:"is_negated,omitempty"`
			IsEquipBonus bool `json:"is_equip_bonus,omitempty"`
		} `json:"stats"`
		Transmog struct {
			DisplayString string `json:"display_string"`
			Item          struct {
				Id  int `json:"id"`
				Key struct {
				} `json:"key"`
				Name string `json:"name"`
			} `json:"item"`
			ItemModifiedAppearanceId int `json:"item_modified_appearance_id"`
		} `json:"transmog"`
		Weapon struct {
			AttackSpeed struct {
				DisplayString string `json:"display_string"`
				Value         int    `json:"value"`
			} `json:"attack_speed"`
			Damage struct {
				DamageClass struct {
					Name string `json:"name"`
					Type string `json:"type"`
				} `json:"damage_class"`
				DisplayString string `json:"display_string"`
				MaxValue      int    `json:"max_value"`
				MinValue      int    `json:"min_value"`
			} `json:"damage"`
			Dps struct {
				DisplayString string  `json:"display_string"`
				Value         float64 `json:"value"`
			} `json:"dps"`
		} `json:"weapon"`
		IsSubclassHidden bool `json:"is_subclass_hidden,omitempty"`
		Sockets          []struct {
			DisplayString string `json:"display_string"`
			Item          struct {
				Name string `json:"name"`
			} `json:"item"`
			Media struct {
				Icon string `json:"icon"`
				Id   int    `json:"id"`
			} `json:"media"`
			SocketType struct {
				Name string `json:"name"`
				Type string `json:"type"`
			} `json:"socket_type"`
		} `json:"sockets,omitempty"`
		Enchantments []struct {
			DisplayString   string `json:"display_string"`
			EnchantmentId   int    `json:"enchantment_id"`
			EnchantmentSlot struct {
				Id   int    `json:"id"`
				Type string `json:"type"`
			} `json:"enchantment_slot"`
			SourceItem struct {
				Id  int `json:"id"`
				Key struct {
				} `json:"key"`
				Name string `json:"name"`
			} `json:"source_item"`
			Spell struct {
				Description string `json:"description"`
				Spell       struct {
					Name string `json:"name"`
				} `json:"spell"`
			} `json:"spell"`
		} `json:"enchantments,omitempty"`
		Spells []struct {
			Description string `json:"description"`
			Spell       struct {
				Name string `json:"name"`
			} `json:"spell"`
		} `json:"spells,omitempty"`
		UniqueEquipped       string `json:"unique_equipped,omitempty"`
		LimitCategory        string `json:"limit_category,omitempty"`
		ModifiedCraftingStat []struct {
			Id   int    `json:"id"`
			Name string `json:"name"`
			Type string `json:"type"`
		} `json:"modified_crafting_stat,omitempty"`
		Description string `json:"description,omitempty"`
	} `json:"equipped_items"`
}

// ToBNet converts the CN  to the unified BNetCharacterEquipmentSummary.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNCharacterEquipmentSummaryModel) ToBNet() any {
	b := &CharacterEquipmentSummaryModel{}
	copier.Copy(b, r)
	return b
}
