package wow_GuildCrest

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGuildCrestBorderMediaResponse is the unified BNet representation for GuildCrestBorderMedia.
type BNetGuildCrestBorderMedia struct{}

// GuildCrestBorderMediaResponse represents the raw CN API response for GuildCrestBorderMedia.
type CNGuildCrestBorderMedia BNetGuildCrestBorderMedia

// ToBNet converts the CN response to the unified BNetGuildCrestBorderMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuildCrestBorderMedia) ToBNet() any {
	return r
}
