package wow_GuildCrest

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGuildCrestEmblemMediaResponse is the unified BNet representation for GuildCrestEmblemMedia.
type BNetGuildCrestEmblemMedia struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	Assets []struct {
		Key   string `json:"key"`
		Value string `json:"value"`
	} `json:"assets"`
	Id int `json:"id"`
}

// GuildCrestEmblemMediaResponse represents the raw CN API response for GuildCrestEmblemMedia.
type CNGuildCrestEmblemMedia BNetGuildCrestEmblemMedia

// ToBNet converts the CN response to the unified BNetGuildCrestEmblemMediaResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuildCrestEmblemMedia) ToBNet() any {
	return r
}
