package wow_GuildCrest

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetGuildCrestComponentsIndexResponse is the unified BNet representation for GuildCrestComponentsIndex.
type BNetGuildCrestComponentsIndex struct{}

// GuildCrestComponentsIndexResponse represents the raw CN API response for GuildCrestComponentsIndex.
type CNGuildCrestComponentsIndex BNetGuildCrestComponentsIndex

// ToBNet converts the CN response to the unified BNetGuildCrestComponentsIndexResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNGuildCrestComponentsIndex) ToBNet() any {
	return r
}
