package wowClassic_MediaSearch

// AUTOMATICALLY GENERATED FILE, DO NOT EDIT
// This file is generated by tools/updater (model template)
// Author: @Thenecromance

// BNetMediaSearchResponse is the unified BNet representation for MediaSearch.
type BNetMediaSearch struct{}

// MediaSearchResponse represents the raw CN API response for MediaSearch.
type CNMediaSearch BNetMediaSearch

// ToBNet converts the CN response to the unified BNetMediaSearchResponse.
// Implementation intentionally returns nil and should be filled by hand when needed.
func (r *CNMediaSearch) ToBNet() any {
	return r
}
